### ISSUE TITLE
json matcher cannot assert same element with different property order inside an array 

### ISSUE THREAD

**Issue by wunaidage** [SpectoLabs/hoverfly#1001]
currently, [{a: 1, b: 2}] will not equals to [{b:2, a:1}] in json matcher.
is this a bug?

**Comment by tommysitu** [comment]
related issue https://github.com/SpectoLabs/hoverfly/issues/957

**Comment by wunaidage** [comment]
@tommysitu the array only contains one json object, it's just the property in that object is in different order. this is a different issue.

**Comment by tommysitu** [comment]
@wunaidage, just added a missing test with an example similar to yours and it passes: https://github.com/SpectoLabs/hoverfly/commit/a8d7f8b34ee6d174641a62a29a5283e15e136183

Maybe you need to double-check your simulation and the request?

**Comment by wunaidage** [comment]
@tommysitu thanks! I'll look into my passings

**Comment by wunaidage** [comment]
Hi @tommysitu I found an issue. for example, my simulation matching value is `[{\"a\":\"1\",\"b\":\"2\"}]` if my post body was passing `[{"a":"1","b":"2"}]` then hoverfly can find match. however if I pass `[{"a":"1", "b":"2"}]`, there's a space between comma and the following quote, hoverfly will fail to find match.

**Comment by wunaidage** [comment]
no space: 200
![image](https://user-images.githubusercontent.com/12276316/143134662-df18687a-db77-43ab-97ba-f49f5cc98961.png)
with space: 502
![image](https://user-images.githubusercontent.com/12276316/143134713-efe20d84-fb23-4cd7-8e01-8cc77045af2c.png)

**Comment by wunaidage** [comment]
+----------+---------+
| hoverctl | v1.3.2  |
| hoverfly | v1.3.2  |
+----------+---------+
here's my version. maybe you have fixed it in latest version?
