### ISSUE TITLE
Provide Apple Silicon release

### ISSUE THREAD

**Issue by ciscoo** [SpectoLabs/hoverfly#1014]
**Is your feature request related to a problem? Please describe.**

No problem currently, our internal tests seem to work fine so far.

I think it would be nice to have a native Apple Silicon release for Hoverfly for those that have M1 MacBooks.

**Describe the solution you'd like**

Native Apple Silicon release for Hoverfly

**Describe alternatives you've considered**

Continue using `darwin/amd64` which works so far.

**Additional context**

My team and others are currently undergoing a hardware refresh at my company, so it would be nice to have a native Apple Silicon release of Hoverfly.

**Comment by tommysitu** [comment]
That's a good idea. We can do that for the next release.

**Comment by ezienecker** [comment]
Hi @tommysitu, I think it would be helpful for many if you would also publish Docker images with this architecture. I have already created a pull request for this. It would be nice if you could take a look at it. https://github.com/SpectoLabs/hoverfly/pull/1019

**Comment by ezienecker** [comment]
Hi @tommysitu, when can we expect a release to be able to include the new image in our projects?

**Comment by tommysitu** [comment]
@ezienecker I can do a release today, have you tried out the docker image from master build? Is it good?

**Comment by tommysitu** [comment]
closed by https://github.com/SpectoLabs/hoverfly/releases/tag/v1.3.7

**Comment by ezienecker** [comment]
@tommysitu Looks good!

1.3.6 Image

```
➜ docker run spectolabs/hoverfly:v1.3.6
Unable to find image 'spectolabs/hoverfly:v1.3.6' locally
v1.3.6: Pulling from spectolabs/hoverfly
3aa4d0bbde19: Pull complete
0b52bafb6df8: Pull complete
a07b0fbeb251: Pull complete
Digest: sha256:ab5e18e090aa04a2c34aa12d7e0f8c378f22f2f92afa441bebdc973888d4beaf
Status: Downloaded newer image for spectolabs/hoverfly:v1.3.6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
INFO[2022-08-23T05:14:57Z] Listen on specific interface                  host=0.0.0.0
```

1.3.7 Image

```
➜ docker run spectolabs/hoverfly:v1.3.7
Unable to find image 'spectolabs/hoverfly:v1.3.7' locally
v1.3.7: Pulling from spectolabs/hoverfly
9b18e9b68314: Pull complete
3443cf2da25f: Pull complete
3963aac20d41: Pull complete
Digest: sha256:e65a0cbe53d35c4d063132e6cedc5cd4939d9c61c65f945ab94faba2d0572d7e
Status: Downloaded newer image for spectolabs/hoverfly:v1.3.7
INFO[2022-08-23T05:15:13Z] Listen on specific interface                  host=0.0.0.0
```

Thank you!
