### ISSUE TITLE
Make hoverflyjava use latest hoverfly binary 

### ISSUE THREAD

**Issue by toadornode** [SpectoLabs/hoverfly#1027]
There was an issue opened where any JSON request/response beginning with an array bracket '['
 was causing mismatches if there is a newline or space characters. see here: https://github.com/SpectoLabs/hoverfly/issues/964

The issue was fixed and the latest binary works, however, hoverflyjava 0.14.0 is still using older versions of the binary. Would you be able to create a new version of hoverflyjava that utilize the latest hoverfly binaries please?

**Comment by tommysitu** [comment]
yeah, can update it today

**Comment by tommysitu** [comment]
wait, that fix has been in hoverfly for ages, the latest hoverfly-java `v0.14.3` should contains all the bug fix release already
