### ISSUE TITLE
Disable tls option doesn't work in v1.3.7

### ISSUE THREAD

**Issue by toadornode** [SpectoLabs/hoverfly#1028]
## Description of the bug

In version 1.1.3 I am using --disable-tls and it works fine, I am able to get a response back from our API. But when I use v1.3.7 of hoverctl with the same flag it tries to validate certs. 

Not sure what changed between these versions. I am running on Mac OSX arch 64 and and using mac os binary file. 

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
(paste here)
```
**If possible, add screenshots to help explain your problem**

## Additional relevant information
1. Hoverfly version: 
2. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
The Hoverfly CA cert you were using with the old version had expired. You need to trust this new cert to use v1.3.7: https://github.com/SpectoLabs/hoverfly/blob/master/core/cert.pem

**Comment by toadornode** [comment]
Thank you :) @tommysitu
