### ISSUE TITLE
Not able to fetch version hoverfly v2 

### ISSUE THREAD

**Issue by sachin-raja** [SpectoLabs/hoverfly#1060]
When I run `go get github.com/SpectoLabs/hoverfly/v2 `

I get an error stating 

> go: module github.com/SpectoLabs/hoverfly@upgrade found (v1.4.0), but does not contain package github.com/SpectoLabs/hoverfly/v2

Seems like the package has a versioning issue. 

## Additional relevant information
1. Hoverfly version: v2.0.0

**Comment by tommysitu** [comment]
sorry we released the one with a wrong tag, the latest should be `v1.5.0`. It's still backward compatible. 

If you installed it through brew before, you can `brew uninstall hoverfly` and then re-install it again to pick up `v1.5.0`
