### ISSUE TITLE
Version mismatch between the website docs and the release package

### ISSUE THREAD

**Issue by akkadaya** [SpectoLabs/hoverfly#1062]
On the website, it says v2.0.0
<img width="296" alt="image" src="https://user-images.githubusercontent.com/1834445/221744858-a39ecadd-97e9-41a3-9eea-8864fe1dad6f.png">
Meanwhile, in Release it says v1.5.0
<img width="504" alt="image" src="https://user-images.githubusercontent.com/1834445/221744983-9900ce05-1942-4c6b-a439-fabd939fdf8b.png">

**Comment by kapishmalik** [comment]
There was an issue with version 2 and @tommysitu rolled it back to v1.5.0. So, he just needs to update in the documentation.

**Comment by tommysitu** [comment]
@akkadaya the latest is v1.5.0 actually, I have just removed the v2.0.0 version from readthedocs as well. Sorry for the confusion.
