### ISSUE TITLE
Hoverfly not installing via "brew" on Mac

### ISSUE THREAD

**Issue by sachin-shashikant-waingankar-db** [SpectoLabs/hoverfly#1072]
## Description of the bug
While trying to install Hoverfly latest version, we are getting download error

## Steps to reproduce the issue
1. run from terminal : brew install SpectoLabs/tap/hoverfly
2. error detected : Downloading https://github.com/SpectoLabs/hoverfly/archive/v1.5.2.tar.gz
curl: (22) The requested URL returned error: 407   

Analysed the location of the location : "https://github.com/SpectoLabs/hoverfly/archive/v1.5.2.tar.gz" - this does not exists, the folder "archive" is not present.

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
https://github.com/SpectoLabs/hoverfly/archive/v1.5.2.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 407
HTTP/1.1 407 authenticationrequired

```
**If possible, add screenshots to help explain your problem**

### Expected result

Should be able to download the latest version using "brew"

## Additional relevant information
1. Hoverfly version: v1.5.2
3. Anything that might help us to diagnose the problem

**Comment by kapishmalik** [comment]
@tommysitu could you please help here?

**Comment by sachin-shashikant-waingankar-db** [comment]
@tommysitu and @kapishmalik - Please help resolve this, as we are not able to progress with the product

**Comment by tommysitu** [comment]
> @tommysitu and @kapishmalik - Please help resolve this, as we are not able to progress with the product

@sachin-shashikant-waingankar-db can you try installing an older version using brew? I am away from my computer for a couple of weeks

**Comment by kapishmalik** [comment]
@sachin-shashikant-waingankar-db you can try downloading executables directly from this link. https://docs.hoverfly.io/en/latest/pages/introduction/downloadinstallation.html

**Comment by tommysitu** [comment]
I run the same command on mac (Ventura 13.3.1): `brew install SpectoLabs/tap/hoverfly`, and it works fine. I don't think it's a hoverfly issue, will close this for now.
