### ISSUE TITLE
Templating: Invalid example of 'replace' helper method

### ISSUE THREAD

**Issue by smb-z** [SpectoLabs/hoverfly#1074]
## Description of the bug
[Documentation](https://docs.hoverfly.io/en/latest/pages/keyconcepts/templating/templating.html#helper-methods) on helper method 'replace' states:

Description|Example|Result
--|--|--
Replace all occurrences of the old value with the newvalue in the target string|`{{ replace Request.Body 'be' 'mock' }}`<br>where Request.Body has the value of “to be or not to be”|to mock or not to mock

If you try to use this example as is, you'll get following error in log file:
```
Failed to applying body templating: Evaluation error: Helper 'Body' called with wrong number of arguments, needed 3 but got 0
```

This error arises because Request.Body is not a variable but a helper function itself and must be provided with parameters.

Correct example is:

Description|Example|Result
--|--|--
Replace all occurrences of the old value with the newvalue in the target string|`{{ replace (Request.Body 'jsonpath' '$.text') 'be' 'mock' }`<br>where Request.Body has the value of `{"text":“to be or not to be”}`| to mock or not to mock

**Comment by tommysitu** [comment]
Thanks for pointing that out. I have updated it now.

**Comment by smb-z** [comment]
Hi Tommy, 
I think proper result in the example would be `to mock or not to mock`, not `{“text”:”to mock or not to mock”}`

Request.Body will return `“to be or not to be”` and not a JSON

**Comment by tommysitu** [comment]
thanks, updated.
