### ISSUE TITLE
Invalid data when using template 

### ISSUE THREAD

**Issue by vuklip** [SpectoLabs/hoverfly#1107]
## Description of the bug

Invalid getting value by template. Let me explain. 

## Steps to reproduce the issue

I have this simulation: 

```json
{
    "data": {
        "pairs": [
            {
                "request": {
                    ...
                },
                "response": {
                    "status": 200,
                    "body": "{ "id": "{{ Request.Body 'jsonpath' '$.params.otp.id' }}" }",
                    "encodedBody": false,
                    "headers": {
                        "Content-Type": [
                            "application/json"
                        ]
                    },
                    "templated": true
                }
            }
        ],
       ...
}
```

and I send the request like 

```json
{"params":{"otp":{"id":998974625887}}}
```

### Observed result
```
{"id": "9.98974625887e+11"}
```
**If possible, add screenshots to help explain your problem**

### Expected result
```
{"id": "998974625887"}
```

## Additional relevant information
1. Hoverfly version: 1.6.1 and older. I also tested with 1.3.6.
2. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
@vuklip I did notice this bug recently as well, I will merge my fix soon.

**Comment by vuklip** [comment]
Nice, thx! 
Waiting for version 1.6.2 :)

**Comment by tommysitu** [comment]
fixed in https://github.com/SpectoLabs/hoverfly/releases/tag/v1.6.2
