### ISSUE TITLE
Responses with status code 204 over HTTPS not working as expected

### ISSUE THREAD

**Issue by jonas-z-ericsson** [SpectoLabs/hoverfly#1122]
## Description of the bug

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3

> All 1xx (Informational), 204 (No Content), and 304 (Not Modified) responses do not include a message body.

But when receiving e.g. a 204 when using HTTPS the receiving buffer contains '0\r\n'. 
This will break some http clients.

It is probably related to this bug: https://github.com/SpectoLabs/hoverfly/issues/865

But now it only has that behaviour for requests with method HEAD: https://github.com/SpectoLabs/hoverfly/blob/master/vendor/github.com/SpectoLabs/goproxy/https.go#L289

## Steps to reproduce the issue

Same as https://github.com/SpectoLabs/hoverfly/issues/865

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
None
```

Some clients can't handle this behaviour properly, e.g. jetty-client 12.0.7 for Java.

![image](https://github.com/SpectoLabs/hoverfly/assets/107255828/5c018932-a1c5-4eee-971d-a1de779859b5)

**If possible, add screenshots to help explain your problem**

## Additional relevant information
1. Hoverfly version: 1.8.0
2. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
It's definitely a recursion, I can fix it in the coming release.

**Comment by hjalle83** [comment]
I got it working with the new version! 👍
