### ISSUE TITLE
miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [SpectoLabs/hoverfly#1131]
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9243209781/job/25427055647

```
====================================================================================================
append to slice `indexes` with non-zero initialized length at https://github.com/SpectoLabs/hoverfly/blob/master/core/templating/templating.go#L160:14
====================================================================================================
```

the `indexes := make([]JournalIndex, len(journal.Indexes))` should be `indexes := make([]JournalIndex, 0, len(journal.Indexes))`

**Comment by kapishmalik** [comment]
@alingse  this is being fixed. Closing this issue.
