### ISSUE TITLE
https request very slowly

### ISSUE THREAD

**Issue by arslantopcu1** [SpectoLabs/hoverfly#1140]
I am using hey/Jmeter to perform load testing on HTTPS site. HTTP request very fast but when I play script HTTPS Request is working very slow. It take long time to initiate and complete each request as shown below in image.

Hoverfly is running simulate mode.

 hey -n 50  -c 50 -x http://localhost:8500   https://api.restful-api.dev/objects
<img width="534" alt="image" src="https://github.com/user-attachments/assets/86d9f88a-c782-4b3b-bcf2-72897163c1c8">

 hey -n 50  -c 50 -x http://localhost:8500   http://api.restful-api.dev/objects
<img width="518" alt="image" src="https://github.com/user-attachments/assets/44414543-b37c-4486-9fef-d564e6012c99">

**Comment by tommysitu** [comment]
It's likely that the [goproxy](https://github.com/elazarl/goproxy) library is not caching the TLS connection... You can try [using  hoverfly as a webserver](https://docs.hoverfly.io/en/latest/pages/keyconcepts/webserver.html) to help you with simulating loads for the time being.
