### ISSUE TITLE
Upgrade dependency 'ChrisTrenkamp/xsel' to eliminate checksum mismatch.

### ISSUE THREAD

**Issue by HappyHacker123** [SpectoLabs/hoverfly#1147]
**Is your feature request related to a problem? Please describe.**
Currently `hoverfly` depends on `ChrisTrenkamp/xsel@v0.9.6`. However `xsel` may have retagged version v0.9.6, so the checksum from the code in github does not match the checksum saved in proxy `sum.golang.org`.
Consequently, when trying to download `ChrisTrenkamp/xsel@v0.9.6` directly, the following error will occur like below.
```
root@iZj6c5flh0q5ax3d1ttfuhZ:~/temp# GOPROXY=direct go get github.com/ChrisTrenkamp/xsel@v0.9.6
go: downloading github.com/ChrisTrenkamp/xsel v0.9.6
go: github.com/ChrisTrenkamp/xsel@v0.9.6: verifying module: checksum mismatch
        downloaded: h1:e4wn/FSaXDSkMyKsgCX8LsxwB2IVPhcAnnJLVFm2XWw=
        sum.golang.org: h1:0TmX81Wq2v2SnssP9SwBzz68KArsj5a8Dt9Ppj095QM=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Describe the solution you'd like**
Upgrade xsel to a version where there's no checksum mismatch like v0.9.7

**Comment by tommysitu** [comment]
should be a simple fix. thanks!

**Comment by tommysitu** [comment]
resolved in https://github.com/SpectoLabs/hoverfly/releases/tag/v1.10.3

**Comment by HappyHacker123** [comment]
Many thanks!
