### ISSUE TITLE
Capture timing of requests

### ISSUE THREAD

**Issue by nmck257** [SpectoLabs/hoverfly#1153]
(I'm new to Hoverfly)

**Is your feature request related to a problem? Please describe.**
I think Hoverfly could be useful not just for unit testing, but performance testing.
In (some forms of) performance testing, I would like to stub out my application's connections to downstream webservices and return fixed responses, but with realistic (data-driven) delay.

**Describe the solution you'd like**
Could `Capture` mode be enhanced to grab not only request/response, but also the time taken for the roundtrip? This data could (minimally) be read by the developer to better-inform "hardcoded" delays, or a step further, could feed directly into `Simulate` mode.

**Describe alternatives you've considered**
Manually researching and configuring delays for requests.

**Comment by tommysitu** [comment]
As a starting point, we can record the latency as fixed delay in capture mode. It seems easy to implement.

**Comment by kapishmalik** [comment]
@tommysitu can I pick this up?

**Comment by tommysitu** [comment]
> @tommysitu can I pick this up?

@kapishmalik of course if you have time. Thank you!

**Comment by kapishmalik** [comment]
Sure, I will manage and start working on the same.

**Comment by kapishmalik** [comment]
Raised PR - https://github.com/SpectoLabs/hoverfly/pull/1154

**Comment by nmck257** [comment]
Very cool to see the quick turnaround on this idea!
