### ISSUE TITLE
unable to use hoverfly with firefox / https

### ISSUE THREAD

**Issue by boakley** [SpectoLabs/hoverfly#121]
Getting hoverfly to work as a proxy for http connections with firefox was quite simple. However, I'm unable to get it to work as a proxy for firefox with https connections. I have no idea where to even start with the debugging. 

I added the certificate to my system with the following commands:

```
 $ sudo cp ca.pem /usr/local/share/ca-certificates/hoverfly.crt
 $ sudo update-ca-certificates
```

In firefox, I went into the preferences for connection settings and manually set a proxy using "localhost" and port 8500.  I added the `ca.pem` certificate, also through the preferences panel. 

I started hoverfly with the following:

    $ ./hoverfly_linux_amd64  --capture -v

When I go to https://yahoo.com the page says "Secure Connection Failed" and this is what I see on stdout:

```
$ ./hoverfly_linux_amd64  --capture -v
{"databaseName":"requests.db","level":"info","msg":"Initiating database","time":"2016-02-25T09:14:48-06:00"}
{"level":"debug","msg":"new counter created, registration successful","time":"2016-02-25T09:14:48-06:00"}
{"Destination":".","Mode":"capture","ProxyPort":"8500","level":"info","msg":"Proxy prepared...","time":"2016-02-25T09:14:48-06:00"}
{"AdminPort":"8888","level":"info","msg":"Admin interface is starting...","time":"2016-02-25T09:14:48-06:00"}
[negroni] listening on :8888
2016/02/25 09:14:52 [001] INFO: Running 2 CONNECT handlers
2016/02/25 09:14:52 [001] INFO: on 0th handler: &{2 <nil> 0x570300} yahoo.com:443
2016/02/25 09:14:52 [001] INFO: Assuming CONNECT is TLS, mitm proxying it
2016/02/25 09:14:52 [001] INFO: signing for yahoo.com
2016/02/25 09:14:52 [001] WARN: Cannot handshake client yahoo.com:443 remote error: bad certificate
```

Are there extra or different configuration steps I need to take?

**Comment by rusenask** [comment]
Hi, thanks. Looking into it.

**Comment by boakley** [comment]
here's a new data point:

0.5.12 is working much better (**thanks!**), though not yet 100%. I may be jumping the gun, but I just happened to visit the site right after you pushed the new bits so I thought I would give it a try. I figure you might be interested in what I've learned.

I downloaded the new bits, updated firefox to 44.0.2, created a new firefox profile, configured it to use the hoverfly proxy for everything, downloaded the new cert, and with that I was able to interact with some https sites. Huzzah! (and did I mention: **thanks!**)

However, I seem to be having problems with sites that use authentication.  For example, I can go to https://www.google.com and search all day long. if I try to login to gmail (https://accounts.google.com/ServiceLoginAuth), google responds with "Invalid Request" when I submit my username and password. If I turn the proxy off, I'm able to log in by simply refreshing the page (read: there's no typo in my username or password).

As another example, I'm also having problems logging into https://www.createspace.com. The pages render, but I can't get past the login prompt. It shows a message stating "javascript and cookies must be enabled". Maybe that message is a red herring, and is just a catch all for "we can't log you in for some reason".

**Comment by rusenask** [comment]
Hi @boakley,
Many thanks for feedback. The thing is that I haven't solved it yet. What I did - created another certificate and used different encoding, hoping that firefox will be happy with it - apparently it's not.
I will try to make those pages work :)

**Comment by boakley** [comment]
I appreciate your efforts in solving it. You're very close!

I think hoverfly could be a real boon to those of us who have to test
against external servers that we don't control.  I wish I could help, but I
have no expertise working on https proxies and authentication and whatnot.
I'm happy to spend time testing each release, though.

--bryan

**Comment by rusenask** [comment]
Hi @boakley ,
Looks like it's finally working:
![image](https://cloud.githubusercontent.com/assets/9080105/14015677/bec9dce6-f1b2-11e5-9a17-d0c696c29ca8.png)

The trick is to use Hoverfly to generate certificate:
```
./hoverfly -generate-ca-cert
```

And then specifying hoverfly to use it:
```
./hoverfly -cert cert.pem -key key.pem
```

This functionality was added with https://github.com/SpectoLabs/hoverfly/pull/165 PR, currently it's in develop and will be in master soon. If you need a binary - I can send you one :)

Cheers,
-k

**Comment by boakley** [comment]
This is great. I originally thought I would wait for the next release to
try it out, but if it's going to be another week or two and you're still
willing to send me a binary, I'll be glad to test it.

**Comment by rusenask** [comment]
hey, I will just go through the current PR and make a new release tomorrow :)

**Comment by tjcunliffe** [comment]
@boakley did you have any luck with the new certificate generation functionality in Hoverfly?

**Comment by boakley** [comment]
I apologize; I haven't had time to go back and revisit it. I'll see if I
can carve out some time this week.

--bryan

**Comment by boakley** [comment]
I am still unable to login to gmail using hoverfly as a proxy. These are the steps that I took:

1. Downloaded hoverfly_v0.5.17_linux_amd64 and renamed to "hoverfly" and set the execute bit
2. generated the keys with `./hoverfly -cert cert.pem -key key.pem`
3. started hoverfly in capture mode with `./hoverfly -cert cert.pem -key key.pem -capture -v `
4. started Firefox with profile manager, and created a new profile named "hoverfly"
5. I went to advanced settings/network, set my proxy host to "localhost", port to 8500 for all proxies
6. I went to advanced settings/certificates, clicked "view certificates", and then clicked "Import..." to import the cert.pem and key.pem files
7. opened a new tab and went to https://accounts.google.com/ServiceLoginAuth
8. I entered my email address, clicked "Next"
9. I entered my password, clicked "Next"

And at this point I'm staring at a page that says "Oops! Your browser seems to have cookies disabled". I verified that in the firefox settings, cookies are indeed enabled.

I also tried adding `-tls-verification=false` when starting hoverfly; that seemed to have no effect.

Did I skip a step?

**Comment by tjcunliffe** [comment]
Hi @boakley, thanks for your response - we'll take a look at this and get back to you shortly.

**Comment by benjih** [comment]
Hey @boakley,

Following the steps you gave, I was able to recreate this issue on Firefox. I was also able to recreate this issue using Google Chrome. We know https works with other sites, but my feeling is there is something unique about the Google Services login causing this issue. My thinking is that this might be an issue with two way SSL support, a feature that we know is not currently working on Hoverfly.

I think that the title of this issue may now be incorrect and we may be looking at a cross browser issue.

**Comment by boakley** [comment]
FWIW, this isn't just a google issue. I've seen the same problem on a
couple other websites.

Since you know two way ssl support isn't working, is this something you're
actively trying to fix, or is it a difficult problem that you have no plans
to fix anytime soon?

**Comment by mogronalol** [comment]
@boakley 

We have plans to fix the issue with two way ssl shortly, it looks like it will be on our roadmap for our next release.

**Comment by boakley** [comment]
Cool. I'll keep an eye out for it.

**Comment by benjih** [comment]
Hey @boakley,

I am going to close this ticket as we already have a ticket around implementing two way SSL #201.

Thanks for the feedback.
