### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by thedrow** [SpectoLabs/hoverfly#152]
It'd be easier to install hoverfly through a homebrew formula.

**Comment by rusenask** [comment]
Hi,

Thanks, we have that on our to do list. The problem up until now with it was that homebrew has this slow process of version updates (unlike systems such as pypi index) where you have to submit a PR with new version and I was releasing new versions 1-2 times per week. I will submit hoverfly brew formula in the next few weeks. 

Karolis

**Comment by benjih** [comment]
Just an update, we are still planning on doing this. As Hoverfly has become more mature in terms of features and the frequency of releasing has changed, I believe now is the perfect time to create a Homebrew formula.

I can't put a time frame on this, but it'll happen soon.

**Comment by benjih** [comment]
Hey @thedrow,

We now have hoverfly available as a brew formula.

```
brew install SpectoLabs/tap/hoverfly
```
