### ISSUE TITLE
Lookup response by key only

### ISSUE THREAD

**Issue by mozey** [SpectoLabs/hoverfly#169]
In my use case it is not practical for me to record the responses, I want to write them manually.

I've looked around a bit and it doesn't seem like it is currently possible, would it possible to make hoverfly lookup a response from import file by key / id only?

When you do a proxy call and a response is not found the message is:

    Hoverfly Error! Could not find recorded request, please record it first!. 
    Got error: key "7a4e6d5c94e616d64255313523d9699a" not found 

I then want to create an import file without specifying what the request is:
```

{
    "data": [
        {
            "response": {
                "status": 500,
                "body": "1234: Some error",
                "headers": {"Content-Type": ["text/html; charset=utf-8"]}
            },
            "id": "7a4e6d5c94e616d64255313523d9699a"
        }
    ]
}



```

**Comment by rusenask** [comment]
Hey, there is a "Add Record" button on admin panel where you can define request and response of your own: 
![screen shot 2016-04-01 at 15 41 11](https://cloud.githubusercontent.com/assets/9080105/14210281/3b2a1058-f820-11e5-8728-e5266b925d27.png)

and then you will see:
![screen shot 2016-04-01 at 15 41 18](https://cloud.githubusercontent.com/assets/9080105/14210319/6e30a37c-f820-11e5-92bc-3768aa98a395.png)

I don't know if this is helpful for you. Since I am working on a new frontend UI - suggestions/feature requests are welcome.

**Comment by mozey** [comment]
I saw that UI, and I know you can populate request.db using an import file.

What I would like to do is lookup a response (just by filling in the key) without specifying exactly what request is.

Suppose I could do this by writing some middleware. I just thought having this as a build in feature might be useful to others too.

**Comment by rusenask** [comment]
Do you want to return that response for every request you make?

**Comment by mozey** [comment]
No, I'm assuming the key from above is a hash of the request data? So I want to avoid having to type out the request. I just want to specify for this key return this response.

**Comment by rusenask** [comment]
Oh, that's what I thought. Unfortunately you can't do that since request key is regenerated every time you import stuff into hoverfly (so if you modify exported JSON files and import them again - request matching will be ok). In your case - creating a middleware would be the right way.

**Comment by mogronalol** [comment]
I'm a little lost here - if you were to specify the hash yourself, how would you generate it?  You would need to know the request in order to generate it's hash?

**Comment by mozey** [comment]
@rusenask Is doesn't look like the key changes. For the same request I always get back the same key in the not found message.

@mogronalol I run the request against the proxy with empty requests.db, Hoverfly responds with:

    "7a4e6d5c94e616d64255313523d9699a" not found

I would then like to create a record that only specifies the key and the response. I don't particularly care what the request is, besides knowing that it will produce the key mentioned above.

**Comment by mogronalol** [comment]
I am still a little confused - in order for you to know what that hash code is you need to know what the request is.  So when you say you don't care what the request is, I don't understand because without it you would never be able to know what the hash is as it's required to generate the hash.  

Could you please give step by step instructions on what you would like your workflow to be please - how would you want to get the hash in the first place in order to manually add hash->response into Hoverfly?

**Comment by dac09** [comment]
Hi,

I may understand what @mozey was asking, as I came here to ask the same question.

I'm capturing a few POST requests, but I'd like hoverfly to respond to a POST to that endpoint with the same response regardless of the body I send.

Is that possible?

Thanks!

**Comment by mozey** [comment]
This [middleware](https://gist.github.com/mozey/00ab8bf387bee513f1f748e374da349e) illustrates the features I wanted. That is

-  Lookup the response by key, where the key is generated from the request content. Given the same request the generated key will always be the same. To accomplish this I sort by property if the request body is JSON. An improvement would be to also sort the query params.

- I've stored each request (optional) and response in a stub, where the filename has the format KEY.json. For my use case the stubs become part of the test suite, so storing them individually in version control is required.

- The middleware must be referenced from hoverfly like this `--middleware="middleware.py /path/to/stubs"` and it can be tested stand alone like this `middleware.py /path/to/stubs KEY.json`

- Sometime the request contains things that change with every request, like a timestamp. The middleware has a list of properties `strip_keys`, these will be removed from the request body (if JSON) before the key is generated.

- Storing JSON (or XML etc) inside JSON is not very readable. The middleware has the option to set response body to a path.

@daco you could modify my middleware script to do what you want, just remove all the lines that start with `request_copy["body"] = `. They key will then be generated using the endpoint details only.

**Comment by dac09** [comment]
Thanks!

**Comment by psisodia** [comment]
@dac09 I have tried using globMatch on POST body request in json  file and it accepts POST and returns 202 but no response body, I am looking for answer for this same problem too.
