### ISSUE TITLE
Edit request with graphic interface

### ISSUE THREAD

**Issue by neoshadybeat** [SpectoLabs/hoverfly#183]
Hi should be nice, edit the request from ui interface, Is there any plan on that?

**Comment by tjcunliffe** [comment]
Hi - this is on our roadmap. We've re-built the admin UI (currently on the develop branch) to make it easier to extend. We will be looking at UI-based request editing in some more detail soon. Contributions are welcome of course!

**Comment by dac09** [comment]
I came here to suggest something similar - it would be amazing if you could also set a 'breakpoint' on a request and can modify it using the UI before responding. So like a debugger response interceptor.

I'm assuming there isn't a way to do this already?

**Comment by benjih** [comment]
We have recently open sourced our new Angular front end, which we are looking to expand and add new functionality to. I have created two issues capturing what was in this ticket. These tickets can be found at https://github.com/SpectoLabs/hoverfly-ui/issues/18 and https://github.com/SpectoLabs/hoverfly-ui/issues/19.
