### ISSUE TITLE
Binary data response with synthetic middleware

### ISSUE THREAD

**Issue by mozey** [SpectoLabs/hoverfly#195]
With python middleware setting a text response body is simple

    payload_dict['response']['body'] = "hello"

Or if the response body is in a file

    body_path = "path/to/response_body.txt"
    body_file = open(body_path, "r")
    payload_dict['response']['body'] = body_file.read()

How would I respond with a binary data file? For example an image

    body_path = "path/to/image.jpg"
    body_file = open(body_path, "r")
    payload_dict['response']['body'] = body_file.read()

Above fails with

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by benjihooper** [comment]
Hey @mozey 

In the upcoming release of Hoverfly, we have addressed this issue. We have changed the Response to include a new boolean value field called "encodedBody". When you export data out of Hoverfly, this field will be marked as true if the Response body is binary. If this field is true, the body will be base64 encoded so that the data can be transported in a JSON format without a loss of data. 

This change will also affect middleware. With the next version of Hoverfly, you'll be able to base64 encode your binary data file and set that string as the response body, set the "encodedBody" flag to true and then Hoverfly will respond with your binary data response.

We'll be releasing this soon, so keep an eye out!

Warmest regards,
Benji

**Comment by benjihooper** [comment]
Hello again @mozey,

We've just released [v0.6.0 of Hoverfly](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.6.0) that includes the fix I mentioned in my previous comment. Hopefully you can check out the new version and give it a spin.

If you have any issues with the binary data in responses, come back and let me know.

I hope this helps you.

Warmest regards,
Benji

**Comment by mozey** [comment]
@SpectoBenji, thanks for letting me know.

Don't quite have this working yet, does the code below look correct? I can't find in the documentation where to set encodedBody on the payload_dict:

    body_file = open(body_path, "rb")
    binary = body_file.read()
    payload_dict['response']['headers']['Content-Length'] = \
        len(binary)
    payload_dict['response']['encodedBody'] = True
    encoded = base64.b64encode(binary)
    payload_dict['response']['body'] = encoded.decode("utf-8")

**Comment by benjih** [comment]
Hey @mozey,

It looks like what you have done is correct, so I will need to investigate as to what exactly is going on with this. I will look into this as soon as I can and get back to you as soon as possible.

Thanks for getting back to us, it is appreciated very much.

(@SpectoBenji is me but a different account)

**Comment by benjih** [comment]
Hello again @mozey,

Having a further look at what you sent, it looks like you are base64 encoding the data and then decoding it into UTF-8 characters as you set it as the response body, causing a loss of binary data.

`payload_dict['response']['body'] = encoded.decode("utf-8")`

My advice would be to remove the decode function on the encoded string when you set it on the payload_dict.

`payload_dict['response']['body'] = encoded`

We have a very similar piece of middleware that we use in our test suite which I have tested and found to be working. It might be worth having a look at that also.

[testdata/binary_middleware.py](https://github.com/SpectoLabs/hoverfly/blob/master/testdata/binary_middleware.py)

I hope this helps.

**Comment by mozey** [comment]
@benjih It does help, I'm not getting a response when I test with my code, but it must be something else. Will do some more testing.

The `testdata/binary_middleware.py` example works with Python 2.7.3 but not with 3.2.3

For Python 3 I have to make the following changes:

    bytes = open(os.getcwd() + "/testdata/1x1.png", "rb").read()
    ...
    payload_dict['response']['body'] = responseBody.decode("utf-8")

**Comment by benjih** [comment]
Hey @mozey,

If its possible, could you please attach the complete middleware you are trying to run to this issue along with the version of python you are working with? It would help me in trying to recreate the exact problem you may be seeing.

**Comment by mozey** [comment]
The problem with my middleware turned out to be an `if len(sys.argv) == 1:` that prints usage text and then calls `sys.exit(1)`. Hoverfly then responded with `{"headers":[],"body":"Hoverfly Error! Could not create synthetic response!. Got error: Synthesize failed, middleware error - exit status 1 \n"}`. I was incorrectly setting the middleware when starting up hoverfly, my middleware expected some args.

For debugging maybe it will be useful to return as body text whatever the middleware prints?

Anyway, modifying your binary_middleware.py example for python3 as per my previous post works. Thanks again for this feature.
