### ISSUE TITLE
Partially matching requests

### ISSUE THREAD

**Issue by benjvi** [SpectoLabs/hoverfly#204]
There are a couple of different use cases that we've been discussing for more configurable mapping of requests to responses:
- Matching on a set of user-specified headers ( issue #203 )
- Looser matching of individual request components, e.g. parameterised URL paths, comparison of json/xml fields in request body

Currently Hoverfly matches all incoming requests to responses by lookup in a key-value store based on a hash of the scheme, method, host, path, query and body (but not on headers). 

The proposed change will allow users to modify which request fields they want to match with on a per-request basis, creating what are effectively *request templates*. If Hoverfly doesn't find an exact match for the request in the key-value store, then it would iterate through the set of request templates associated with the current simulation, looking for a match. 

We think that this will give the maximum flexibility in how matching will work. For the first pass we are assuming that:
 1. The number of request templates will be relatively small compared to the number of requests recorded / requests made
 2. Since the number of request templates is small, its not going to be too much work for people to create them by directly modifying json ( although we also plan to look at how these can be captured directly )

Woudl be interested to hear any feedback or related use cases that people might have

**Comment by mogronalol** [comment]
Potentially there wouldn't be too much of a performance hit, if the total amount of request templates remains small.

**Comment by nicholasjackson** [comment]
Would love this feature

**Comment by tjcunliffe** [comment]
Delivered in release [v0.8.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.8.0)

Described in the [documentation here](https://spectolabs.gitbooks.io/hoverfly/content/usage/matching_requests.html)
