### ISSUE TITLE
Different behavior in downloaded binary and self-compiled code

### ISSUE THREAD

**Issue by awaise267** [SpectoLabs/hoverfly#207]
Hi Team,

The pre-compiled binary (downloaded from the links in the documentation) fails silently. Below is all that I can see when my application tries to connect to the box api (https://api.box.com).

`2016/06/29 11:35:09 [029] INFO: Running 2 CONNECT handlers
2016/06/29 11:35:09 [030] INFO: Running 2 CONNECT handlers
2016/06/29 11:35:09 [031] INFO: Running 2 CONNECT handlers
2016/06/29 11:35:09 [032] INFO: Running 2 CONNECT handlers
2016/06/29 11:35:09 [033] INFO: Running 2 CONNECT handlers
2016/06/29 11:35:09 [034] INFO: Running 2 CONNECT handlers` 

Interestingly, I am able to get hoverfly to work **partially** using a self-compiled binary which is strange as I haven't made any code changes. The only change I have made is to the jwt-go package import. jwt-go was updated to v3.0.0 a few days ago. This was a breaking update and caused build errors while trying to compile the hoverfly source code as-is. I was able to get it to compile by using the gopkg.in redirect to the old (v2) version of jwt-go.

Using my self-compiled code, I get the message "response from external service got successfuly!" along with a lot of other info and debug messages. However, now I am unable to fully export the service-data captured. A call to http://localhost:8888/api/records gives me the below error:

`	PANIC: interface conversion: *negroni.responseWriter is not negroni.ResponseWriter: missing method Before
goroutine 300 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0xa6ab28, 0xc8205e9a00, 0xc8201aa810)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/recovery.go:39 +0x231
panic(0x4e1f80, 0xc82035e500)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc8201a2420, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0, 0xc820442140)
	/Users/awaise/go_code/HoverflyTest/src/github.com/meatballhat/negroni-logrus/middleware.go:138 +0x6dd
github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65170, 0xc8201a2420, 0xc820193d20, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0xd8
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0x63
github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc8201aa840, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0, 0xc820442060)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/static.go:53 +0x323
github.com/codegangsta/negroni.middleware.ServeHTTP(0xa65118, 0xc8201aa840, 0xc820193d00, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0xd8
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0x63
github.com/codegangsta/negroni.(*Logger).ServeHTTP(0xc82002c258, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0, 0xc820442000)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/logger.go:25 +0x241
github.com/codegangsta/negroni.middleware.ServeHTTP(0xa650f0, 0xc82002c258, 0xc820193ce0, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0xd8
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0x63
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc8201aa810, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0, 0xc8200d5fe0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/recovery.go:54 +0x78
github.com/codegangsta/negroni.middleware.ServeHTTP(0xa650c8, 0xc8201aa810, 0xc820193cc0, 0xa6ab28, 0xc8205e9a00, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:33 +0xd8
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc8201aa8a0, 0xa65350, 0xc8200640d0, 0xc8204089a0)
	/Users/awaise/go_code/HoverflyTest/src/github.com/codegangsta/negroni/negroni.go:73 +0xbb
net/http.serverHandler.ServeHTTP(0xc82017d000, 0xa65350, 0xc8200640d0, 0xc8204089a0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820336500)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e`

I am an absolute beginner in Go (planning to use the binary out of the box along with a JavaScript/Python middleware). Please suggest a workaround if possible.

Thanks!

**Comment by benjih** [comment]
Hey @awaise267.

Regarding the first issue you raised about the pre-built binary that silently fails, the logs you've included look like the logs from your application. Does Hoverfly log anything before you see it fail?

When you compiled Hoverfly yourself and used the v2 jwt-go package, did the partial errors occur there as well? What did you do to build Hoverfly?

**Comment by awaise267** [comment]
Hey @benjih

I forgot to mention, the binary works fine when capturing http requests. I faced the first issue while trying to capture the **https** requests sent from my application to the Box API. The logs are from my terminal window running Hoverfly with the verbose flag `-v`. My application gives me an exception: `Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 502 Bad Gateway"`. But the proxy itself does not print any errors to the terminal console. Just the message `INFO: Running 2 CONNECT handlers`

The errors mentioned in the second issue occur when I try to view the service-data after successfully capturing the requests using the code I have compiled. They also occur when I try to open the Admin UI in my browser (I believe the Admin UI makes a call to the same API here - http://localhost:8888/api/records)

To build Hoverfly, I have followed the steps mentioned in the [doc](https://spectolabs.gitbooks.io/hoverfly/content/getting_started/installation_and_setup.html):

```
mkdir -p "$GOPATH/src/github.com/SpectoLabs/"
git clone https://github.com/SpectoLabs/hoverfly.git "$GOPATH/src/github.com/SpectoLabs/hoverfly"
cd "$GOPATH/src/github.com/SpectoLabs/hoverfly"
go get
```
Gives me some errors here
```
# github.com/SpectoLabs/hoverfly/authentication
authentication/auth_service.go:45: undefined: jwt.ParseFromRequest
authentication/jwt_backend.go:68: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
authentication/jwt_backend.go:69: invalid operation: token.Claims["iat"] (type jwt.Claims does not support indexing)
authentication/jwt_backend.go:70: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
authentication/jwt_backend.go:71: invalid operation: token.Claims["sub"] (type jwt.Claims does not support indexing)
authentication/middlewares.go:31: undefined: jwt.ParseFromRequest
```

I did a grep for `github.com/dgrijalva/jwt-go` and replaced all occurrences with `gopkg.in/dgrijalva/jwt-go.v2`

`go get` works without errors now. I completed the remaining steps as per the doc.

```
go get
cd cmd/hoverfly
go build
```

**Comment by benjvi** [comment]
Hi @awaise267 

I've been looking at this but having some trouble reproducing. Is there any more info you could share about the requests you're making - e.g. is the API using authentication headers/sessions/client certs?

It would also help if you can get the dependencies with glide (`brew install glide && glide up`) and then share the glide.lock file so we can check we have the same dependency versions

**Comment by awaise267** [comment]
Using glide according to the instructions in the updated doc seems to have resolved the issue in the self compiled code. Probably had something to do with the dependency versions. The binary still didn't work for me but I'm happy to use the self compiled version.

Thank you guys!
