### ISSUE TITLE
Following installation getting : {error:Not Found}

### ISSUE THREAD

**Issue by supasympa** [SpectoLabs/hoverfly#213]
Following installation (Mac OSX / zsh) I get an error:

`/usr/local/bin/hoverctl: line 1: {error:Not Found}: command not found`

Snippet from terminal:

```
...

Installation complete. To get started:
1. Run 'hoverctl pull benjvi/hello-world:latest'
2. Set your http_proxy environment variable: 'export http_proxy=http://localhost:8500/'
3. Run 'hoverctl start'
3. Run 'hoverctl import benjvi/hello-world:latest'
4. Run 'curl -L http://lab.specto.io/static/hello-world.html', or open in the browser on linux

...

$ hoverctl pull benjvi/hello-world:latest
/usr/local/bin/hoverctl: line 1: {error:Not Found}: command not found
$ hoverctl
/usr/local/bin/hoverctl: line 1: {error:Not Found}: command not found
$ hoverctl start
/usr/local/bin/hoverctl: line 1: {error:Not Found}: command not found
```

**Comment by benjih** [comment]
Hey @supasympa,

We're experiencing the same issue as you. We are currently investigating this issue right now. I will reply when I have more information.

Thanks for letting us know.

**Comment by rusenask** [comment]
wrong compile architecture?

**Comment by benjih** [comment]
For some reason, Github wasn't serving the binaries properly. A lot of the binaries lead to error pages.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/47131865/0abdff2e-4843-11e6-91d0-51e0b20484a2.0_OSX_amd64
</Key>
<RequestId>622E71735FE3837F</RequestId>
<HostId>
oH5Bf6QiUYhChuqtAwrjNC7GmU7E4Bc1m5qo/ykYLU2tUGnKW7U/OR/YUhKm+knU7L2jWvaSSyA=
</HostId>
</Error>
```

On top of this, the installer script might not have been using the correct URL for retrieving the binaries. We are in the process of rebuilding and reuploading the binaries. Once this is done, I will review the installer script and ensure its all working.

**Comment by benjih** [comment]
The binaries are back up on the releases page. I am now looking at the installer script.

**Comment by benjih** [comment]
The script should be fixed now. It is working for us. 

@supasympa, if you could run the command again and let us know if the error has been resolved.

```
curl -o install.sh https://storage.googleapis.com/specto-binaries/install.sh && bash install.sh
```

Again, thanks for letting us know about this and hope this

**Comment by supasympa** [comment]
Looking good! Thanks for the headsup.
