### ISSUE TITLE
Issues with POST requests

### ISSUE THREAD

**Issue by alex-glv** [SpectoLabs/hoverfly#247]
I am trying hoverfly in combination with Dredd + OpenAPI spec.

I am running tests against hoverfly in capture mode.

My GET requests get through fine, however, for POST requests hoverfly returns 301s and Dredd won't follow through.
Moreover, the location header is set to /endpoint, without a host prefix.

Example:
```
request:
method: POST
uri: /addresses
headers:
    User-Agent: Dredd/1.5.0 (Linux 4.4.16-moby; x64)
    Content-Type: application/json
    Content-Length: 95

body:
{
  "address": {
    "street": "teststreet",
    "number": "15",
    "country": "The Netherlands",
    "city": "Den Haag"
  }
}


expected:
headers:

body:

statusCode: 200
bodySchema: {"title":"Post status response","type":"object","properties":{"status":{"type":"boolean"}},"required":["status"]}


actual:
statusCode: 301
headers:
    content-length: 0
    content-type: text/plain; charset=utf-8
    date: Tue, 23 Aug 2016 09:59:18 GMT
    hoverfly: Was-Here
    location: /addresses
    connection: close

body:
```

What's the policy for POST requests, are they somehow special?

**Comment by benjih** [comment]
Hey @alex-glv,

There are no special rules around handling POST requests. Hoverfly treats every request agnostically. I will have a look around what could potentially be going on within Hoverfly.

**Comment by alex-glv** [comment]
@benjih Thanks, that's what I suspected but wanted to verify. If hoverfly sent 301s then it wouldn't be able to capture request / response to begin with.

**Comment by benjih** [comment]
Do you have any logs from Hoverfly that might help diagnose what is going on?

**Comment by alex-glv** [comment]
```{"destination":"user-dev:8084","level":"info","method":"POST","middleware":"","mode":"capture","msg":"request and response captured","path":"//register","rawQuery":"","time":"2016-08-23T10:46:38Z"}
{"destination":"user-dev:8084","level":"info","method":"GET","middleware":"","mode":"capture","msg":"request and response captured","path":"//customers","rawQuery":"","time":"2016-08-23T10:46:38Z"}
{"destination":"user-dev:8084","level":"info","method":"GET","middleware":"","mode":"capture","msg":"request and response captured","path":"//customers/57a98d98e4b00679b4a830af","rawQuery":"","time":"2016-08-23T10:46:38Z"}
```

This is an example. They look alright. The issue was the actual service throwing 301 because the endpoint was incorrect, prefixed with "//"

Fixing this resolved the issue. Thanks for your time! @benjih
