### ISSUE TITLE
Delays does not follow convention set by RequestMatchers

### ISSUE THREAD

**Issue by agnibrata** [SpectoLabs/hoverfly#251]
e.g:

Actual endpoint - http://REALHOST:REALPORT/user/data/{userid}

We have captured the req by setting  the proxy. (localhost:8500)

Then we start the server as ./hoverfly -webserver

Set the response delay as below:

```
 curl -H "Content-Type application/json" -X PUT -d '{"data":[{"urlPattern":"localhost\\:8500","delay":1000}]}' http://${HOVERFLY_HOST}:8888/api/delays
```

Now when i ran the req `http://localhost:8500/user/data/{userid}` the response delay is not working.

**Comment by benjih** [comment]
Hey @agnibrata,

Thank you for raising this. Using your example and a sample data set I had, I was able to recreate the issue. Response delays work slightly differently depending on how you run Hoverfly.

In proxy mode, a delay will match against a string combination of the host and the path. In web server mode, it is just the path.

To get delays working with Hoverfly running as a web server, you can only match on the path, ignoring the destination. This is something that isn't well documented.

To match any request and add a delay:
```
{
	"data": [{
		"urlPattern": ".",
		"delay": 20000
	}]
}
```

To match a specific endpoint:
```
{
	"data": [{
		"urlPattern": "/api/endpoint",
		"delay": 20000
	}]
}
```

My thinking is that regardless if Hoverfly is running as a proxy or a web server, matching should still be available on both host and path. The way I am thinking of doing this is making sure the host is always set.

In web server mode, I am unsure what the host should be. Should the host be "localhost" or the name of the original host? 

Using localhost means that any delays written for Hoverfly will only work when running as a web server, unless the original request response was recorded as being from localhost. Using the original host name means that you could reuse the delay for both proxy and web server, but then in web server mode, you probably wouldn't use that host to access Hoverfly, which might cause confusion.

This issue has brought attention to the fact that the web server mode of Hoverfly does not operate exactly the same as proxy mode and that there are still a lot of unknowns around how it should behave. We would love to hear your thoughts on this.

**Comment by JohnFDavenport** [comment]
I understand this is a more general issue of consistency between webserver and proxy mode, so I've changed the title. Please correct if I have misunderstood @benjih

**Comment by tommysitu** [comment]
Splitting the `urlPattern` into `hostPattern` and `pathPattern` might be a simple way to fix this problem. In webserver mode, only `pathPattern` is checked, and the same simulation will work for both proxy or webserver modes. 

Another solution is to move the delay settings to the response, and allow granular control of delays using the request matcher.

Either way will be a breaking change and requires a schema upgrade.

**Comment by JohnFDavenport** [comment]
We can perhaps avoid breaking the schema by announcing we shall deprecate `urlPattern`. Let's introduce a distinct replacement (maybe 'fixedDelay' rather than 'delay') and give users a few months minimum to move over to the replacement. Unfortunately I don't think we can justify delaying the 1.0.0 release to do it.

**Comment by JohnFDavenport** [comment]
Let's do this with the per-response delays #807

**Comment by tommysitu** [comment]
More info about using delay urlPattern for webserver and proxy mode has been added to the doc: https://docs.hoverfly.io/en/latest/pages/tutorials/basic/delays/multiplelocations/multiplelocations.html
