### ISSUE TITLE
hoverfly as webserver doesn't provide the right content-type

### ISSUE THREAD

**Issue by agnibrata** [SpectoLabs/hoverfly#252]
My api response content-type is expected as `application/json`; where as hoverfly gives back as `text/plain`
Hoverfly response - 
```
HTTP/1.1 200 OK
Req: /user/aaa111
Resp: 124
Date: Wed, 24 Aug 2016 04:42:21 GMT
Content-Length: 124
Content-Type: text/plain; charset=utf-8

{"userId":"727a87f5-03cb-4f69-9778-6585d37461c5","eid":"aaa111","name":"Test User","email":"test.user@aaa.com","team":"Foo"}
```
Actual response -
```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 124
ETag: W/"7c-vKwqaAK/uwMcGkLv6JIknA"
Date: Wed, 24 Aug 2016 18:00:26 GMT
Connection: keep-alive

{"userId":"727a87f5-03cb-4f69-9778-6585d37461c5","eid":"aaa111","name":"Test User","email":"test.user@aaa.com","team":"Foo"}
```
And also observer that in the ui - http://localhost:8888; under the count section not count increases if i use as webserver mode.

**Comment by benjih** [comment]
Hey @agnibrata,

We recently discovered the same issue. In webserver mode, the correct headers were not being added to the response before being sent. This is what is creating this issue for you regarding content-type.

We have fixed this issue and merged into master (#243). We anticipate this bug being released in the upcoming release of Hoverfly, v0.8.1.

**Comment by benjih** [comment]
Hello again @agnibrata,

We have just released [v0.8.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.8.1) of Hoverfly. This new version contains the fix mentioned above to webserver mode.

**Comment by jmart1** [comment]
I still have this problem.

**Comment by JohnFDavenport** [comment]
@jmart1  As this issue was fixed over a year ago can I ask you to raise a new issue please.
