### ISSUE TITLE
readthedocs_query outdated

### ISSUE THREAD

**Issue by luandrea** [SpectoLabs/hoverfly#262]
Hi,
I tried the readthedocs_query example, but I think that it is outdated.

In the starting URL "format=json" is missing, and then  in the json list also "subdomain" is missing. Could you verify and fix?

**Comment by JohnFDavenport** [comment]
Thanks @luandrea for pointing this out. The readthedocs example was written for a very early version of hoverfly.  Can you clarify where you are looking?

**Comment by luandrea** [comment]
The error was in this example: SpectoLabs-hoverfly-e9578bf/core/examples/clients/readthedocs_query/test.py
I was trying some simple example to understand how Hoverfly works.

**Comment by benjih** [comment]
Hey @luandrea,

I tested this and you are right. It looks like there were some changes to their v1 API, which included the removal of the `subdomain` field.

I have modified the test.py example now to use the `resource_uri` field instead. This was merged in in #266.

I hope this helps you.
