### ISSUE TITLE
Review diagnostics in case of panic!

### ISSUE THREAD

**Issue by JohnFDavenport** [SpectoLabs/hoverfly#275]
Providing a generic solution for all potential failures would probably be difficult but issue #255   suggests there are circumstances where Hoverfly has sufficient context and we could dump context (URI, REST headers, request, template, response, middleware, etc) perhaps to the log or to a separate file.

**Comment by JohnFDavenport** [comment]
As the data is likely to be sensitive we should review what security we provide, such as encrypting the data.

**Comment by benjih** [comment]
With the new version of Hoverfly, there will be easier ways to retrieve all the simulation data and the Hoverfly config with both /api/v2/simulation and /api/v2/hoverfly.

But I do like the idea of having a file that we could upload with issues.
