### ISSUE TITLE
Hoverctl to Support -cert and -key

### ISSUE THREAD

**Issue by dogarfin** [SpectoLabs/hoverfly#284]
Is there a way to run hoverctl with the -cert and -key arguments in that same way I am able to run the hoverfly binary with these arguments?

Also, thank you for this great product.

**Comment by benjih** [comment]
Hey @dogarfin 

Thanks for the feedback, currently you cannot do that with hoverctl but this is definitely something it should do.

I imagine the best way it would work is by having options that can be used for the start command.

`hoverctl start --cert <string> --key <string>`

**Comment by benjih** [comment]
Hello again @dogarfin,

We have added support for providing certificates and keys to hoverctl when starting an instance of Hoverfly. This can be founded in the latest release of Hoverfly, [v0.9.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.9.1).

Thanks for the suggestion and I hope this feature helps.

Any other issues with Hoverfly or hoverctl, please let us know.
