### ISSUE TITLE
hoverctl loads hoverfly from PATH, should look in current directory first

### ISSUE THREAD

**Issue by shyal** [SpectoLabs/hoverfly#298]
```hoverctl``` and ```hoverfly``` seem to often get bundled together, however ```hoverctl``` seems to look for the ```hoverfly``` binary in the path.

This can lead to strange situations, where ```hoverctl``` does not find the ```hoverfly``` binary, or loads the wrong ```hoverfly``` binary.

Maybe ```hoverctl``` should first try to load ```hoverfly``` from the directory it is in, before loading it from the path.

```go
dir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
hfbin := filepath.Join(dir, "hoverfly")
if _, err := os.Stat(hfbin); err == nil {
  // use hfbin
} else {
  // load from path as before
}
```

**Comment by benjih** [comment]
Hey @shyal,

Thanks for the feedback. At the time of creating hoverctl, this never occurred to me, but having saw this issue made it clear that this is something that hoverctl should do. I have implemented this change and it can be found in the latest release of Hoverfly, [v0.9.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.9.1).

**Comment by shyal** [comment]
Thank you.
