### ISSUE TITLE
Hoverctl bash auto-completion

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#325]
Would be nice to have auto-completion when using the command line tool.

**Comment by joostvanwollingen** [comment]
Has any work been done on this issue? I think the implementation could be relatively easy, given hoverctl already uses Cobra. 

I've created PR #656 for this issue, but I have some questions and it probably needs some more work:

- Should the project distribute the completion file separately from the hoverctl or create a command in hoverctl that can install the completion?
- Perhaps the completion file should be created in ~/.hoverfly and there should be symbolic link in the bash_completion.d folder?
- The way I use runtime.GOOS in "getSuggestedPathToCompletionFile"-function to detect a probable bash_completion.d folder is probably too naive.

**Comment by tommysitu** [comment]
The work has not been done yet, so thank you very much for your effort. Regarding your questions: 
- What you have done is great, using `hoverctl completion` makes sense
- I think the completion file should be a symlink which is common for many autocompletion profiles. 
- It works on Mac for us for the time being, we can worry about it later.

If you can update your PR https://github.com/SpectoLabs/hoverfly/pull/656 with the symlink change, we are happy to merge it in.

**Comment by joostvanwollingen** [comment]
Updated the PR. Please review.

**Comment by tommysitu** [comment]
It looks good. Thank you!

**Comment by tommysitu** [comment]
@joostvanwollingen this feature is now released as v0.14.2. I personally think that this is a really useful one!
