### ISSUE TITLE
Recording request headers should be optional

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#329]
@mogronalol has raised the concern of potentially exposing sensitive information from recording request headers. 

Perhaps the request headers recording should be disabled by default, and options for a user to record specific headers would be provided.

**Comment by benjih** [comment]
Hey @tommysitu,

You'll be happy to hear that v0.11.0 of Hoverfly (the next release) will not capture headers by default. Instead, you will have to tell Hoverfly what headers you would want to capture.
```
hoverctl capture --headers "User-Agent,Content-Type"
```

If you want to capture all headers, there is even a flag for that too.
```
hoverctl capture --all-headers
```

I will close this ticket once the release has been made.

**Comment by tommysitu** [comment]
Excellent!

**Comment by benjih** [comment]
[v0.11.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.0) has now been released.
