### ISSUE TITLE
Simulate and capture mode simultaneously

### ISSUE THREAD

**Issue by proofyman** [SpectoLabs/hoverfly#341]
It's quite common scenario to populate/modify records collection in big buggy applications. Right now I have to write my own hoverctl to start 2 hoverfly instances.

**Comment by benjih** [comment]
You can start multiple instances using Hoverctl, though it might not be clear. To start multiple instances of Hoverfly, you need to make sure you have no port collisions.

`hoverctl start --admin-port 1234 --proxy-port 5678
hoverctl start --admin-port 2345 --proxy-port 6789`
