### ISSUE TITLE
Add status command to hoverctl

### ISSUE THREAD

**Issue by johnharris85** [SpectoLabs/hoverfly#351]
Not a huge deal, but would be nice to have a hoverctl status that just gives current middleware if in use, whether hoverctl is running or not, what mode it's in, etc...?

If this fits in the roadmap I'm happy to implement and submit a PR?

**Comment by benjih** [comment]
This makes sense and is a fairly minor change I believe. Feel free to submit a PR, I'd be happy to look over it. If not, we are more than happy to implement this.

**Comment by benjih** [comment]
This was added to Hoverfly in version [v0.14.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.14.1).
