### ISSUE TITLE
Hoverfly verifier

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#354]
I propose producing another binary alongside Hoverfly which can be used to verify that simulations have not become stale. 

The way it would work is by performing all the requests in a simulation and asserting the responses are still the same.

## High level example

(I've only included two request fields and one response field for simplicity)

| Method        | Path           | Response Body                |
| ------------- |:-------------:| -------------:| 
| GET      | /foo | {"hello" : "world"} |
| PUT      | /bar      | {"hello" : "world"}  |
| POST | /foo      | {"hello" : "world"}  |

The verifier would iterate over each request matcher and build a request based on it.  It would then assert the response is the same as before:

`assert GET /foo == {"hello" : "world"}` PASS
`assert PUT /bar == {"hello" : "world"}` FAIL
`assert POST /foo == {"hello" : "world"}` PASS

In this case we no longer receive the simulated response for the second request, so we would receive a test failure. 

## Reporting

The results of running this binary would be a JSON or XML file, which also has a pretty formatted HTML equivalent which is human readable.

## Schema verification

It's quite common for data which is returned by an external API (such as timestamps) to change even if the request does not. In the case of `JSON`:

```json

{
  "foo" : "bar",
  "bacon" : "4"
}

```

Is the same API contract as:

```json

{
  "foo" : "bar",
  "bacon" : "5"
}

```

It just happens that the second time we made the request, somebody had added more bacon. This does not mean that our simulation is invalid, as it is still the same contract but with different data.  To be invalid we would have to do something like change the name of the field:

```json

{
  "fooRenamedToBreakingField" : "bar",
  "bacon" : "5"
}

```

Having this type of schema comparison instead of a straight up comparison of the raw data is going to be more useful, but I think for the first iteration of the application we can leave it out as it's quite complicated and requires a wider discussion.

**Comment by JohnFDavenport** [comment]
See #699

**Comment by JohnFDavenport** [comment]
We have [diff mode](https://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/modes/diff.html) which provides the underlying functionality. The assertion part of this could be in a wrapper such as Hoverfly-java or a separate application.
