### ISSUE TITLE
Ability to secure proxy with authentication headers

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#358]
Right now the authentication mechanism can only be used to secure Hoverflies API endpoints. We would want this to apply to standard proxy usage aswell. A good summary of the flow is here on this stackoverflow:

http://stackoverflow.com/questions/10023636/http-spec-proxy-authorization-and-authorization-headers

Basically we would return `407 Proxy Authentication Required` if authentication is turned on, unless we provide `Proxy-Authorization` with `base64(username:password)`. The user should just be what we use currently for API authentication.

It doesn't currently make sense to give restricted access to the simulation data via the API, but then give unrestricted access to it via the proxy - it should be a binary decision between being entirely restricted / not restricted.

This also opens it up to being run somewhere publicly.

**Comment by benjih** [comment]
Hey @mogronalol,

This feature has been added to master and will be released as part of Hoverfly v0.10.2.

**Comment by benjih** [comment]
Hey @mogronalol , we've release v0.10.2 which includes this feature.
