### ISSUE TITLE
Helm chart for Hoverfly

### ISSUE THREAD

**Issue by bspaans** [SpectoLabs/hoverfly#366]
Hi guys, big fan here. I think it would be cool if we'd live in a world where Hoverfly had a sanctioned Helm chart (https://github.com/kubernetes/helm). Regardless, keep doing what you doing!

**Comment by benjih** [comment]
Hey,

Thanks for the praise. It's much appreciated.

I will look into Helm and see if I can produce a chart for Hoverfly.

**Comment by tommysitu** [comment]
This is the PR for adding an incubator chart https://github.com/helm/charts/pull/11365

**Comment by tommysitu** [comment]
Hoverfly Helm chart is now available in the official incubator: https://github.com/helm/charts/tree/master/incubator/hoverfly

**Comment by tommysitu** [comment]
Thank you for the suggestion @bspaans!

**Comment by svanellewee** [comment]
Hey everyone, what is the official helm repository for hoverfly now? I don't see any clear official repos for this. Can someone point me to the current home of the official maintained hoverfly helm repo ?

**Comment by tommysitu** [comment]
@svanellewee we haven't got an official one since Helm migrated their repo, but you may get some inspiration to create yours here: https://github.com/helm/charts/tree/master/incubator/hoverfly
