### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by novathore** [SpectoLabs/hoverfly#370]
Hi!
On a new version of hoverfly ( v0.10.0 ), i caught an critical error, but hoverfly ( v0.9.0 ) working fine for my tool.
I can't find detailed changelog, where i can see breaking changes.
So, i can't find page where i can download previous version of hoverfly. I can download previous version by URL, but it is not obvious.
Thanks!

**Comment by benjih** [comment]
Hey @novathore, all of our changes and links to old releases is on our [release page](https://github.com/SpectoLabs/hoverfly/releases).

What's the critical error?

**Comment by JohnFDavenport** [comment]
Please reopen the ticket if there is more information.
