### ISSUE TITLE
Can't use http_proxy or https_proxy directly with hoverfly

### ISSUE THREAD

**Issue by Bruno-DaSilva** [SpectoLabs/hoverfly#373]
Currently we are running into a situation where we are blocked with a firewall to the service we want to mock, but we are able to access it via proxy server. Our normal setup to access this server is: 

app_server ------> proxy_server ------> service_to_mock

Now, in order to mock this, we require this setup:

app server ------> hoverfly ------> proxy_server ------> service_to_mock

However, hoverfly does not automatically configure this additional proxy server when http_proxy or https_proxy environment variables are set. Would it be possible to add in this functionality?

**Comment by Bruno-DaSilva** [comment]
I've experimented with a small change on my end, and it seems to work perfectly. I will open up a PR, please let me know what you think of this change.

**Comment by benjih** [comment]
Hey @Bruno-DaSilva, thanks for raising the issue and submitting a pull request. I will look into your pull request today.

**Comment by Bruno-DaSilva** [comment]
PR merged, I consider this issue closed. Thanks @benjih.
