### ISSUE TITLE
capture mode should have an extra optional param: --donotcapture

### ISSUE THREAD

**Issue by paul-hammant** [SpectoLabs/hoverfly#375]
I'd like to be able to do `hoverctl mode capture --donotcapture todobackend.com`

So that I don't have to tinker with excludes in a browser, when it's only APIs I want to capture ..

![2017-02-04_2028](https://cloud.githubusercontent.com/assets/82182/22622974/b0d95e08-eb18-11e6-9816-0a19c33dc9ff.png)

.. and I'm not wanting to capture JavaScript, HTML, CSS, images etc.

**Comment by mogronalol** [comment]
This is a good idea. I don't think Hoverfly allows this. You can tell it what _to_ capture but not what _not_ to capture. So we have this:

```
$ hoverctl destination to-capture.com
```

What about something like:

```bash
$ hoverctl destination 
$ Hoverfly currently applies to all URL's
$ hoverctl destination include foo.com 
$ hoverctl destination exclude foo.com/some-subpath 
$ hoverctl include bar.com 
$ hoverctl destination 
$ Hoverfly applies to:
$ foo.com and bar.com
$ Hoverfly does not apply to:
$ foo.com/some-subpath
```

I'm not sure about making it a flag, purely because I see it as a global setting for Hoverfly, regardless of the mode.

**Comment by SergiiNozhka** [comment]
Also it would be great if we can specify headers/cookies as parameters for capture mode, to filter out extra requests.

**Comment by tommysitu** [comment]
Hoverfly has a `destination` flag for filtering requests by regex already which should be flexible enough for many use cases. For example, you can create a negative lookahead regex to exclude certain URL patterns: 

`hoverctl destination [^http://echo.jsontest.com].*`

`curl --proxy localhost:8500 echo.jsontest.com` will not be captured, but

`curl --proxy localhost:8500 echo.jsontest.com/api/v1` will be.

We will improve the documentation to make it clear that `destination` flag takes any golang regex.

@SergiiNozhka please open a new issue if you have any use case for the suggestion.

**Comment by johnraz** [comment]
@tommysitu I still think this is really difficult to exclude a list of domain you don't want to capture/simulate.

I'm currently considering hoverfly and this is really a strong blocker, other than that the project is great and checks all the checkboxes.

Could you give a clear example of what the regex would look like to eg exclude:
`localhost, localstack.myservice.local, anydomain.foo` ?

**Comment by tommysitu** [comment]
@johnraz you're right, golang regex has some limitations in excluding a string. I guess the best way is to provide a flag for passing a list of hostnames which you don't want to capture, like `-non-proxy-hosts localhost, localstack.myservice.local, anydomain.foo` Just had a look at the codebase, it might be possible to do that. Contribution is welcomed!
