### ISSUE TITLE
Synthesize mode - documentation clarification as to API and heterogeneous nature of plugin

### ISSUE THREAD

**Issue by paul-hammant** [SpectoLabs/hoverfly#376]
> Hoverfly to operate in Synthesize mode, a middleware executable must be specified

Should you add on to the readthedocs advice page ..

1. The executable takes CLI args and uses std-out as the communication channel back to hoverfly.

2. How about a bash example, too (inline in page).

**Comment by mogronalol** [comment]
Are you referring to [this page](http://hoverfly.io/en/latest/pages/keyconcepts/modes/synthesize.html)?

It does link through to the [middleware](http://hoverfly.io/en/latest/pages/keyconcepts/middleware.html#middleware) page, but I think this is a bit too much as well. 

People probably just want a quick example of something to run locally in bash, with a quick explanation on how it's a binary operating on standard out and in. Shouldn't be too hard to add.

**Comment by JohnFDavenport** [comment]
Closing as we have updated the cocumentation
