### ISSUE TITLE
Introduce spy or stub options to Hoverfly

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#389]
This comes from this issue in [Hoverfly-Java](https://github.com/SpectoLabs/hoverfly-java/issues/47).

With Mockito in Java, you have the ability to `Spy` on real objects. This means instead of having a pure mock, you have the real object. In this case, individual methods are overridden to become stubs, leaving the the non-stubbed methods to work as normal.

This seems like something Hoverfly could do, but for http. So something like:

`hoverctl simulate --stub` // The same as how it currently behaves
`hoverctl simulate` // The same as above because stub is default
`hoverctl simulate --spy` // When there isn't a match, call the real service

This is a valid use case, in some situations. The one given was running the external dependency locally or as part of your build, and only wanting to change the behaviour of specific endpoints.

**Comment by tommysitu** [comment]
Spy mode is introduced in this PR: https://github.com/SpectoLabs/hoverfly/pull/680

**Comment by tommysitu** [comment]
Thank you for your contribution @3sunnysideup, Hoverfly v0.15.0 has a new `spy` mode.
