### ISSUE TITLE
please add a /time to hoverfly for testing

### ISSUE THREAD

**Issue by shyal** [SpectoLabs/hoverfly#413]
A really easy way to test hoverfly language bindings is to do a GET on /health, but the information is not enough to test caching and simulation. Could we have a /time path which returns:

``` json
{ "date": "2017-02-17", "epoch": 1487333774959, "time": "13:16:14" }
```

Thanks.

**Comment by benjih** [comment]
Hey @shyal,

Thanks for all the work you have put into [hoverpy](https://github.com/SpectoLabs/hoverpy). It is very much appreciated.

I will look into this for the next release.

**Comment by shyal** [comment]
Hi @benjih. My pleasure. Hoverpy is still using some of v1 endpoints. Need to migrate them soon. Thanks for your help and support.

**Comment by JohnFDavenport** [comment]
Latency is now recorded in the journal, both in capture and simulate modes, and the journal also gives a lot of health info.
