### ISSUE TITLE
Missing information on overriding Hoverfly's default SSL certificate

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#421]
The current doc has a tutorial about HTTPS simulation: 
http://docs.hoverfly.io/en/latest/pages/tutorials/https/https.html

It would be nice to have instruction on how to provide self-signed certificate to hoverfly. 

I'd suggest including these to the HTTPS tutorial
1. Using `hoverfly -generate-ca-cert` to generate 'cert.pem' and 'key.pem' files in the current folder and start up hoverfly with these new SSL cert and key.
2. Provide your own SSL cert and key by using `hoverfly -cert </cert/file/path> -key </key/file/path>
3. Alternatively use `hoverctl --certificate </cert/file/path> --key </key/file/path>`
4. Should mention that both key and cert is required to override the default SSL credentials
5. Should also mention that only unencrypted key is supported
6. Should mention that the key and cert files should be PEM encoded.

**Comment by tjcunliffe** [comment]
This is on a branch [v0.10.2](https://github.com/SpectoLabs/hoverfly/tree/v0.10.2).
