### ISSUE TITLE
Option to change Transfer-Encoding: chunked to Transfer-Encoding: identity

### ISSUE THREAD

**Issue by michalc** [SpectoLabs/hoverfly#422]
I'm trying to use hoverfly as a proxy to an API that does not support Transfer-Encoding: chunked. The reason for this is that it uses the Content-Length header to verify a signature in the Authorization header. Since chunked doesn't have this header, the API failes authentication.

Is there a way to make sure hoverfly makes its external requests using the identity transfer encoding?

**Comment by benjih** [comment]
Hey @michalc,


Hoverfly does not make any changes to the headers of requests being proxied to their intended destination. The only header that is added is on the response, which is `["Hoverfly": "Was-Here"]`.

Where is this Transfer-Encoding header coming from? This isn't something that Hoverfly adds. It might be that maybe your HTTP client is using this header by default.

You could write a piece of middleware that modifies outgoing request and changes the value of the header, this would be the best way to do it if you are expecting your Transfer-Encoding header to be changed while in transit.

**Comment by michalc** [comment]
> Where is this Transfer-Encoding header coming from?

Well, I thought it was hoverfly! I have now upgraded to v0.10.1 (from v0.10.0), and the issue doesn't seem to happen.

My bad... apologies.
