### ISSUE TITLE
Feature Request: Simulate Mode with option to use request middleware

### ISSUE THREAD

**Issue by tophercf** [SpectoLabs/hoverfly#426]
Had a few situations/use cases that I have been trying to work around, and would like to throw out a few ideas for new features.
- Allow simulate mode to use request modification from middleware
- Allow modify mode to ignore headers, similar to capture mode

**Comment by Apurva1995** [comment]
I am facing similar kind of issue, where i need to modify request using middleware in simulate mode. I have one filed in request payload that i need to ignore while matching. So this feature would be really helpful.

**Comment by tommysitu** [comment]
please refer to issue https://github.com/SpectoLabs/hoverfly/issues/690
