### ISSUE TITLE
Remote middleware requests are missing a Content-Type header

### ISSUE THREAD

**Issue by Bruno-DaSilva** [SpectoLabs/hoverfly#460]
Hi @benjih,

Looks like hoverfly isn't sending a Content-Type header along with requests. I'm using a Spring Boot app as my middleware, but that defaults no Content-Type to application/octet-stream (with no way to configure otherwise as far as I can tell).

It's a quick code fix to add this, could you review the PR I've opened, please?

**Comment by benjih** [comment]
Hey @Bruno-DaSilva, this has been merged. It will be released with v0.11.0 which is looking to be next week.

**Comment by benjih** [comment]
[v0.11.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.0) has now been released.
