### ISSUE TITLE
Preventing loss of data on shutdown

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#464]
When using the default data store for Hoverfly, everything is stored in memory. This is fast, but it means the user must remember to call `export` before stopping it, otherwise the data is lost. It would be good if Hoverfly provided an endpoint what states whether the data has been exported or not since it's last change. This means clients such as the CLI can decide to prompt on calling `stop` for the user to export their saved changes.

**Comment by JohnFDavenport** [comment]
You can persist data using the -db flag in Hoverfly. I have to admit I'd forgotten that is an option.
