### ISSUE TITLE
Ability to retrieve self sign certificate using Hoverctl

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#476]
It would be useful if you could retrieve the self signed certificate which Hoverfly is using via the CTL. For example, I want to add it to a trust store, and now need to find it in the source tree.

**Comment by JohnFDavenport** [comment]
You can retrieve the certificate as it says in the documentation with the [wget](https://hoverfly.readthedocs.io/en/latest/pages/tutorials/basic/https/https.html?highlight=wget) command so wonder if this is really necessary. Thoughts anyone?

**Comment by JohnFDavenport** [comment]
Ok, no more comments & the documentation deals with this so closing.
