### ISSUE TITLE
hoverctl flag to suppress echoing middleware source code

### ISSUE THREAD

**Issue by mozey** [SpectoLabs/hoverfly#478]
When scripting `hoverctl middleware` it would be nice if there was a flag to suppress echoing of the middleware source code. 

hoverctl does not write errors to stderr, for example "File not found". So `hoverctl middleware ... > /dev/null` will also mask error messages.

**Comment by mozey** [comment]
Alternatively maybe only echo middleware code if `-v` is set?

**Comment by benjih** [comment]
I think moving the the echoing into verbose logging would make more sense than what it does currently.

I will look into the fact that hoverctl does not print errors to stderr.

**Comment by benjih** [comment]
Hey @mozey,

I've updated hoverctl so that it only print the first five lines of a script unless verbose is set. I have also made sure errors are being written to stderr.

This will make it into the next release which will be within the next 7 days.

**Comment by benjih** [comment]
Hey @mozey,

This is request is now live in [v0.11.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.1) of Hoverfly.
