### ISSUE TITLE
Add HTTP compression to hoverfly responses

### ISSUE THREAD

**Issue by Bruno-DaSilva** [SpectoLabs/hoverfly#486]
In our tests, we're seeing upwards of 600 megabit per second across a few of load balanced Hoverflys during our performance tests. If the client sending requests to hoverfly sends a header with `Accept-Encoding: gzip`, say, it would be great if hoverfly had an option to compress the body in a response.
To clarify, this would mean that the request/response pairs would be plaintext (and served plaintext if `Accept-Encoding` was missing), but would be compressed if the client attaches that `Accept-Encoding` header.

**Comment by JohnFDavenport** [comment]
Hi, I'm not an expert but I've some experience of pushing SV solutions to their limits. I assume you are putting the Hoverfly instances across the network so is that why you'd like to use gzip? We found that compressing data meant that CPU became the bottleneck, although if you are spreading the load across enough CPUs that might not apply. Would it be possible to share some details of your configuration? What kind of load balancer are you using? Can you share what you are seeing at the CPU and NIC level?

**Comment by mogronalol** [comment]
@Bruno-DaSilva Wondering how you got on with this? Did you try implementing middleware to perform the compression?

**Comment by JohnFDavenport** [comment]
Closing as we previously worked out it's a bad idea
