### ISSUE TITLE
mistake about download link on the offical website

### ISSUE THREAD

**Issue by alex-whybother** [SpectoLabs/hoverfly#489]
A simple mistake about the download link on the offical website, the download link for Linux 64bit is linked to 
>https://github.com/SpectoLabs/hoverfly/releases/download/v0.11.0/hoverfly_bundle_linux_386.zip

and link for Linux 32bit is linked to 

>https://github.com/SpectoLabs/hoverfly/releases/download/v0.11.0/hoverfly_bundle_linux_amd64.zip

And the links for Windows have the same problem.
This is my first time to post a issue, pls correct me if i am doing anythig wrong.

**Comment by JohnFDavenport** [comment]
Thanks for pointing that out @alex-whybother . You are right. We might not have spotted that for weeks!

It appears that the links have been reversed where it is possible to do so.

**Comment by alex-whybother** [comment]
Glad that I can help

**Comment by tjcunliffe** [comment]
Fixed - thanks @alex-whybother!
