### ISSUE TITLE
Loose matching option for path matcher 

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#499]
A simulation which contains `"path": "/app/api/v1/"` is not matching a request to `/app/api/v1` or vise versa. 

It is permissible for URL with or without `/` to point to different content: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

But for Restful endpoints, it shouldn't make any difference.

Perhaps we could introduce a settings for strict/loose matching for path?

**Comment by benjih** [comment]
Maybe if there was a matcher like `containsMatch`, you could then loosely
match against both paths, leaving `exactMatch` for stricter matching on
path.

I'm keen to avoid adding additional config if there is an alternative that
makes sense.

**Comment by benjih** [comment]
Maybe if there was a matcher like `containsMatch`, you could then loosely
match against both paths, leaving `exactMatch` for stricter matching on
path.

I'm keen to avoid adding additional config if there is an alternative that
makes sense.`

**Comment by tommysitu** [comment]
The problem with `containsMatch` is that it will match everything starts with a root path, such as `/app/api/v1/foo`, `/app/api/v1/bar`, etc. 

While loose matching option is intended for ignoring things that might cause ambiguity in a request, in this case is the trailing slash in the path
