### ISSUE TITLE
Add verification to simulation mode

### ISSUE THREAD

**Issue by dumbird** [SpectoLabs/hoverfly#501]
We're trying to using a mock proxy to record requests sent to the real servers, and replaying the response in simulation mode for integration test. We have checked a few solutions, including Hoverfly, MockServer, WireServer, Flashback etc. Hoverfly wins over the simplicity to set up and use. However, we need a feature to verify that some requests are indeed made to a remote server in the simulation mode, similar to the verify() method provided by Mockito. It seems that Hoverfly currently doesn't have that. Mockserver does provide that, but we have issue to make it work in the man-in-the-middle mode for https traffic. It would be great if verification can be added to the simulation mode. Thanks.

**Comment by mogronalol** [comment]
@dumbird This is definitely high up on a roadmap, and is likely to be one of the next features we implement following following remote Hoverfly authentication. We will be aiming for Mockito style verification, where you will be able to run matchers against all the requests that have been made. It's will be relatively granular, allowing you to specify ordering, types of matching, counts etc. This will then feed into the Java binding (If you're experimenting with that)

**Comment by dumbird** [comment]
Great! I'm looking forward to trying it out. And yes, I'm using the Java binding. And talking about Java binding, it seems that the latest one available is still using schema v1?


Rui

________________________________

**Comment by tommysitu** [comment]
@dumbird, hoverfly-java is a little bit behind. It needs to upgrade to v2 schema and add matchers to the DSL. 
Feedback is very welcomed, and contribution is even better :)

**Comment by mogronalol** [comment]
Yes it is. It's the next job for Hoverfly Java though.

**Comment by tommysitu** [comment]
Hi @dumbird, verification is implemented in Hoverfly-Java already, therefore I am closing this issue.
