### ISSUE TITLE
API endpoint for killing Hoverfly

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#516]
Right now we are using PID's to kill a running Hoverfly process. It's going to be a lot less brittle if it can be done via an API endpoint, using the URL of the target Hoverfly stored within the config. We are also a lot less likely to run across PID related problems which change across platforms.

**Comment by mogronalol** [comment]
@johnharris85 I've assigned this to you if you were looking for some guidance. If you don't have the time the no worries at all and we will implement it ourselves. This should be the start of resolving your container issues as it will no longer need to check for PID's.

**Comment by johnharris85** [comment]
Sounds good, will take a look next week.
