### ISSUE TITLE
Extract parameters from a request and put in response

### ISSUE THREAD

**Issue by JohnFDavenport** [SpectoLabs/hoverfly#520]
Use case:

Having matched a templated requests, or used XPath or jsonpath matchers, take fields from XML encoded and JSON requests and allow them to be automatically substituted in a suitably encoded response.

**Comment by mogronalol** [comment]
For the first iteration, I am thinking we add a new flag to a matcher-to-response pair called `templating` which can be `true` or `false` to enable it. 

I've looked at various templating libraries, and this seems like the best as it uses moustache (https://mustache.github.io/):

- https://github.com/cbroglie/mustache

I don't particularly like the idea of using GoLang templating, as it's quite verbose + is not as universally known as moustache 

To begin with, the only accessible object will be the request. I'll outline what I think should be available shortly.

**Comment by mogronalol** [comment]
I actually need to double check this is the correct syntax for moustache, but I am thinking this (Bear with me I'll keep adding as I think of more):

example template | example value | description
--- | --- | ---
`{{ Request.QueryParam.<ParamName>[n] }}` | `valueOfParam` | singular parameter value
`{{ Request.QueryParam.<ParamName> }}` | `valueOfParam` | list of parameter values
`{{ Request.Scheme }}` | https | request scheme

**Comment by tommysitu** [comment]
How about path variable, eg. `/api/books/<bookId>`?

**Comment by mogronalol** [comment]
@tommysitu I've created a branch, and I'll keep adding to it. A little bit of a pain to write it all down on GitHub. We can evaluate once I have some examples pushed.

**Comment by brijeshps** [comment]
Any update on the issue, whether all the examples mentioned in the "Example Template" are implemented or still pending?

**Comment by mogronalol** [comment]
Hi @brijeshps This is already implemented in the current version of Hoverfly. This issue somehow got left behind. The documentation is here:

http://hoverfly.readthedocs.io/en/v0.13.0/pages/keyconcepts/templating/templating.html

I noticed there seems to be a bug with rendering the table, as it is somehow out of date. So you can view the raw RST to see the examples until we get this fixed:

https://raw.githubusercontent.com/SpectoLabs/hoverfly/v0.13.0/docs/pages/keyconcepts/templating/templating.rst

**Comment by tommysitu** [comment]
@mogronalol, I don't think the header and body templating is done.

**Comment by mogronalol** [comment]
Yes, to clarify body templating is unlikely to be implemented in the open source Hoverfly. Header templating may come in the future, but we can track this in a new issue as this one was more generalised as

> Extract parameters from a request and put in response

Which is what has been implemented.

**Comment by brijeshps** [comment]
If you have not implemented body templating in “Open source Hoverfly”, then where exactly you have implemented it? Can you please clarify, Whether it’s available as paid service?

I have tried an example mentioned in templating. I have created a request/response pair and imported the same in Hoverfly. The request I fired was http://10.5.0.0:9001/zero/one/two and in the response body I have put "body": "{Test: {{ Request.Path.[1]}}}".  However the “Request.Path.[1]” didn’t parsed and the response was Test: {{ Request.Path.[1]}} only. Please find attached the complete request/response pair for your reference.

Thanks & regards,
Brijesh Kumar

**Comment by mogronalol** [comment]
Have you followed this step from the docs?

https://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/templating/templating.html

> By default templating is disabled. In order to enable it, set the flag to true in the response of a simulation.

Right now alot of our time is dedicated to Hoverfly Cloud which will be available shortly. We left the body parsing out for scope of Hoverfly for now. Please raise another issue if you are in need of any extra features in the area.

**Comment by brijeshps** [comment]
Thanks for informing me that body parsing is not implemented. This is something that I was looking for. Regarding the templating, I have set the flag true. Please find attached the Request/response I have used for your reference. Let me know if I miss anything.

[Test1.zip](https://github.com/SpectoLabs/hoverfly/files/1207686/Test1.zip)

**Comment by mogronalol** [comment]
Could you please create a separate issue for bugs, this is now closed.
