### ISSUE TITLE
Hoverfly could not execute this middleware

### ISSUE THREAD

**Issue by KvMadan** [SpectoLabs/hoverfly#537]
I'm facing below error while using Java as middleware.
Hoverfly could not execute this middleware

Following is the command I'm trying to start.
hoverctl middleware --binary java --script C:\tmp\Test.class

Is Java as middleware supported? Am I using the command incorrectly? or any issue with Java version?

**Comment by benjih** [comment]
@tommysitu is looking into this as he previously stated in https://github.com/SpectoLabs/hoverfly-java/issues/93.

**Comment by KvMadan** [comment]
@tommysitu The class just introduces some random delay. I tried to use packaged jar also but didn't work. 
Tried below commands, but same error. 
hoverctl middleware --binary java --script C:\tmp\Test.jar
hoverctl middleware --binary javaw --script C:\tmp\Test.jar

**Comment by KvMadan** [comment]
@tommysitu With the latest version hoverfly, i am getting below error. 
**_C:\Dev\hoverfly>hoverctl middleware --binary java --script C:\tmp\Test.jar
Hoverfly could not execute this middleware
Invalid middleware: exit status 1_**

**Comment by tommysitu** [comment]
@KvMadan I need to double check. The hoverfly doesn't have any test on JAVA middleware. It could be broken now even if it worked before.

**Comment by KvMadan** [comment]
@tommysitu Can you check and update? So that we will work on alternatives.

**Comment by tommysitu** [comment]
Ok, I will let you know by tomorrow.

**Comment by tommysitu** [comment]
@KvMadan I can reproduce your errors from my end. Passing jar or class file would result the same error: 
```
Hoverfly could not execute this middleware

Invalid middleware: exit status 1
```

I am gonna ask Benji to better understand this problem tomorrow.

Python middleware is working for sure, if you're interested in trying it out.

**Comment by KvMadan** [comment]
@tommysitu Thank you!. We will consider Python as the last option.

**Comment by tommysitu** [comment]
@KvMadan, we found a workaround for Java middleware. 
For instance if you have a compiled java middleware which you can run inside  the shell: `java SomeMiddleware`, you need to put it in a shell script: 
```
#!/usr/bin/env bash

java SomeMiddleware
```
Give it any name, for example `test.sh`

Then in the same folder, import to hoverctl with this command: 
`hoverctl middleware --binary test.sh --script empty.json`

where `empty.json` is just a hack around the file checking in hoverfly, you can replace it with any empty file.

**Comment by tommysitu** [comment]
I imagine if you have a standalone jar file (maybe you need to write  more sophisticated middleware and need to pull in some libraries), then just replace the line in that shell script with `java -jar test.jar`

This is not an ideal solution, but we expect many users found it easier to use python or javascript to manipulate JSON data.

We should improve the support for Java middleware, but the above is the workaround for now. 

If you have any other support query, you can direct it to our Gitter channel (https://gitter.im/SpectoLabs/hoverfly?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by KvMadan** [comment]
@tommysitu can you tell me how we can use JavaScript? any example/reference?

**Comment by tommysitu** [comment]
@KvMadan did you manage to run your Java middleware? We'd like to close this issue if it is fixed. If you need support for javascript middleware please use the Gitter channel.

**Comment by KvMadan** [comment]
@tommysitu I'll check and get back to you soon.

**Comment by KvMadan** [comment]
I'm getting below error. 
C:\hoverfly>hoverctl middleware --binary java_delay.sh --script empty.json
Hoverfly could not execute this middleware
Invalid middleware: fork/exec java_delay.sh: %1 is not a valid Win32 application.

the java_delay.sh file contains 
javaw random_delay.jar
This works fine when i execute outside hoverfly. FYI, the jar file just introduces random delay.

**Comment by tommysitu** [comment]
If you are using Windows, try convert java_delay.sh to batch script?

**Comment by KvMadan** [comment]
@tommysitu Yes, I tried that as well but didn't succeed. 
I'm getting below error. 
_C:\hoverfly>hoverctl middleware --binary C:\tmp\java_delay.bat --script C:\tmp\empty.json
Hoverfly could not execute this middleware_

Invalid middleware: exit status 1

**Comment by tommysitu** [comment]
In that case, I will need to test it on Windows myself.

**Comment by KvMadan** [comment]
@tommysitu thank you. Let me know if you have any suggestions.

**Comment by KvMadan** [comment]
@tommysitu Any updates?

**Comment by tommysitu** [comment]
@KvMadan we are making some changes to middleware, and the goal is to make it work with the executable jar, so that you can do: `hoverctl middleware --binary "java -jar" --script middleware.jar`. 

For the time being, I would recommend you to use other languages. There are some examples here, including the javascript one you asked for:
https://github.com/SpectoLabs/hoverfly/tree/master/examples/middleware

**Comment by KvMadan** [comment]
@tommysitu Thanks for the update. Waiting for the changes soon.
Currently, trying to use python. But will wait for java updates.

**Comment by arisbood** [comment]
Any updates on this?

**Comment by arisbood** [comment]
Getting the same error with python

**Comment by tommysitu** [comment]
What error did you get? @arisbood, and what is the python script you are trying to run?

**Comment by tommysitu** [comment]
A workaround for running java middleware can be found here: https://github.com/tommysitu/hoverfly-java-middleware

Feel free to create a new issue if you run into middleware problem again.
