### ISSUE TITLE
Max size for cache

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#544]
Currently, there is not limit for the size of the cache, so memory consumption could keep going up. If we introduce a limit, it would make this go away. Making it configurable would also be useful:

`hoverctl config set max-cache 1024` or something?

**Comment by JohnFDavenport** [comment]
Hoverfly uses an in-memory cache at the moment which doesn't report memory consumption readily. Replacements give rise to other considerations, particularly performance,  GC performance, cache aging, etc. Ideally profiling is needed in making the right decision.

The lack of reports makes me wonder whether it is an issue in practice. Feedback is needed.

**Comment by tommysitu** [comment]
Implemented in v1.0.0-rc.2
