### ISSUE TITLE
Unable to stop hoverfly local instance

### ISSUE THREAD

**Issue by KvMadan** [SpectoLabs/hoverfly#554]
I'm getting below error when trying to stop the hoverfly instance.
hoverctl stop
Target Hoverfly is not running
Run hoverctl start -t default to start it
FYI, this is happening after the targets were introduced in hoverfly. I always work with the local instance, and what should i change to work with it?

**Comment by benjih** [comment]
Which version of hoverctl are you using? Is the Hoverfly process running?

**Comment by KvMadan** [comment]
@benjih 
hoverctl | v0.11.3  |
| hoverfly | v0.11.3

**Comment by benjih** [comment]
Can you try this with the latest version, [v0.11.4](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.4)

**Comment by KvMadan** [comment]
@benjih thanks! It works with new version.
