### ISSUE TITLE
Deploying hoverfly in cloud foundry

### ISSUE THREAD

**Issue by pradeepkusingh** [SpectoLabs/hoverfly#556]
I remember opening a ticket with the same requirement in past, but unable to find it. so creating a new ticket. This might be a great feature as Cloud foundry is very popular as a private cloud. I am desperately looking for a Mock server which can be deployed in CF.

**Comment by JohnFDavenport** [comment]
Yes, the issue you are looking for is this one: #515

I'll comment there and close this one.
