### ISSUE TITLE
Hoverfly failed to load javascript middleware with multiple modules due to file path

### ISSUE THREAD

**Issue by yougusnc** [SpectoLabs/hoverfly#557]
Hi, first of all, I'd like to say that Hoverfly is a great tool, and thank you for making it available.

I tried to write a middleware with javascript, using "--binary node" option. When I tried to load it with hoverctl, no matter which folder I am in, I always get
`Invalid middleware: exit status 1`

If I check with `hoverctl logs`, I can see that it failed because it cannot do the `require('./config')` in the main .js file (log entry below). Would someone kindly help to explain how I can get around with it? It's not a super simple .js, so I hope to not put all modules into one .js file.

Just to clarify, I am using Mac OS X, and I can run the main js file from any folder with command line such as `node path/to/my/app/middleware.js` with no problem. I also tried a couple of hacks mentioned in [this gist](https://gist.github.com/branneman/8048520), but no good result yet.

`{"error":"exit status 1","level":"error","msg":"Middleware failed to stop successfully","sdtderr":"module.js:472\n    throw err;\n    ^\n\nError: Cannot find module './config'\n    at Function.Module._resolveFilename (module.js:470:15)\n    at Function.Module._load (module.js:418:25)\n    at Module.require (module.js:498:17)\n    at require (internal/module.js:20:19)\n    at Object.\u003canonymous\u003e (/private/var/folders/71/k83kbc752b97_9zz1d9972dm0000gq/T/hoverfly/hoverfly_381257566:7:16)\n    at Module._compile (module.js:571:32)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:488:32)\n    at tryModuleLoad (module.js:447:12)\n    at Function.Module._load (module.js:439:3)\n","sdtdout":"","time":"2017-05-25T11:08:09-05:00"}
[negroni] Completed 422 Unprocessable Entity in 104.950602ms
`

**Comment by yougusnc** [comment]
So I kind of figured out what happened. It seems that `hoverctl middleware --binary node --script middleware.js` command would move and / or rename the middleware.js file to its own folder and run node on it, but the problem is that it did not consider that multiple .js module scenario... I think that is the reason because while I was trying one of the hacks I can see error in log changed to 
`Error: Cannot find module '/private/var/folders/71/k83kbc752b97_9zz1d9972dm0000gq/T/hoverfly/config'\n    at Function.Module._resolveFilename (module.js:470:15)`

I might be able to run it directly using hoverfly instead of hoverctl, but I cannot go that route, because my plan is to run it on a stand-alone remote instance, dynamically controlled with hoverctl command... I might end up doing an ugly hack that requires hard-coding the module folder for each of those modules in the middleware.js...

**Comment by benjih** [comment]
Hey @yougusnc,

Thanks for the feedback, it is appreciated.

You are correct, it works by writing the "middleware script" to a temporary directory which it then executes. The problem with its implementation is that it does not work with multi-file middleware. This has come up in the past and I think it needs thinking, but I also think in general needs a bit of rethinking.

**Comment by yougusnc** [comment]
Hi, @benjih,

Thank you for confirming it. I kind of get the hack more or less working on my local. I do understand that the team probably think that a "heavier" middleware would use an external web-based service, but there might be some middle ground between a single script and an external web-based service...
