### ISSUE TITLE
Oauth2 and Hoverfly

### ISSUE THREAD

**Issue by pradeepkusingh** [SpectoLabs/hoverfly#559]
I haev all my microservices secured by Oauth2 tocken. How hoverfly can get fresh token each time and run test ?

**Comment by mogronalol** [comment]
Hi Pradeepkusingh. Why does Hoverfly need a token if it's simulating your dependency? Or do you mean it's simulating the service which generates tokens?

**Comment by mogronalol** [comment]
@pradeepkusingh Is this question in reference to Hoverfly Cloud by any chance?

**Comment by pradeepkusingh** [comment]
I think I ma good. Thanks for help.
