### ISSUE TITLE
Query params matching issues

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#563]
There are a few issues I found when using a matcher for query params:

1. It is case sensitive
2. It is matching on the query string, not individual params 
3. The wildcard symbol in glob pattern is matching at least one character, while in Linux, `*` matches empty string as well (http://man7.org/linux/man-pages/man7/glob.7.html). At the moment,`*foo*` cannot match `foo`

**Comment by benjih** [comment]
Hey @tommysitu,

Here are my thoughts regarding your three points.
```
1. It is case sensitive
```
This is partially true. When looking at globMatcher (irrespective of which field it is matching against, the wildcard `*` character is case insensitive. The part of the globMatch which is case sensitive is the part you provide. For example: '*est' will match 'test', 'Test' and 'best'. It won't match against 'tesT' or 'besT'. This is inline with how glob matching on a UNIX system works.

What you may be suggesting is that there should be some preprocessing on requests, such as lowercasing the query string. I would suggest raising that as its own issue.

```
2. It is matching on the query string, not individual params
```
This is true, in Hoverfly, the query is currently recorded and stored as a string. I think this needs to be fixed but this will require a change in schema. I will publish an issue today with my proposal and link back to this.

```
3. The wildcard symbol in glob pattern is matching at least one character, while in Linux, * matches empty string as well (http://man7.org/linux/man-pages/man7/glob.7.html). At the moment,*foo* cannot match foo
```
This is not true, I have added tests to the globMatch to prove this.
