### ISSUE TITLE
Proposed schema changes (new schema version v3)

### ISSUE THREAD

**Issue by benjih** [SpectoLabs/hoverfly#569]
With the recent feedback from @tommysitu in ticket https://github.com/SpectoLabs/hoverfly/issues/563, I believe we need to make a change to the current simulation schema.

Currently, request queries are stored as strings. An example value for a request query could be `"?queryOne=true"`. This could be a problem when using multiple query parameters. For example, if your request contains two query parameters, your HTTP client could send these in either order.

```javascript
...
    "request": {
        "query": {
            "exactMatch": "?queryOne=true&queryTwo=false"
        }
    }
...
    "request": {
        "query": {
            "exactMatch": "?queryTwo=false&queryOne=true"
        }
    }
```

Instead, what we I believe we should do is change the request query option to behave like request headers. This means converting the query string into a key value map. 

Before making this change, I think we need to also change headers. Right now, headers in the v2 simulation are fairly basic and follow how headers were recorded from v1. When the new matching options were added, we did not introduce the new matchers to headers. 

My proposed change to requests will look like this
```javascript
{
    "data": {
        "pairs": [
            {
                "request": {
                    "destination": {
                        "exactMatch": "hoverfly.io"
                    },
                    "query": {
                        "queryOne": {
                            "exactMatch": "true"
                        },
                        "queryTwo": {
                            "globMatch": "*"
                        },
                    },
                    "headers": {
                        "Content-Type": {
                            "globMatch": "*application/json*"
                        }
                    },
                }
            }
        ],
        "globalActions": {
            "delays": []
        }
    },
    "meta": {
        "schemaVersion": "v3",
        "hoverflyVersion": "v0.11.4",
        "timeExported": "2017-05-30T14:23:44+01:00"
    }
}
```

**Comment by benjih** [comment]
In conversation with @tommysitu, he reminded me of multiple values.

For example when using Hoverfly in capture mode.
```
curl --proxy localhost:8500 http://hoverfly.io -H "customHeader:one,two"
```
```javascript
"headers": {
    "customHeader": [
        "one,two"
    ],
}
```
```
curl --proxy localhost:8500 http://hoverfly.io -H "customHeader:one" -H "customerHeader:two"
```
```javascript
"headers": {
    "customHeader": [
        "one",
        "two"
    ],
}
```
```
curl --proxy localhost:8500 http://hoverfly.io?customQuery=one,two
```
```javascript
"query": {
    "exactMatch": "customQuery=one,two"
}
```
```
curl --proxy localhost:8500 http://hoverfly.io?customQuery=one&customQuery=two
```
```javascript
"query": {
    "exactMatch": "customQuery=one&customQuery=two"
}
```

With this schema change, I am proposing that when dealing with duplicate query paramaters or headers on inbound requests, we always combined the multiple values into a combined, comma separated value. This schema would introduce a more consist way of dealing with this.
```javascript
"headers": {
    "customHeader": {
        "exactMatch": "one,two"
    },
}
```

```javascript
"query": {
    "customQuery": {
        "exactMatch": "one,two"
    },
}
```

The main disadvantage with this would be that the order of query parameter values would matter when using exactMatch recordings of requests using duplicate query parameter keys. Right now, I feel that this is okay because this problem already exists with headers and should be addressed separately at another point.

**Comment by tommysitu** [comment]
We could have a new type of matcher for multi-values field in the future:
```
"query": {
    "customQuery": {
        "elementsMatch": ["one", "two"]
    },
}
```

**Comment by mogronalol** [comment]
@benjih The convention for query parameters is to repeat them, not have a comma separated list. Like this:

`www.service.com?foo=1&foo=2&bar=1&foo=3`

Which I would translate to something like:

```
"query": {
    "foo": [
        {
          "exactMatch": "1"
        },
        {
          "globMatch", "*"
        }
     ],
     "bar": {
        {
          "exactMatch": "3"
        }
     }
}
```

I'm not actually sure how it would work - an "at least once" strategy would be easiest, where it doesn't care about using the same field for each matcher. For example:

`?foo=1&bar=3` is matched by both the `exactMatch` and `globMatch` for `foo` and bar is matched also. The problem with this though is it has no way of saying how many times the parameter needs to appear.

**Comment by tommysitu** [comment]
@mogronalol, with an array of matchers for the same field, it is ambiguous for how the matching will be done. Is it one matcher per value, or checking each value with all the matchers? 
With your example, `"exactMatch" : "1"` will match `foo=1`, but not the others, so it is a match or not? what if I want to match all of them `foo=1&foo=2&foo=3`, do I need to define three exact matchers?

If the field has multiple values, then it is just an array. To match on array, we use array matcher, just like assertJ library in Java, we can match on: 
- contains any elements
- contains exact elements
- contains some elements
- contains elements with certain patterns 
ects.

**Comment by mogronalol** [comment]
@tommysitu That's what I was getting at by "at least once" where it doesn't care about using the same parameter multiple times. The problem, if you do otherwise, is that the ordering of the list should be ignored, in which case which case how do you know what element applies to each matcher?

**Comment by mogronalol** [comment]
So

`foo=one&foo=two&foo=3`

With a list of matchers for `foo`:

`exactMatch=two,globmatch=*,exactMatch=3`

How does it know what field belongs to each matcher?

**Comment by benjih** [comment]
Could you clarify what you mean @mogronalol?

Regarding your proposal, this is clearly a move towards defining multiple matchers an individual field, or in this situation, multiple matchers each field key.

If we are to go down this route, I think it would make the most sense to update the rest of the request object so that usage of matchers is consistent across fields. This would obviously increase the scope of work for this change.

I see the value in having multiple matchers across each of the fields. An area this would be most useful would be with the body field, opening up the opportunity for people to apply multiple JSONPath and XPath statements.

With the example you provided, I have to agree with @tommysitu. This is confusing. My first assumption was that the `foo` query had to `1` as its the only value that matches both `"exactMatch": "1"` and `"globMatch", "*"`. 

I think this would get even more confusing if we were to implement multiple matchers across a whole request. If we were to have multiple XPath matchers on the body, in that case, we are expecting them all to match. This is different behaviour for what you have suggested for the query.

**Comment by mogronalol** [comment]
If there is a list of values for a single query parameter, and you want a matcher for each one, then how will it work if the ordering of the list changes? There's no way of knowing which matcher applies to which element.

**Comment by benjih** [comment]
I think that complicates things too far. What we are proposing is that the matcher applies to the entire value of the query key. The value may be a single value, may be a comma separated list if multiple values are passed in.

The ordering is an issue when using multiple value, but I think its worth thinking about that in more detail while also considering multiple matchers elsewhere. Right now, the ordering issue is already present when using the current version of Hoverfly but the order effects both keys and values. This changes tries to mitigate and reduce the ordering issue only to requests that have multiple query values.
