### ISSUE TITLE
Returned header changes inner capital letters to small one

### ISSUE THREAD

**Issue by MatousJobanek** [SpectoLabs/hoverfly#573]
Hi guys, 
Your tool is really great, thank you for your job. We are using it in our test suite and I came across a small problem - when I use this setting:
~~~java
hoverflyRule.simulate(dsl(service("https://api.github.com")
            .get("/repos/my/project/releases/latest")
            .willReturn(
                ResponseBuilder.response()
                    .header("X-RateLimit-Remaining", "0")
                    .header("X-RateLimit-Reset", "1496393220")
                    .header("Status", "403 Forbidden")
                    .body(RESPONSE_BODY)
            )));
~~~
then the response contains headers:
~~~
"Status" : "403 Forbidden"
"Transfer-Encoding" : "chunked"
"X-Ratelimit-Reset" : "1496393220"
"X-Ratelimit-Remaining" : "0"
~~~
As you can see the header `X-RateLimit-Remaining` has changed to `X-Ratelimit-Reset`

I there something that I'm missing in my config?

**Comment by mogronalol** [comment]
@MatousJobanek We will double check whether this is a problem with upstream Hoverfly or the DSL.

**Comment by MatousJobanek** [comment]
Thank you very much @mogronalol 
I faced the same problem when I configured it using a file:
~~~java
@ClassRule
public static HoverflyRule hoverflyRule =  HoverflyRule.inSimulationMode(classpath("my-simulation.json"));
~~~
not sure if this information helps anyhow.

**Comment by mogronalol** [comment]
Yes thanks, I just tried the following test and it itsn't a bug in producing the data:

```
@Test
    public void shouldNotMixUpHeaderValues() {
        // Given
        final ResponseBuilder status = ResponseBuilder.response()
                .header("X-RateLimit-Remaining", "0")
                .header("X-RateLimit-Reset", "1496393220")
                .header("Status", "403 Forbidden")
                .body("");

        // When
        final Response response = status.build();

        // Then
        assertThat(response)
                .hasExactHeaders(
                        header("X-RateLimit-Remaining", "0"),
                        header("X-RateLimit-Reset", "1496393220"),
                        header("Status", "403 Forbidden"));
    }
```

The file you have will end up being posted to Hoverfly which contains the simulation logic. I'll drop an issue on their.

**Comment by mogronalol** [comment]
@MatousJobanek Sorry, just realised we are already on the Hoverfly GitHub, I saw the Java code and thought we were on Hoverfly Java. Could you the `json` in this issue please?

**Comment by MatousJobanek** [comment]
Here you can find the JSON file: https://gist.github.com/MatousJobanek/a0d5fca17617b247916c88aa21891b67

**Comment by mogronalol** [comment]
@MatousJobanek I've noticed you are using the older schema version (v1).

If you try `hoverctl import my-simulation.json && hoverctl export my-simulation-v2.json` it should upgrade it but work functionally the same. If that's the case, there's a chance the bug could have been resolved already. Let me know if it helps, please. If not could you take a look please @benjih?

**Comment by MatousJobanek** [comment]
So I upgraded to the newer schema version, but it didn't help - the header has changed again...

**Comment by benjih** [comment]
Hey @MatousJobanek,

I am taking a look into this now. I think you are correct. At first glance, it definitely isn't using the correct case. This is the case with v1 and v2 simulations. I did notice that if you added an additional hyphen, making it to `X-Rate-Limit-Reset`, Hoverfly will respect the capital L.

**Comment by benjih** [comment]
@MatousJobanek @mogronalol 

So in closer inspection, this is something that is being done by Golang. When Hoverfly reconstructs a response ready to be served, it uses the `http.Header` struct's `Add()` function.

https://github.com/SpectoLabs/hoverfly/blob/master/core/modes/modes.go#L82

This add function ends up calling a function in the `textproto` called `CanonicalMIMEHeaderKey()`. This function is the one that is changing the cases of characters.

https://github.com/golang/go/blob/master/src/net/textproto/reader.go#L562

We could bypass this by adding headers to the `http.Header` struct directly, avoiding any calls to `CanonicalMIMEHeaderKey()`.

**Comment by MatousJobanek** [comment]
Hi @benjih 
Yeah, when I use the additional hyphen, then it works. Unfortunately, the logic that I'm testing consumes responses from GitHub API, and the header contains the key: `X-RateLimit-Reset`.

**Comment by benjih** [comment]
@MatousJobanek, 

Yeah, I wouldn't expect you to have to change your simulation to get the right response.

I'm still looking into fixing this. Even when avoiding `CanonicalMIMEHeaderKey()` by writing the Headers map directly, the header key still gets tampered with. I think Golang must be checking/validating the headers before they are sent back as there is no code in Hoverfly that would do this.

I will continue investigating and see if I can find out what is modifying the Header key now.

**Comment by benjih** [comment]
Hey @MatousJobanek,

I've raised a PR with what I believe is a fix to your issue. In the end, I was able to work around Golang's imposed standardization to header keys.

Once this is in master, we will look at making a patch release to Hoverfly and updating Hoverfly-Java.

Thanks for pointing this out and keep on simulating!

**Comment by tommysitu** [comment]
Hi @MatousJobanek I am about to release a new version of Hoverfly-Java that will fix the bug. It won't be available on Maven Central until later today or tomorrow. 

At the mean time, if you want to try it out, you could use the `0.6.1-SNAPSHOT` version. Here is how you [include Hoverfly-Java SNAPSHOT version in your project](http://hoverfly-java.readthedocs.io/en/latest/pages/misc/misc.html#using-snapshot-version)
