### ISSUE TITLE
Run hoverfly using automatic configuration script

### ISSUE THREAD

**Issue by kallolghose** [SpectoLabs/hoverfly#583]
Hi,

I am using hoverfly as proxy server to capture responses in a WebPage, I am sitting behind a corporate automatic configuration script, so when I run hoverfly am getting error **(connectex: A connection attempt failed because the connected party did not properly respond)** open as I am not able set the automatic configuration script to my proxy server. 

So, is there a way to start the hoverfly using automatic configuration script(.dat) file.

Thanks in advance !!

**Comment by benjih** [comment]
Hey @klloghose

Are the requests you are trying to capture from the webpage using web sockets?

**Comment by kallolghose** [comment]
Hi @benjih 

Yes i am trying to capture the request from webpage but not using web sockets. The webpages are behind a corporate proxy which is implemented using Proxy Auto-Config(PAC) file. 
Hoverfly uses upstream-proxy but we need to use the PAC file. Is there a way to do this ?
OR 
Is there a way to send some requests through the upstream-proxy and some without using any proxy?

Thanks !!

**Comment by JohnFDavenport** [comment]
Closing this issue as it has gone stale. Reopen if needed! It seems someone intended to make it hard for tools such as Hoverfly here. Hoverfly is primarily an API Simulation or Service Virtualization tool - we'd need to see more demand for use-cases such as this - or maybe a PR!
