### ISSUE TITLE
database simulation

### ISSUE THREAD

**Issue by pradeepkusingh** [SpectoLabs/hoverfly#585]
Scenario :I have few values stored in DB and read from my Micro services. How can I acheive it using hoverfly and no db involve. I would like to have hoverfly work as DB store and I can do all testing like DB goes down and if Data not available without involving real DB.

**Comment by JohnFDavenport** [comment]
What is the database and what protocol does the DB use to connect to your application?

**Comment by pradeepkusingh** [comment]
BD is redis and mongo. we use jdbc connector to connect those.

Thanks,
Pradeep Singh
Please excuse typos.

**Comment by JohnFDavenport** [comment]
Hi, we don't support JDBC in Hoverfly. @danielbryantuk Wrote a blog on subject which explains the reasons and some of the alternatives that we suggest. You can read it [here](https://specto.io/blog/2016/8/25/is-service-virtualisation-useful-simulating-datastores-and-messaging/).

**Comment by pradeepkusingh** [comment]
Ok, Thanks you.

Thanks,
Pradeep Singh
Please excuse typos.

**Comment by JohnFDavenport** [comment]
I hope the article assists. Feel free to ask more questions although the gitter channel is probably best for that as you can get immediate responses there. 

I'll close this issue now.

**Comment by mogronalol** [comment]
@pradeepkusingh If there is a HTTP interface for Redis or Mongo, then you could use that as an alternative. Hoverfly can simulate any HTTP traffic, including HTTP database traffic.
