### ISSUE TITLE
Hoverfly only loading static contents

### ISSUE THREAD

**Issue by kallolghose** [SpectoLabs/hoverfly#604]
Hi,

I have a webpage where most of the data is loaded dynamically (including js and css), if I start recording with hoverfly after clearing cache, then on simulation js and css files are not loading as they are not in the cache and hoverfly does not keep any information regarding them.

So, is there any option in hoverfly whereby I can specify which API(s) to be recorded. So, that the remaining API(s) are fetched directly from the website's server.

Thanks in advance !!

**Comment by benjih** [comment]
Hey @kallolghose,

It sounds like you may be after the destination option in Hoverfly. This is a regex pattern that will filter requests Hoverfly intercepts. If the data on the webpage is coming from a different address than the static files, you could just set the destination to the URL that the data is coming from.

Please check out the section of the docs and please let me know if this solved your issue or not.

[Destination filter](https://docs.hoverfly.io/en/latest/pages/keyconcepts/destinationfiltering.html)

**Comment by kallolghose** [comment]
Hi @benjih,

I used destination and it would solve my issue. But I am facing another issue, I am trying to use negative lookahead regex (Example: hoverctl destination **"^(?!.*(js|css)).*$"**)  which should not match URL containing JS or CSS in them but the rest should mactch. 

But when I try to use the same in destination it is giving me **Regex pattern does not compile** error. 

How should I give the regex which would not match JS or CSS contained in the URL string ??

Thanks in advance !!!

**Comment by benjih** [comment]
Golang regex does not current support negative lookahead regex. You will have to rewrite to regex query to instead match on the endpoints you are trying to simulate rather than using regex to filter out the requests you want.

**Comment by kallolghose** [comment]
Okay !! am now specifying the destination with all the requests that i want. 

Thanks !!

**Comment by benjih** [comment]
Excellent news! Glad to hear it.
