### ISSUE TITLE
jsonPath match expression not working

### ISSUE THREAD

**Issue by subham1112** [SpectoLabs/hoverfly#636]
I am trying to send the following request to hoverfly webserver simulator :
{
	"number1": "23423424",
	"number2": "23234242",
	"text1": "abc",
	"mockObj": {
		"searchText": "1234"
	}
}

The intent is to respond with response :

{
status: "SUCCESS"
}

now, in the simulated json file for hoverfly, the request object is:
"request": {
	"path": {
		"exactMatch": "/abc/def"
	},
	"method": {
		"exactMatch": "POST"
	},
	"scheme": {
		"exactMatch": "http"
	},
	"body": {
		"jsonPathMatch": "$[?(@.searchText=='1234')]"
	}
}

 However, I am getting the following error from hoverfly:

Hoverfly Error!

There was an error when matching

Got error: Could not find a match for request, create or record a valid matcher first!

The matcher which came closest was:

{
    "path": {
        "exactMatch": "/abc/def"
    },
    "method": {
        "exactMatch": "POST"
    },
    "scheme": {
        "exactMatch": "http"
    },
    "body": {
        "jsonPathMatch": "$[?(@.searchText=='1234')]"
    }
}

But it did not match on the following fields:

[body]
Which if hit would have given the following response:

Is there something I am missing here. I ran the jsonPath expression against jsonPath expression matcher tools online and they responded with the correct value. Please help.

**Comment by subham1112** [comment]
Any news on this please?

**Comment by benjih** [comment]
Your looks incorrect for usage in Hoverfly. I was able to get your request working with `$.mockObj.searchText?(@ == \"1234\")`. The jsonPath you provided would never work with the JSON object you provided as your jsonPath requests an element from an array at the root `$[` and then the query being refers to a field that is ignoring its parent field.

**Comment by subham1112** [comment]
Thank you @benjih  for the response. I was able to replicate your suggestion into my use case and am able to filter based on partial match now.
