### ISSUE TITLE
jsonMatch does not partially match

### ISSUE THREAD

**Issue by benjih** [SpectoLabs/hoverfly#641]
Previously mentioned here #627

The jsonMatch matcher in Hoverfly currently does not support partial matching. For jsonMatch to match, the full JSON is required.

**Comment by tommysitu** [comment]
This is now implemented by @dilitvinov PR. Will update the doc before a release.

**Comment by tommysitu** [comment]
A new JSON partial matcher is available in v1.0.0. You can find some examples here: https://hoverfly.readthedocs.io/en/latest/pages/reference/hoverfly/request_matchers.html#json-partial-matcher
