### ISSUE TITLE
Capturing requests & responses from an application deployed in weblogic

### ISSUE THREAD

**Issue by brijeshps** [SpectoLabs/hoverfly#647]
I am trying to capture request & response from an application using Hoverfly. The hoverfly is installed on a machine and set in proxy with capture mode.
The application is a web application deployed in Weblogic in linux box.The application uses soap requests to communicate to Tibco ESB server and fetch details from provider systems. I want to capture the soap requests & responses between application server & ESB.

To capture the request & response I have set proxy in Application server in following ways.

1) Add the proxy parameters in setDomianEnv.sh script of application server
	EXTRA_JAVA_PROPERTIES="-Dhttp.proxyHost=10.0.0.1 -Dhttp.proxyPort=8500 ${EXTRA_JAVA_PROPERTIES}"
	export EXTRA_JAVA_PROPERTIES
2) add the proxy parametes in JVM startup parameters of application

3) set proxy for os level user
	http_proxy=http://10.0.0.1:8500

In all the three cases I have failed to capture requests & responses in hoverfly. No requests & responses routed through hoverfly.

can anyone help what went wrong in these three approaches? Is there any otherway to do the same or any additional settings to be done to route the request & response through proxy?

**Comment by JohnFDavenport** [comment]
This doesn't appear to be a problem with Hoverfly. If the proxy is configured correctly Hoverfly will intercept the traffic. I suggest referring your question to your Weblogic support team as it's a licensed product, or maybe put it up on Stackoverflow.
