### ISSUE TITLE
Feature Request: "pass-through simulate mode"

### ISSUE THREAD

**Issue by mackantestar** [SpectoLabs/hoverfly#648]
Hi,

Use Case:

For example a web application providing customer specific data for logged in customers

**client <--api--> web app** <--api to simulate/pass through--> back end 

We only have control of the **bold** part above

There are cases when we want to simulate only certain services for a particular logged in customer. Could be that one of the services is slow, shaky, not complete, or we want to easily change the response.
Simulating one of the services can be a way of achieving e2e scenarios.

All other services though we want to "pass-through" to the real end-point. 

Instead of inside the web app create logic or point one of the services to the simulated, its much easier to just set a proxy for the whole web app. And the proxy decides if simulating or pass-through will happen. 

Related scenario

Lets say we simulate all services that a particular customer needs while logged in. We still want to be able to log in with another customer and for this customer recieve real data

What do you think about this functionality?

Best Regards
Marcus

**Comment by JohnFDavenport** [comment]
I can see that this would be useful in some cases.

From my own experience, I have worked with some legacy systems which for various reasons have no good equivalent test system. When testing new systems that use them it becomes necessary to populate them with test data to simulate new functionality in the front-end or web-app in this example. The test data is distinguished by a fake customer-id, bank account number or flight number.

However, I don't personally see it as core functionality. It may fall into the category of a new business application for Hoverfly which would help customers with legacy systems.

How important is to your business @mackantestar ?

**Comment by mackantestar** [comment]
Main idea for us with using hoverfly is actually to be able to serve testdata, as we cant add test-data directly in the back end. 

So we record data for real customer(-id), 
then create a fake customer-id (in the authentication system), 
then we change in the simulation.json so that req-resp pairs will match calls with the fake id instead of the real id
hoverfly will respond instead of the real system for the fake-id. And we also have complete control of the  responses

In practice we have created a test-customer in the back end..

Of course when we later test we could do a separate deploy with hoverfly set as proxy, and another deploy without the proxy

So mocked-tests for one deploy, test with real data in another deploy 

With the  "pass-through simulate mode" we can instead just have one deploy for all our tests. Its just a matter of if we log in with fake och real customer

**Comment by mogronalol** [comment]
We already have an issue for this #389 which I think covers the functionality you are after.

**Comment by mackantestar** [comment]
Aha yes it does. Didn't see 

Thank you both
