### ISSUE TITLE
Enhancement: Possibility to set response body to object instead of string in the schema.json

### ISSUE THREAD

**Issue by mackantestar** [SpectoLabs/hoverfly#649]
Hi,

Use Case:
The response body to my requests is always json. 

When the simulation.json file is created, just like it says in the schema.json, the body is treated as a string.

So the simulation.json file looks for example like this
...
"body": "{\\"key\\":\\"value\\"}"
...

It would be really nice if the body could be treated as an object instead (some setting somewhere). 

Resulting in simulation.json to look like this
...
"body":{"key":"value"}
...

Then simulation.json is directly passed in whatever json viewer you are using and you can more easily analyize the payload without extra steps

Can this be something of interest?

Thanks!

**Comment by mogronalol** [comment]
We're aware that the JSON within JSON is quite difficult to reason about due to the escape characters. However, I am not sure about your suggestion as it would result in invalid JSON. What we are working on is a simulation editing UI which would do the unescaping for you. Does this sound like a viable alternative?

**Comment by mackantestar** [comment]
My suggestion with the schema.json set to object for body was more of a conceptual one.
At the same time data added to the simulation.json has to be in the right format of course. 

I guess this is a matter of how hoverfly handles the response body in the first place.

Im happy and grateful with all your work and a UI does sound like a viable alternative.  

thanks
