### ISSUE TITLE
GET requests with body are recorded but not matched

### ISSUE THREAD

**Issue by krzd** [SpectoLabs/hoverfly#664]
It is possible to correctly record GET requests with a body, but a request will never match it in simulation mode.
Such requests are not actually against the HTTP specification and are used for example in ElasticSearch to allow complex JSON queries without using POST and thus making it easy to distinguish and manage read and write operations.
If a body is present in a recorded GET request, it should probably be considered as for any HTTP verb.

**Comment by tommysitu** [comment]
That's true, it is not against the HTTP spec, but at the same time not many tools support it, for example, Postman and curl won't let me make a GET request with a body. Could you let me know how you make such request so that I can reproduce the problem?

**Comment by krzd** [comment]
When using curl it is true that using `--data` will switch it to `POST` by default, but can be switched back by explicitly specifying `-X GET` as evidenced by the verbose output using `-v`.

For example: `curl -v -X GET --data '{"query":{"match":{"field":"test"}}}' https://elasticsearchurl/index/_search`


I tend to prefer Paw of Postman where you can enable bodies for GET requests in the settings, at least when I last used it.


Postman does indeed not support it as far as I can tell and they do not seem to want to support it (https://github.com/postmanlabs/postman-app-support/issues/131 and https://github.com/postmanlabs/postman-app-support/issues/2004).


Hope that helps.

**Comment by mogronalol** [comment]
@krzd I don't actually think this is the case. Take the following simulation:

```
{
	"data": {
		"pairs": [
			{
				"request": {
					"path": {
						"exactMatch": "/"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "www.google.com"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"exactMatch": ""
					},
					"body": {
						"exactMatch": "{\"query\":{\"match\":{\"field\":\"test\"}}}"
					}
				},
				"response": {
					"status": 408,
					"encodedBody": false
				}
			}
		],
		"globalActions": {
			"delays": []
		}
	},
	"meta": {
		"schemaVersion": "v4",
		"hoverflyVersion": "v0.14.2",
		"timeExported": "2017-10-07T13:56:02+02:00"
	}
}
```

If I run:

```bash
hoverctl import my-simulation.json
hoverctl mode simulate
curl -v -X GET --data '{"query":{"match":{"field":"test"}}}' http://www.google.com --proxy localhost:8500 -v
* Rebuilt URL to: http://www.google.com/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8500 (#0)
> GET http://www.google.com/ HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.54.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 36
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 36 out of 36 bytes
< HTTP/1.1 408 Request Timeout
< Date: Sat, 07 Oct 2017 12:00:25 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
```

I get 408 as expected.

**Comment by tommysitu** [comment]
I could not reproduce the issue either: 
```
Tommys-MacBook-Pro:simulations tommysitu$ curl -v -X GET http://www.google.com --proxy localhost:8500 -v
Note: Unnecessary use of -X or --request, GET is already inferred.
* Rebuilt URL to: http://www.google.com/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8500 (#0)
> GET http://www.google.com/ HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.54.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 502 Bad Gateway
< Content-Type: text/plain
< Date: Sat, 07 Oct 2017 13:37:39 GMT
< Content-Length: 1146
<
Hoverfly Error!

There was an error when matching

Got error: Could not find a match for request, create or record a valid matcher first!

The following request was made, but was not matched by Hoverfly:

{
    "Path": "/",
    "Method": "GET",
    "Destination": "www.google.com",
    "Scheme": "http",
    "Query": {},
    "Body": "",
    "Headers": {
        "Accept": [
            "*/*"
        ],
        "Proxy-Connection": [
            "Keep-Alive"
        ],
        "User-Agent": [
            "curl/7.54.0"
        ]
    }
}

Whilst Hoverfly has the following state:

{}

The matcher which came closest was:

{
    "path": {
        "exactMatch": "/"
    },
    "method": {
        "exactMatch": "GET"
    },
    "destination": {
        "exactMatch": "www.google.com"
    },
    "scheme": {
        "exactMatch": "http"
    },
    "query": {},
    "body": {
        "exactMatch": "{\"query\":{\"match\":{\"field\":\"test\"}}}"
    }
}

But it did not match on the following fields:

[body]

Which if hit would have given the following response:

{
    "status": 408,
    "body": "",
    "encodedBody": false,
    "templated": false
* Connection #0 to host localhost left intact
}
```

**Comment by tommysitu** [comment]
It is trying to match the body for the GET request from the debug message. Do you mind sharing your simulation file, @krzd? There could be other issues.

**Comment by krzd** [comment]
In my case I have multiple requests to two different endpoints, so there is a body1 sent to '_search' and to '_mtermvectors' as well as a body2, ...
As soon as I switched to `POST` it all worked and that was indeed the only change to the simulation file too.
Unfortunately, I cannot provide my whole simulation file and when trying to reduce it down, I noticed that ours is incompatible with the latest version.
It may even be that it does not occur with it, so I will close this for now and come back to you when I can reproduce it with the latest version with something I can share.

**Comment by mogronalol** [comment]
You should be able to import any simulation version into the latest Hoverfly and it should automatically upgrade it for you.

**Comment by krzd** [comment]
```hoverctl import Documents/django-kvasir/extern/kvasir_data_integrations/hoverfly_data/trma.json
Could not import simulation

Invalid JSON, missing "meta" object```


[test.txt](https://github.com/SpectoLabs/hoverfly/files/1368368/test.txt)

**Comment by mogronalol** [comment]
Ah right, your simulation must be very old then. They have been versioned with the meta field for over a year I think. As long as it's versioned you should be fine, but otherwise, it will fail (This is the case for you).

**Comment by krzd** [comment]
We are still using v0.10.1 released in February -- https://github.com/SpectoLabs/hoverfly/releases/tag/v0.10.1

**Comment by JohnFDavenport** [comment]
So, I think the conclusion to this (it requires a lot of reading and I'm likely to forget) is that Hoverfly will capture the body in a GET request _if present_ and in simulate mode will match on the body in a GET request _if present_. The body is not required, as per the HTTP spec.
