### ISSUE TITLE
Simulation contains exact and regex matchers failed to produce strongest matching

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#665]
Giving the following simulation, all these requests:
`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=notfound`
`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=empty`
`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=Berlin`

return the same response: 
`["Amsterdam","Boston", "Berlin", "Dubai"]`

but we expect the ones with query `location=empty` and `location=notfound` return different exact-matched response as the default matching strategy should be `strongest`. 

This problem seems to go away if I run `hoverctl mode simulate` before making those requests.

```
{
	"data": {
		"pairs": [
			{
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"exactMatch": "location=notfound"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 404,
					"body": "{\"msg\" : \"city not found\"}",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			},
			{
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"exactMatch": "location=empty"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 200,
					"body": "[]",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			},
      {
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"regexMatch": "location=[a-zA-Z]+"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 200,
					"body": "[\"Amsterdam\",\"Boston\", \"Berlin\", \"Dubai\"]",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			}
		],
		"globalActions": {
			"delays": []
		}
	},
	"meta": {
		"schemaVersion": "v4",
		"hoverflyVersion": "v0.14.2",
		"timeExported": "2017-10-05T10:52:42+02:00"
	}
}
```

**Comment by mogronalol** [comment]
I'm not sure what the issue with this is? All the matchers will have the same score, so in that event it picks the last one (which is what it is doing).

**Comment by jpartner** [comment]
Thats the point it wasn't always picking the last one.

**Comment by mogronalol** [comment]
What I have got from Tommy is:

> return the same response:
["Amsterdam","Boston", "Berlin", "Dubai"]
but we expect the ones with query location=empty and location=notfound return different exact-matched response 

That is incorrect. They should all return the _same_ exact-matched response, as they all have the same score.

I'll try re-ordering the simulation and see if I can get it to break.

**Comment by mogronalol** [comment]
Yes, if I re-order it so the last matcher is first:

```
{
	"data": {
		"pairs": [
			{
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"exactMatch": "location=notfound"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 404,
					"body": "{\"msg\" : \"city not found\"}",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			},
			{
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"exactMatch": "location=empty"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 200,
					"body": "[]",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			},
      {
				"request": {
					"path": {
						"exactMatch": "/api/v1/recommendations"
					},
					"method": {
						"exactMatch": "GET"
					},
					"destination": {
						"exactMatch": "localhost:8081"
					},
					"scheme": {
						"exactMatch": "http"
					},
					"query": {
						"regexMatch": "location=[a-zA-Z]+"
					},
					"body": {
						"exactMatch": ""
					}
				},
				"response": {
					"status": 200,
					"body": "[\"Amsterdam\",\"Boston\", \"Berlin\", \"Dubai\"]",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Thu, 05 Oct 2017 08:51:45 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						]
					},
					"templated": false
				}
			}
		],
		"globalActions": {
			"delays": []
		}
	},
	"meta": {
		"schemaVersion": "v4",
		"hoverflyVersion": "v0.14.2",
		"timeExported": "2017-10-05T10:52:42+02:00"
	}
}
```

Then that is still the one that gets picked, which is wrong.

**Comment by jpartner** [comment]
There seems to be some confusion on what is expected and documentation isn't clear. Andrew I believe you implemented this so can you state your understanding of what is expected please.

**Comment by mogronalol** [comment]
The behavior should still be the same as before scoring was implemented, but I don't know whether it picked the first or last one. I'll just go for last as that seems to make sense to me (As it will iterate all the elements each time)

**Comment by mogronalol** [comment]
Okay, so after trying to reproduce a failure with tests I've realised that it is indeed behaving correctly. What I can do is break it down by putting the matching process into a tabular view. Here is the first simulation posted by Tommy (I've omitted body and scheme):

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 

So when performing matching the last match is always picked:

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=notfound`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=empty`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=berlin`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |

So the last matcher in the simulation will be chosen for every request, meaning that simulation should always return:

`["Amsterdam","Boston", "Berlin", "Dubai"]`

This is what happens. If you bear with me I'll repeat this for a re-ordered version...

**Comment by mogronalol** [comment]
Now, let's try again with the same simulation, only this time we have moved what was once the last matcher to the beginning:

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 

We are still picking the last matcher, but now it is different to the one in the previous example:

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=notfound`
`[]`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 3 | false |

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=empty`
`{"msg" : "city not found"}`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 3 | false |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 4 | true |

`curl --proxy localhost:8500 localhost:8081/api/v1/recommendations?location=berlin`
`["Amsterdam","Boston", "Berlin", "Dubai"]`

| Path ExactMatch  | Method ExactMatch | Destination Exact Match | Query Exact Match | Query Regex Match | Score | Matches? |
|-------------------|---------------------|-------------------------|-------------------------|---------------------|-------|-----------|
| /api/v1/recommendations | GET | localhost:8081 | | location=[a-zA-Z]+ | 4 | true |
| /api/v1/recommendations | GET | localhost:8081 | location=notfound | | 3 | false |
| /api/v1/recommendations | GET | localhost:8081 | location=empty | | 3 | false |

This still works as it should, always picking the last matcher.

I have found where this is documented, and it looks like it is saying the opposite (Picks the first, so I'll correct it)

**Comment by tommysitu** [comment]
That explains it. But would it be more sensible to give exact matcher a higher score: 

So for this query `localhost:8081/api/v1/recommendations?location=notfound`
```
"query": {
   "exactMatch": "location=notfound"
}
```
will be a stronger matcher than this loose matcher: 
```
"query": {
   "regexMatch": "location=[a-zA-Z]+"
}
```

The use case for this would be what Brian wanted to do, to return empty array if the location is `empty`, return an not found error if the location is `notfound`, and then return a normal response if the location is anything else.

**Comment by mogronalol** [comment]
I think that complicates things a little bit, giving different scores to different types of criteria. Everything being +1 seems easier to reason about. In this case, you could get around things by doing:

```
"query": {
   "exactMatch": "location=notfound",
   "regexMatch": "location=[a-zA-Z]+"
}
```

This would add an extra point meaning it would take precedence.

There's also the idea of an `overrideScore` field as a future feature which you can use to set a priority.
