### ISSUE TITLE
"Applying a delay to all responses" tutorial documentation doesn't make sense

### ISSUE THREAD

**Issue by jg8481it** [SpectoLabs/hoverfly#669]
Specifically this part...

http://hoverfly.readthedocs.io/en/latest/pages/tutorials/basic/delays/allresponses/allresponses.html

![image](https://user-images.githubusercontent.com/19155572/31541994-5bb77b90-afde-11e7-8f5e-19a3348b24ce.png)

**Comment by tommysitu** [comment]
@jg8481it it is fixed. Thank you for pointing that out!
