### ISSUE TITLE
what version has java 7 support

### ISSUE THREAD

**Issue by donhill** [SpectoLabs/hoverfly#672]
I am on a java 7 project and would like to know if there is a version that supports java 7

**Comment by tommysitu** [comment]
Hi @donhill, the  [hoverfly-java](https://github.com/spectolabs/hoverfly-java) project only supports JAVA 8, but we will look into building a multi-release jars in the future using this Java 9 features: https://blog.jetbrains.com/idea/2017/10/creating-multi-release-jar-files-in-intellij-idea/

**Comment by tommysitu** [comment]
@donhill you're welcome to create an issue for Java 7 support in https://github.com/spectolabs/hoverfly-java project

Closing this now.
