### ISSUE TITLE
allow users to switch from proxy to webserver mode during runtime

### ISSUE THREAD

**Issue by sherl0cks** [SpectoLabs/hoverfly#674]
Seems like a few unnecessary steps to do shutdown and reboot the server with a new config. If possible today, let me know.  I couldn't find it in the CLI or the docs.

**Comment by JohnFDavenport** [comment]
You can switch hoverfly modes, e.g. from capture to simulation easily using hoverctl. However, I'm guessing you mean rebooting 'the server' with a new configuration is the issue? Can you give some more details on what you are doing before and after the reboot, and what you mean by 'the server'.

**Comment by sherl0cks** [comment]
@JohnFDavenport I'm referring to webserver vs proxy e.g. `hoverctl start webserver` vs `hoverctl start`. The server in this case is the hoverfly instance. I'm currently deploying hoverfly in OpenShift with https://github.com/sherl0cks/labs-ci-cd/tree/tool-box-zip/docker/hoverfly. I'm not using the shipped docker containers due to #675. Since I have to kill the hoverfly process to switch from proxy to webserver, that also requires me to deploy a new container, which also means I need to export simulation.json and then import it in the new container.

**Comment by tommysitu** [comment]
@sherl0cks Switching proxy modes during runtime is not supported. What's your use case for this feature?

**Comment by JohnFDavenport** [comment]
Thanks for the clarification. A lot of things are possible with Hoverfly ... the more you look into it, the more you realize that actually very little difference between proxy and webserver mode from Hoverfly's point of view. 

Could you say why you are switching modes and what you are trying to do? There may be other ways to achieve what you want to do.

**Comment by sherl0cks** [comment]
Use case is simple - run https://docs.hoverfly.io/en/latest/pages/tutorials/basic/exportingsimulations/exportingsimulations.html when hoverfly is in a container. That requires running at least two containers, which is annoying as a user. I realize this is feature request, let me know if you are interested in it. If not, no worries we can close this issue.

**Comment by tommysitu** [comment]
If hoverfly is running in a container, you can switch between capture and simulation mode using its API, so one hoverfly running as a proxy would be enough. Unless you want to capture using proxy, and simulate using web server mode, then yes you need to run two containers.

**Comment by sherl0cks** [comment]
@tommysitu I am aware of the former scenario and yes, it is easy to execute. however; this ticket is discussing the latter scenario.

**Comment by tommysitu** [comment]
Hi @sherl0cks thank you for your suggestions. It will improve usability but the change would require a bit of effort. We can revisit this in the future, will close this for now.
