### ISSUE TITLE
Capture different responses for the same GET request

### ISSUE THREAD

**Issue by edsrzf** [SpectoLabs/hoverfly#679]
In capture mode, hoverfly will record the first response it sees for a particular GET request, but not any other, different responses later. It's possible that a mutating request, such as a POST, PUT, or DELETE, could change the response. This behavior can be simulated with state, but that requires manual modification of the simulation data. It would be nice to be able to capture this sort of flow without having to do anything manually.

One way to fix this might be for capture to add a special, numeric state field. It would add a `transitionsState` to any potentially-mutating requests that increments the field. Then it would add the appropriate `requiresState` to all GET requests (or maybe all requests).

Effectively this means that responses are invalidated after a mutating request. This solution obviously isn't foolproof, but I bet it would work for many cases.

Thoughts? Other possible solutions? (Also, I'm pretty new to hoverfly, so please forgive me if I've overlooked something that already exists.)

**Comment by JohnFDavenport** [comment]
I have seen simple sequential state detection and recording such as this implemented. See my comment dated 1 Jun in #428. It does work - as you say in many cases.

I quite like the idea of annotating the simulation file automatically as it is a bit of an imposition to do that. It would help later. Your suggestion makes sense. We would have to look to see if Hoverfly detect statefulness easily during capture. 

The only objection is that this feature would be great for demonstration but is it so good for testing? Do you contrive the test so much that you end up with a fragile test and you'd be better with a bunch of smaller tests? Any concrete use-cases?

**Comment by benjih** [comment]
I have added a simple implementation of recording duplicate requests, storing each unique request response with a sequence number which can be stepped through in simulate mode.

This will be included in the next release of Hoverfly, v0.17.0. I will update this ticket when that has been released.

**Comment by tommysitu** [comment]
v0.17.0 is now available, you can check here for this new feature: https://hoverfly.readthedocs.io/en/latest/pages/tutorials/basic/capturingsequences/capturingsequences.html
