### ISSUE TITLE
fatal message Could not create a hoverfly directory

### ISSUE THREAD

**Issue by yotsubakoiwai** [SpectoLabs/hoverfly#681]
I am new to this tech stack and playing around with it. But when I extracted hoverlfy on my C:\ and added it to my Path env variable, then run **hoverctl version** (as per the docos), it gives me 

> level=fatal msg="Could not create a .hoverfly directory".

How to fix it?

**Comment by tommysitu** [comment]
Which version of Windows are you using?

**Comment by yotsubakoiwai** [comment]
Windows 7 x64

Thanks,
Jackie

**Comment by tommysitu** [comment]
Unfortunately, I don't see this error when I tried it on Windows 7. 
The error suggests that `hoverctl` failed to create the `.hoverfly` config folder in your home folder (eg. C:\Users\<your username>\.hoverfly). It could be your folder permission settings preventing it.

**Comment by navadutha** [comment]
I am facing the same error ... how did this get resolved ?? Please suggest.
level=fatal msg="Could not create a .hoverfly directory".

**Comment by enidzheng** [comment]
yes, I am facing the same error too.......any solution pls?

**Comment by enidzheng** [comment]
> I am new to this tech stack and playing around with it. But when I extracted hoverlfy on my C:\ and added it to my Path env variable, then run **hoverctl version** (as per the docos), it gives me
> 
> > level=fatal msg="Could not create a .hoverfly directory".
> 
> How to fix it?

**Comment by tommysitu** [comment]
@enidzheng it sounds like a Windows permission issue. Are you running `hoverctl` as an admin? 

> Unfortunately, I don't see this error when I tried it on Windows 7.
> The error suggests that `hoverctl` failed to create the `.hoverfly` config folder in your home folder (eg. C:\Users<your username>.hoverfly). It could be your folder permission settings preventing it.

**Comment by enidzheng** [comment]
@tommysitu , yes, seems . nah, I didn't run as admin, as I don't have admin on my laptop:(.  But  I can manually create folder under the same path.
