### ISSUE TITLE
Hoverfly docker image

### ISSUE THREAD

**Issue by devenfc** [SpectoLabs/hoverfly#686]
Hi,
I need to run hoverfly inside docker. I am not able to send any traffic to docker container host admin & proxy port. 

Does server just listen to 127.0.0.1 only ? 

Is there any option to bind server to all interfaces inside docker container ?

**Comment by tommysitu** [comment]
Hi @devenfc, 

The latest release of hoverfly (v0.15.0) does not bind to all interface by default, but I think it should be an exception for Docker image. You can run this for the time being: `docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest -listen-on-host 0.0.0.0`

**Comment by devenfc** [comment]
Hi @tommysitu 

Thanks for update.

It fixed my issue.

**Comment by invoicesharing-developers** [comment]
Hi @tommysitu,

I am trying to connect 2 dockers. One only with the hoverctl and the other with hoverfly. But the binding is impossible even with the -listen-on-host 0.0.0.0. Do you know a solution for this?

Thanks in advance.

**Comment by tommysitu** [comment]
Hi @invoicesharing-developers, have you tried this: 
```
$ docker pull spectolabs/hoverfly
$ docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest
$ hoverctl status
```
Please make sure you are using the latest hoverfly Docker image. The hoverfly version should be v0.15.1

**Comment by invoicesharing-developers** [comment]
Hi @tommysitu I am using v0.15.1 but is not possible to connect.

I have installed hoverctl in my machine and I am trying to connect to the hoverfly server (docker), both in the same machine. But is not possible the connection from hoverctl to hoverfly.

hoverctl status --> Could not connect to Hoverfly at http://192.168.99.100:8880

I think is a problem with docker.

Docker version 17.09.0-ce, build afdb6d4

Thanks.

**Comment by tommysitu** [comment]
Hi @invoicesharing-developers, `hoverctl status` by default connect to hoverfly admin API on `localhost:8888`. For connecting to other host and port, You can take a look at this tutorial: http://hoverfly.readthedocs.io/en/latest/pages/tutorials/advanced/remotehoverfly/remotehoverfly.html#remotehoverfly

If you can access the admin dashboard which in your case `http://192.168.99.100:8880` on the browser, it means the Hoverfly is already running.

**Comment by bharatiyas** [comment]
Hi,

I am new to hoverfly. I ran the docker image:

$ docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest

I then sshed into the container:

$ docker exec -it xxxxxxxxx bash

I cannot find hoverfly inside the container. I tried:

$ hoverfly -version

but it does not work.

What are the steps I need to follow to run hoverfly in the container?

Thanks,
Sanjay

**Comment by amu007** [comment]
> Hi,
> 
> I am new to hoverfly. I ran the docker image:
> 
> $ docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest
> 
> I then sshed into the container:
> 
> $ docker exec -it xxxxxxxxx bash
> 
> I cannot find hoverfly inside the container. I tried:
> 
> $ hoverfly -version
> 
> but it does not work.
> 
> What are the steps I need to follow to run hoverfly in the container?
> 
> Thanks,
> Sanjay

https://hoverfly.readthedocs.io/en/latest/pages/introduction/downloadinstallation.html

This Docker image does not contain hoverctl. Our recommendation is to have hoverctl on your host machine and then configure hoverctl to use the newly started Hoverfly Docker instance as a new target.

**Comment by tommysitu** [comment]
@amu007 when you use `docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest` to run hoverfly, the proxy should be running on localhost:8500, and admin API on localhost:8888, you can use `hoverctl` to control it on your host machine.
