### ISSUE TITLE
How to set ip for hoverfly?

### ISSUE THREAD

**Issue by karlpokus** [SpectoLabs/hoverfly#693]
Hi!

How do I set hoverfly to listen on something other than loopback like `10.0.0.0/8`? The only config I can find concerns `hoverctl` and it's remotes.

**Comment by tommysitu** [comment]
Hi @karlpokus, you can set hoverfly to listen on a single address only, for example `hoverfly -listen-on-host 10.0.0.1` , or listen to all interfaces: `hoverfly -listen-on-host 0.0.0.0`. I don't think it works with a CIDR block.

**Comment by karlpokus** [comment]
@tommysitu Wonderful! Thank you. I'm gonna try this.

**Comment by karlpokus** [comment]
@tommysitu 

$ hoverfly -listen-on-host 10.0.0.0/8

INFO[2018-02-07T13:44:24+01:00] Listen on specific interface                  host=10.0.0.0/8
INFO[2018-02-07T13:44:24+01:00] Using memory backend                         
INFO[2018-02-07T13:44:24+01:00] Proxy prepared...                             Destination=. Mode=simulate ProxyPort=8500
INFO[2018-02-07T13:44:24+01:00] current proxy configuration                   destination=. mode=simulate port=8500
FATA[2018-02-07T13:44:24+01:00] Failed to start proxy                         error=listen tcp: lookup 10.0.0.0/8: no such host

**Comment by karlpokus** [comment]
`0.0.0.0` works though.

**Comment by tommysitu** [comment]
You are not the first one asking the question. I have added the answer to the "Troubleshooting" section in the docs now.

**Comment by karlpokus** [comment]
@tommysitu Yeah documenting this sounds good. btw: any chance of adding the flag to hoverctl in the future?

**Comment by tommysitu** [comment]
Yes, inconsistent flags between hoverctl and hoverfly is an issue. If you want to do some Go, feel free to send us a PR.

**Comment by karlpokus** [comment]
@tommysitu I'd be happy to contribute. Let me see if I can find a spot. Regardless - thanks for the swift reply. Really like working with hoverfly.

**Comment by benjih** [comment]
The inclusion of the `listen-on-host` flag has been merged in via #705 and is now awaiting release.

**Comment by karlpokus** [comment]
@benjih Excellent news! Thank you 😃
