### ISSUE TITLE
New Diff mode for comparing response from real service with simulation config

### ISSUE THREAD

**Issue by MatousJobanek** [SpectoLabs/hoverfly#699]
It would be good to have a mode for calling external service and comparing response with currently stored simulation to detect differences between our version and what is the current service response. 

Hoverfly would call the real service and would load matching simulation config. When the service responds then it would compare the response with the simulation (if it is present) and create diff report. Hoverfly then would return the real response to the client and store the diff report. From the test, it should be possible to get all diff reports stored from the last time with all differences.

The communication flow would look like:
```
 test                client       hoverfly              service
invoke client ----->  |              |                     |
  |              send request ---->  |                     |
  |                   |          resend request   ---->    |
  |                   |          and find simulation     process
  |                   |              |           <-----  response
  |                   |          receive response          |
  |                   |          and compare               |
  |                   |   <---resend real response---      |
get comparison results  ---------->  |                     |
  |   <-------------------------   return diff             |
fail or passs                        |                     |
```
WDYT? Is it something that would make sense in the sense of the Hovefly project?

I have already started working on it and I have some implementation for both hoverfly and hoverfly-java projects. I'll send my implementation proposal as a PR probably tomorrow.

**Comment by tommysitu** [comment]
I think this is a fantastic idea! One problem with using a simulation is that the data could be out of sync with the real service over time, and using diff mode would reveal if the simulation is still faithful. 

I will try to review your PR this week.

**Comment by danielbryantuk** [comment]
I think the idea sounds awesome -- funnily enough, in both of the Hoverfly workshops that @mogronalol and I ran over the last two weeks people asked about this!

**Comment by mogronalol** [comment]
Just noticed this, and it is indeed a great idea!
