### ISSUE TITLE
hoverctl not loading config.yaml on first start

### ISSUE THREAD

**Issue by jrtaisto** [SpectoLabs/hoverfly#704]
ENV:
OS:  CentOS 7
Running as non-root account

Version:

hoverfly@localhost ~> hoverctl version

+----------+----------+
| hoverctl |          |
| hoverfly | v0.15.1  |
+----------+----------+

Conditions:  Install bits for hoverfly, use pre-configured .hoverfly/config.yaml, and do the following:

hoverfly@localhost ~> hoverctl status
Could not connect to Hoverfly at localhost:8888

hoverfly@localhost ~> cat .hoverfly/config.yaml
default: local
targets:
  local:
    name: local
    host: localhost
    admin.port: 8888
    proxy.port: 8500
    authenabled: false
    username: "test"
    password: "test123"

1) First command run with environment setup.

hoverfly@localhost ~> hoverctl config
/home/hoverfly/.hoverfly/config.yaml
default: local
targets:
  local:
    name: local
    host: localhost
    admin.port: 8888
    proxy.port: 8500
    authenabled: false
    username: "test"
    password: "test123"

The above is expected.  Put in a default username password but haven't enabled auth yet.

2) Verify that nothing is running.

hoverfly@localhost ~> hoverctl status
Could not connect to Hoverfly at localhost:8888

3) Check your configuration again.

hoverfly@localhost ~> hoverctl config
/home/hoverfly/.hoverfly/config.yaml
default: local
targets:
  local:
    name: local
    host: localhost
    admin.port: 8888
    proxy.port: 8500
    authenabled: false
    username: ""
    password: ""

Yikes!!  Why the clean slate?  I didn't use hoverctl or hoverfly to modify the local config, but yet it changed.  It seems to do the same thing no matter what you do pertaining to hoverctl start|status|stop which doesn't make any sense.  The config.yaml should be persistent and should only change if you're locally changing things with hoverctl/hoverfly or if you're managing this instance remotely via hoverctl.

**Comment by tommysitu** [comment]
hoverctl is loading config.yaml fine. I think the bug is to do with hoverctl remove the username and password if auth is disabled.

**Comment by jrtaisto** [comment]
Tommy,

   Correct, it loads the config.yaml from the file if you do the config
before starting things up or doing a status.  However, it wipes things out
when it starts up or does a status, which it shouldn't do.  I don't think
the auth being enabled or disabled matters to wiping it out; however, it
does seem to reset it to disabled, i.e., false.

hoverfly@localhost ~/.hoverfly> hoverctl config
/opt/QL/app/hoverfly/.hoverfly/config.yaml
default: local
targets:
  local:
    name: local
    host: localhost
    admin.port: 8888
    proxy.port: 8500
    authenabled: true
    username: "test"
    password: "t3stm3!"

hoverfly@localhost ~/.hoverfly> hoverctl status
Could not connect to Hoverfly at localhost:8888

hoverfly@localhost ~/.hoverfly> hoverctl config
/opt/QL/app/hoverfly/.hoverfly/config.yaml
default: local
targets:
  local:
    name: local
    host: localhost
    admin.port: 8888
    proxy.port: 8500
    authenabled: false
    username: ""
    password: ""
hoverfly@localhost ~/.hoverfly>

**Comment by tommysitu** [comment]
@jrtaisto thank you for reporting this issue. It was caused by hoverctl resetting optional fields when parsing the config file. Sorted in the upcoming RC.
