### ISSUE TITLE
How To Make Hoverfly To Listen to Specific Host And Port

### ISSUE THREAD

**Issue by cypress18** [SpectoLabs/hoverfly#716]
I want to tell Hoverfly to listen to specific host and port.   I tried the command below and got errors.
Any suggestions?

Thanks.

hoverfly_bundle_windows_amd64>hoverfly.exe -tls-verification=false -listen-on-host 10.0.96.92:80
[34mINFO[0m[2018-03-19T16:31:23-05:00] Listen on specific interface                  [34mhost[0m=10.0.96.92:80
[34mINFO[0m[2018-03-19T16:31:23-05:00] TLS certificate verification has been disabled
[34mINFO[0m[2018-03-19T16:31:23-05:00] Using memory backend
[34mINFO[0m[2018-03-19T16:31:23-05:00] Proxy prepared...                             [34mDestination[0m=. [34mMode[0m=simulate [34mProxyPort[0m=8500
[34mINFO[0m[2018-03-19T16:31:23-05:00] current proxy configuration                   [34mdestination[0m=. [34mmode[0m=simulate [34mport[0m=8500
[31mFATA[0m[2018-03-19T16:31:23-05:00] Failed to start proxy                         [31merror[0m=listen tcp: address 10.0.96.92:80:8500: too many colons in address

**Comment by tommysitu** [comment]
I think you need to run this: `hoverfly.exe -tls-verification=false -listen-on-host 10.0.96.92 -pp 80`. 
You can run `hoverfly.exe --help` to see all the available flags.

**Comment by cypress18** [comment]
Thanks for your quick reply.  -pp does not seem to be working for me.  I tried and got different error. I think -pp is to run hoverfly proxy on different port other than port 8500.  It's not for hoverfly to listen on specific host port.

./hoverfly -tls-verification=false -capture -listen-on-host 10.16.28.254 -pp 80
INFO[2018-03-19T21:46:18Z] Default proxy port has been overwritten       port=80
INFO[2018-03-19T21:46:18Z] Listen on specific interface                  host=10.16.28.254
INFO[2018-03-19T21:46:18Z] TLS certificate verification has been disabled
INFO[2018-03-19T21:46:18Z] Using memory backend
INFO[2018-03-19T21:46:18Z] Proxy prepared...                             Destination=. Mode=capture ProxyPort=80
INFO[2018-03-19T21:46:18Z] current proxy configuration                   destination=. mode=capture port=80
FATA[2018-03-19T21:46:18Z] Failed to start proxy                         error=listen tcp 10.16.28.254:80: bind: address already in use

**Comment by tommysitu** [comment]
Have you tried using a different port? I hope you have got it working already. As it doesn't look like it's a bug, I am closing this now.
