### ISSUE TITLE
Working with the repository is very slow

### ISSUE THREAD

**Issue by ia3andy** [SpectoLabs/hoverfly#719]
Working with the repository is very slow. It seems it is because of the heavy hoverfly binaries which are in the sources. 

It may be a good idea if this is possible to make the download part of the build process.

**Comment by tommysitu** [comment]
@ia3andy you meant cloning Hoverfly-Java repo is slow? I noticed that the Hoverfly binaries' size has gone up. What were you suggesting?

**Comment by ia3andy** [comment]
@tommysitu Yes I meant cloning, or fetching when the binaries are updated.

I don't have any concrete solution in mind. My first guess (and I don't know if it is possible) was to remove the binaries and to add a download phase to the gradle build (with a specific version of hoverfly).

**Comment by tommysitu** [comment]
@ia3andy that's a good idea. I can remove the binaries from git history as well, I think that would help.

**Comment by tommysitu** [comment]
This is now moved to https://github.com/SpectoLabs/hoverfly-java/issues/166
