### ISSUE TITLE
xmlMatch with Current Date field.

### ISSUE THREAD

**Issue by mhmohapatra** [SpectoLabs/hoverfly#720]
I have a SOAP request which has current date field, xml macther is failing because there is no way to simulate that scenario. Client application is setting the current date for that field which is different from the value hardcoded in the simulation.

**Comment by tommysitu** [comment]
It's possible to use helper method to generate current date time in the response (http://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/templating/templating.html#helper-methods), but not yet in the request as described in your use case.

**Comment by mhmohapatra** [comment]
Is it possible to add some regular expression for individual nodes of the
xmlMatch, that will be very much helpful in these kind of scenarios.

**Comment by tommysitu** [comment]
`xmlMatch` doesn't support matching by regex, how about trying `xpathMatch` and date time operators https://www.w3.org/TR/xpath-functions-31/#func-date-less-than

**Comment by mhmohapatra** [comment]
xpathMatch is not working at all in my case, I validated the xml using a xpath tester and the xpath expression works fine, the same expression is not able to match anything in hoverfly.

**Comment by tommysitu** [comment]
Could you share your xpath expression and a sample of the xml you want to match? That would help debugging the problem.

**Comment by JohnFDavenport** [comment]
I've seen examples like this when using date data for events in the near future. However, you may also need to adjust dates in the response as well and they may need computing. Not difficult in principle, but we need an example to understand what the problems are.

**Comment by JohnFDavenport** [comment]
No further info supplied so closing this for the time-being
