### ISSUE TITLE
hoverfly unable to forward https://[ipv6%interface] URI

### ISSUE THREAD

**Issue by Wwang77433** [SpectoLabs/hoverfly#740]
I send a CURL command to an endpoint IPv6 link local address on a Linux box and hoverfly is not able to forward a request.  It seems like hoverfly is having problem working with the %bond (percent network interface).  How can I work around this issue?

Here's my CURL command:
curl -k https://[fe80:0:0:0:9af2:b3ff:fe22:559c%bond0]/ --proxy localhost:8500

Hoverfly console output:
ERRO[2018-06-08T16:22:46Z] There was an error when forwarding the request to the intended desintation  error=Get https://[fe80:0:0:0:9af2:b3ff:fe22:559c]/: dial tcp [fe80::9af2:b3ff:fe22:559c]:443: connect: invalid argument mode=capture request=&map[body: method:GET scheme:https destination:[fe80:0:0:0:9af2:b3ff:fe22:559c] path:/ query:map[] headers:map[User-Agent:[curl/7.54.1] Accept:[*/*]]] response=&map[error:nil response]

Thanks

**Comment by Wwang77433** [comment]
bond0 is a network interface on a Centos Linux system.  %bond0 is a scope identifier for iPV6 link local address.

**Comment by JohnFDavenport** [comment]
Lacking enough information, so closing. The issue can be reopened if some relevant diagnostic information is provided.
