### ISSUE TITLE
[Templating] iso8601DateTime timezone

### ISSUE THREAD

**Issue by szarlatan** [SpectoLabs/hoverfly#754]
Hey,

I'm working on templating parts of my captured responses. In docs you mention `{{ iso8601DateTime }}` template and give an example that this will give current local time with timezone indicated
```
The current date, formatted in iso8601 | {{ iso8601DateTime }} | 2006-01-02T15:04:05Z07:00
```

Is there any flag needed? If I just use the template it gives me an output of UTC, e.g.  @`2018-07-13T07:58:33Z`. Am I doing something wrong, or it's rather outdated or misleading docs and the template can return UTC dateTime only?

Best Regards,
Kris.

**Comment by tommysitu** [comment]
Hi @szarlatan, it only returns UTC datetime at the moment.

**Comment by szarlatan** [comment]
Good to know @tommysitu 

Can you update the example for now, not to stay misleading as it is currently?

BR,
Kris.

**Comment by tommysitu** [comment]
@szarlatan thank you for pointing that out. Just pushed a fix for the doc.
