### ISSUE TITLE
add support for validate mode

### ISSUE THREAD

**Issue by yagnik** [SpectoLabs/hoverfly#757]
What are your thoughts on adding a "validate mode". 
The goal would be to re-run simulations and check the response is same as we got. 
Benefits:
- verify that simulations stored are up to date
- verify that api is still correct
- future could potentially build openapi spec out of the simulations

**Comment by JohnFDavenport** [comment]
Hi @yagnik Hoverfly has a diff mode. 

We have recently added Swagger/OpenAPI support to Hoverfly Cloud.

We are thinking of making the diff work alongside Swagger. 

We are looking for feedback from our users so if you wanted to be involved contact me directly.

**Comment by JohnFDavenport** [comment]
Closing issue please reopen if necessary
