### ISSUE TITLE
Matcher Chaining

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#761]
With matcher chaining, one can use JSONPath to get a JSON node, and use other matcher to compare its value. For example: 
```
{
  body: [
    {
      matcher: "jsonpath"
      value: “$.user.id"
      doMatch: {
        matcher: “exact”,
        value: “1"
    }
  ]
}
```
This removes the stress of composing and testing complex  jsonpath/xpath expressions, which may not be supported by the current jsonpath/xpath library hoverfly is using. The matcher will be more readable too.

**Comment by kapishmalik** [comment]
@tommysitu can I take this up?

**Comment by kapishmalik** [comment]
@tommysitu  I am currently working on this request.

**Comment by tommysitu** [comment]
Some work has been done here to allow one level of nesting for the `form` matcher: https://github.com/SpectoLabs/hoverfly/pull/1025 you might find it useful @kapishmalik

**Comment by kapishmalik** [comment]
@tommysitu I was thinking to change return type of all matchers from bool to string, bool...i.e. matchedvalue, ismatched or not so that I keep on iterating till doMatch is null. Whenever the value of matcher returns false, I should return false otherwise true. Hope it makes some sense.
