### ISSUE TITLE
FR: Support using upstream-proxy conditionally

### ISSUE THREAD

**Issue by ohenak** [SpectoLabs/hoverfly#762]
Problem: In my company, the proxy for accessing external world is restricted to only access external websites but not internal. However, there are use cases that we need Hoverfly to be able to access both external and internal websites.

Is there a way to have Hoverfly use the upstream-proxy based on certain condition, something like exclusion list or proxy auto-config (PAC) file?

**Comment by benjih** [comment]
Hey @ohenak,

I am currently in the process of implementing this. It should be available in v0.17.4.

**Comment by tommysitu** [comment]
I believe @benjih has implemented it in v0.17.4
