### ISSUE TITLE
Capture Android app traffic

### ISSUE THREAD

**Issue by pjmartorell** [SpectoLabs/hoverfly#784]
Hi, I have a question regarding the suitability of Hoverfly to capture requests from an Android app. I would like to capture the traffic of an Android app **not owned by me** running on my mobile phone, so I don't know exactly what would be the best setup for this purpose.
I guess I would need to add a proxy on my phone to redirect the traffic of my phone to Hoverfly and from there record all ongoing and outgoing requests. 

Another inconvenient is that the traffic is encrypted using SSL with SSL pinning. I don't know how Hoverfly it's able to record and simulate encrypted data. In the case of simple SSL maybe it's not too complicated but with SSL pinning I guess i'ts much more complicated. 

What is the better way to do that?

Thanks!

**Comment by tommysitu** [comment]
Hi @pjmartorell, you can try configuring the Android system proxy to use a Hoverfly listening on the network where the phone can route to. 

Not sure about SSL pinning, does it mean the app only trust a specific certificate from the server or the other way around?

**Comment by JohnFDavenport** [comment]
@pjmartorell Are neither the app or server in your control?

**Comment by pjmartorell** [comment]
Thanks for your help. No, I don't own neither the app nor the server. For simple SSL I guess Hoverfly is able to record the responses using a self-signed certificate. Adding a proxy would be enough? or should I add the self-signed certificate in my device?

In the case of SSL pinning, as far as I know, the server checks that the app certificate matches with the server certificate, avoiding MITM attacks. One option I am trying is to decompile the app and get rid of the SSL pinning, as I have seen the app is not obfuscated. I don't see any other alternatives.

**Comment by tommysitu** [comment]
Your device needs to trust the hoverfly self-signed certificate. You can find more details about SSL configuration here: https://hoverfly.readthedocs.io/en/latest/pages/tutorials/advanced/configuressl/configuressl.html
