### ISSUE TITLE
How to mount a json file to hoverfly docker container

### ISSUE THREAD

**Issue by xinxinzhao1212** [SpectoLabs/hoverfly#785]
I want to use "sudo docker run -it -p 8888:8888 -p 8500:8500 -v simulation.json:xxxxx spectolabs/hoverfly:latest" to mount a exist json file ,This file is made by "hoverctl" ,I want to mount this file to hoverfly container when it start .but can not find the mount path in container . Or this is the wrong way to do this issue ?

**Comment by xinxinzhao1212** [comment]
This is the full url request 
curl  -k --proxy http://localhost:8500 -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDE3NTA3NzIsImlhdCI6MTU0MTc0NzE3MiwiaXNzIjoiSGl0cm9uIiwic2NvcGUiOlsidHIxZDF1bSIsImRldmJpbmQiXSwidXNlcl9pZCI6ImdpdGh1YjozMjY2ODUxNSJ9.vn_XB-ZRo2qyu0iyq_Oidc7PLMnZg55upj_h1FUUKMSEG2fqgXqWH65ZANJZSmviN-4e57k2IGeVMfTIvq_hckOWFgGmbYNdFcSHJ8__-YstEe33VZ4o7MZswc5uuBetS56xxz_JCRwxZJYKR-ItJIEvmdapRDav0ochJ6Ft8uMGd9SS8kDM7fb_obrPWakEk8xFKyNSaXUoD_RZDjkIw-nWJ0ga8C1ESS4wp0jh6oCas8EaWbj8k0EDMGQSsp8jf-GiYcH_rgtU9wP8RSoRxQQqGQOiAAe0x1bx30q63FcCdy4oqJQ6fblRrLQoaISTsGebJ1GoJ2H4iqiyNmldrCjcpePTXf9RTc2H0R0dtjZPl0Cd7YsT9uzh1U5ZDA692EZwgI1AxCwsWtA-wqbiVFc4pY3VVOx64yGOp4dtcHpYQVVVlV0re9xHO2Ww-fI1ocmUyTAvJvgT4HkosY5TDG1hq-aQ5RhNA5tlYeHGzqEDMVMO3JqGe6bKnkYbnWgIydZWl_M-Ll6s_V8U-9ZIV6gJhJ8uL4mjxdYg0vG5MJurtn5iZs9U_XUfsrDXCOeIEjBFCwMYhg_tn9GxiJtMjEGhhcGKqUpEW6QPQKwSuyAaHodaeeWgWc1k-PsAkgAhugUOFaKst5ev9n5mu8UFDLk7vRG7uVq5naeodKPUFgw" -H "apikey: vRlXrdcLcME6yWtZKG6ug5BpC6vYmCCr" http://172.17.0.2:8888/api/v1/jwt/validate
Hoverfly Error!

There was an error when matching

**Comment by xinxinzhao1212** [comment]
and i can get the test url get from hoverfly

hun@hun16:~/hoverfly$ curl  -k -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDE3NTA3NzIsImlhdCI6MTU0MTc0NzE3MiwiaXNzIjoiSGl0cm9uIiwic2NvcGUiOlsidHIxZDF1bSIsImRldmJpbmQiXSwidXNlcl9pZCI6ImdpdGh1YjozMjY2ODUxNSJ9.vn_XB-ZRo2qyu0iyq_Oidc7PLMnZg55upj_h1FUUKMSEG2fqgXqWH65ZANJZSmviN-4e57k2IGeVMfTIvq_hckOWFgGmbYNdFcSHJ8__-YstEe33VZ4o7MZswc5uuBetS56xxz_JCRwxZJYKR-ItJIEvmdapRDav0ochJ6Ft8uMGd9SS8kDM7fb_obrPWakEk8xFKyNSaXUoD_RZDjkIw-nWJ0ga8C1ESS4wp0jh6oCas8EaWbj8k0EDMGQSsp8jf-GiYcH_rgtU9wP8RSoRxQQqGQOiAAe0x1bx30q63FcCdy4oqJQ6fblRrLQoaISTsGebJ1GoJ2H4iqiyNmldrCjcpePTXf9RTc2H0R0dtjZPl0Cd7YsT9uzh1U5ZDA692EZwgI1AxCwsWtA-wqbiVFc4pY3VVOx64yGOp4dtcHpYQVVVlV0re9xHO2Ww-fI1ocmUyTAvJvgT4HkosY5TDG1hq-aQ5RhNA5tlYeHGzqEDMVMO3JqGe6bKnkYbnWgIydZWl_M-Ll6s_V8U-9ZIV6gJhJ8uL4mjxdYg0vG5MJurtn5iZs9U_XUfsrDXCOeIEjBFCwMYhg_tn9GxiJtMjEGhhcGKqUpEW6QPQKwSuyAaHodaeeWgWc1k-PsAkgAhugUOFaKst5ev9n5mu8UFDLk7vRG7uVq5naeodKPUFgw" -H "apikey: vRlXrdcLcME6yWtZKG6ug5BpC6vYmCCr" http://172.17.0.2:8888/api/v2/simulation
{"data":{"pairs":[],"globalActions":{"delays":[]}},"meta":{"schemaVersion":"v5","hoverflyVersion":"v0.17.7","timeExported":"2018-11-20T03:12:26Z"}}

**Comment by tommysitu** [comment]
You just need to add the import argument to import from the mounted file: 

  " sudo docker run -it -p 8888:8888 -p 8500:8500 -v {full path to the simulation file}:/var/hoverfly/simulation.json  spectolabs/hoverfly:latest -import /var/hoverfly/simulation.json"

In fact you can use all the flags available for hoverfly (see hoverfly --help) when you start the hoverfly container.

**Comment by xinxinzhao1212** [comment]
thank you ,it resolve my problem .closed.
