### ISSUE TITLE
Hoverfly doen't support different mode for different services

### ISSUE THREAD

**Issue by agnibrata86** [SpectoLabs/hoverfly#791]
I understand for centralized infrastructure, we can have one hoverfly for each instance, but it won't work for the federated model like somebody wants create an infra for their own set of services in cloud as it will incur cost. And also if you want to try the setup locally it will difficult to achieve.

**Comment by JohnFDavenport** [comment]
If I understand you, you do not want to run multiple services *yourself* as it would incur cost? 

If that is correct. What would be the specific change you need to Hoverfly to help you achieve this?

**Comment by JohnFDavenport** [comment]
Closing as more information is needed. Rather than reopen please use the new template .
