### ISSUE TITLE
Multi-Value Query Params: Hoverfly fails to replay captured request

### ISSUE THREAD

**Issue by mmichaelis** [SpectoLabs/hoverfly#792]
I am using `hoverfly-java` and `hoverfly-java-junit5` 0.11.1 to capture and replay requests to Solr. Solr uses multi-value query parameters for the "Filter Query (fq)" parameter: [Common Query Parameters | Apache Solr Reference Guide 7.6][REF1]

Unfortunately using a captured session for simulation fails to match this parameter.

The parameter is captured as:

```
"fq" : [ {
  "matcher" : "exact",
  "value" : "+feederstate:SUCCESS&-folderpath:5&groups:(0)"
} ],
```

On simulation Hoverfly fails to match but correctly detected that we have an array parameter here as provided in the error message _The following request was made, but was not matched by Hoverfly_:

```
"fq": [
    "+feederstate:SUCCESS",
     "-folderpath:5",
    "groups:(0)"
],
```

From what I understand a possible solution has been discussed in #569 but from the discussion I cannot derive if the suggestions made it into Hoverfly or not.

Is it a bug? Do I miss a configuration option? And if it is a bug: Is there a workaround like manually adapting the captured requests/matchers?

[REF1]: <https://lucene.apache.org/solr/guide/7_6/common-query-parameters.html> "Common Query Parameters | Apache Solr Reference Guide 7.6 (visited: 1/10/2019)"

**Comment by mmichaelis** [comment]
For JUnit 5 I have found a workaround which weakens the match a little, but it is sufficient for us. It makes use of the fact that `hoverfly-java` does not use immutable list in the `Simulation` instance: We just go through all request-response-pairs and in any matcher containing ampersands as value, we replace the ampersands by asterisks and change the matcher type to `glob` rather than `exact`:

```java
private static ObjectWriter OBJECT_WRITER = new ObjectMapper().writerFor(Simulation.class);

@BeforeEach
void setUp(Hoverfly hoverfly) throws JsonProcessingException {
  Simulation simulation = hoverfly.getSimulation();
  Set<RequestResponsePair> pairs = simulation.getHoverflyData().getPairs();
  for (RequestResponsePair pair : pairs) {
    Request request = pair.getRequest();
    Map<String, List<RequestFieldMatcher>> query = request.getQuery();
    for (List<RequestFieldMatcher> matchers : query.values()) {
      // From Debugging we know, that the list is mutable. Thus, it is
      // possible to replace some of the entries.
      for (int i = 0; i < matchers.size(); i++) {
        RequestFieldMatcher<?> matcher = matchers.get(i);
        Object value = matcher.getValue();
        if (value instanceof String) {
          String stringValue = (String) value;
          if (((String) value).contains("&")) {
            RequestFieldMatcher<String> workaroundMatcher = new RequestFieldMatcher<>(RequestFieldMatcher.MatcherType.GLOB, stringValue.replace('&', '*'));
            matchers.set(i, workaroundMatcher);
          }
        }
      }
    }
  }
  String simulationString = OBJECT_WRITER.writeValueAsString(simulation);
  // In order to activate the new Simulation, we need to initialize Hoverfly
  // a second time (first time is done in HoverflyExtension/HoverflyUtils already).
  hoverfly.simulate(() -> simulationString);
}
```

**Comment by tommysitu** [comment]
I was wrong about the encoding of the ampersands. This issue is causing by the Matcher joining multi-values by semi-colon rather than an ampersand, so matching the string exactly will fail.

**Comment by tommysitu** [comment]
PR https://github.com/SpectoLabs/hoverfly/pull/794 should fix the bug. 

Unfortunately you will need to re-capture the simulations in order to produce the following exact matcher with the correct stringify array: 
```
"fq" : [ {
  "matcher" : "exact",
  "value" : "+feederstate:SUCCESS;-folderpath:5;groups:(0)"
} ],
```
It will only affect simulation that has multi-value query matcher.
