### ISSUE TITLE
Need to specify protocol for Docker

### ISSUE THREAD

**Issue by jdgarciar** [SpectoLabs/hoverfly#801]
## Could not connect to Hoverfly at hoverfly:8888
Hi. I like Docker so I'm running Hoverfly as a container:
```
docker run --name hoverfly --network mynet -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest
```
And..., I have another container to develop my application (I prefer to have Node.js running as a container to develop my applications):
```
docker run --name app --network mynet -v $(pwd):/app -it -p 8080:80 --workdir /app node:10 bash
```

Those containers are in the same network `mynet` so I have `hoverctl` in my second container to access remotely to `hoverfly` which is running as a container, too. But, when I'm trying to execute a command like `hoverctl mode capture` I'm getting this response:
```
Could not connect to Hoverfly at hoverfly:8888
```

I configured the remote host by `hoverctl` in the second container.
```
hoverctl targets create remote --host hoverfly --admin-port 8888 --proxy-port 8500
hoverctl targets default remote
hoverctl mode capture
```

```
Could not connect to Hoverfly at hoverfly:8888
```

¿Why is it happening?
```
docker top hoverfly
```

```
/go/bin/hoverfly -listen-on-host=0.0.0.0
```

I saw in the documentation the flag `-listen-on-host` could help me but it isn't working.
If I try to connect to `hoverfly` from my `localhost` I can do it, I have a connection, but between containers it isn't working.

**Comment by jdgarciar** [comment]
And between those containers I can do it: from the second container `ping hoverfly` and I have a response. From the container `hoverfly` I do `ping app` and I have a response, so, ¿why the second container can't request the container `hoverfly` by `hoverctl`?

**Comment by jdgarciar** [comment]
I have the solution..., it's really important to add the protocol `http` to the `host` when you are adding an IP address or some alias because Docker doesn't resolve it adding `http` before the address, it only adds the docker container ID so, there isn't any specified protocol at the request.

**Comment by jdgarciar** [comment]
I think `hoverctl` doesn't add automatically the procotol to the host when the address doesn't have a DNS which resolves it.

**Comment by JohnFDavenport** [comment]
Maybe this is a documentation issue. So reopening it.

**Comment by JohnFDavenport** [comment]
If there's a better title, change it. Thanks @jdgarciar for pointing this out as others will come across this problem.

**Comment by tommysitu** [comment]
It could be a bug actually: https://github.com/SpectoLabs/hoverfly/blob/master/hoverctl/wrapper/hoverfly.go#L169

When no protocol is specified, and it's not localhost, hoverfly tries to use `https`

**Comment by tommysitu** [comment]
@jdgarciar Just want to confirm with you, you got it to work by adding `http:\\` to the host flag?
`hoverctl targets create remote --host http://hoverfly --admin-port 8888 --proxy-port 8500`

**Comment by jdgarciar** [comment]
@JohnFDavenport, @tommysitu  :) 👍

**Comment by jdgarciar** [comment]
@tommysitu as you said. It worked for me adding the `--host http:\\hoverfly`.

**Comment by tommysitu** [comment]
v1.0.0-rc.2 had a fix for this issue.
