### ISSUE TITLE
How can I install hoverfly as windows service or install to iis

### ISSUE THREAD

**Issue by BilgehanYildiz** [SpectoLabs/hoverfly#809]
Hi I am new at hoverfly and I am looking for some information

I download hoverfly windows setup.But I am little bit confused

when I use to hoverctl  start and this time hoverfly start to work on the fly but when I close command line it goes down

Is it possible to install hoverfly like windows service or install to iis.So when machine is shutdown or closed it can be automatically start.

Thank

**Comment by JohnFDavenport** [comment]
@BilgehanYildiz This may just be down to how Windows works. This forum discussion might give you some ideas on how to fix the problem: https://serverfault.com/questions/39451/there-is-any-way-to-run-processes-in-the-background-in-windows-nohup-equivalent

**Comment by BilgehanYildiz** [comment]
When command prompt is closed all gone?What I want to ask is there any out of the box solution about that to install hoverfly windows server

**Comment by JohnFDavenport** [comment]
No there isn't
