### ISSUE TITLE
Capture and listen specific url (not given all api path)

### ISSUE THREAD

**Issue by BilgehanYildiz** [SpectoLabs/hoverfly#811]
Hi I can capture and simulate hoverfly in capture mode

Is it possible to hoverfly can listen my site request and capture all of them

like there is a lot api in my site and I want to do that listen all request to coming my site and capture that

Or only we can do for each spefic api ,like curl --proxy http://localhost:8500 'http://myrestapisite/Person/1 exetute with curl and capture them one by one?

Is there any easy way to capture all request for specific uri

cmd-->hoverctl mode capture
curl --proxy http://localhost:8500 'http://myrestapisite/Person/1
cmd-->hoverctl export simulation.json
cmd-->hoverctl stop

**Comment by tommysitu** [comment]
Depends on how you made your requests. If you made your requests via a browser, you can set your browser to use Hoverfly as a proxy. Then all the requests will be intercepted and captured. I would suggest you to have a look at the docs regarding proxy server:https://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/proxyserver.html

**Comment by BilgehanYildiz** [comment]
Actually I want to ask is there a way to attach specific url in any browser.In this scenario only my browsers will be captured what I want to try anycoming request to myapi can be listened?

**Comment by JohnFDavenport** [comment]
@BilgehanYildiz  Hoverfly is designed for that. It's best to try it. Please you use the gitter channel to ask questions as creating issues for simple questions creates clutter and wastes our time.

Closing this as it's neither a feature request or a bug.
