### ISSUE TITLE
Allow responses being read from a file instead of having to write them in the simulation JSON

### ISSUE THREAD

**Issue by BrainStone** [SpectoLabs/hoverfly#815]
**Is your feature request related to a problem? Please describe.**
Currently when running a simulation you have to specify the response bodies in the simulation JSON directly. This makes formats that use double quotes or new lines (like JSON) pretty much unreadable. And when using binary formats like images, it's essentially impossible to know which image is which without converting the base64 encoded image back first.  
Additionally having the response body in the simulation JSON can really blow up the file size.

**Describe the solution you'd like**
I think parallel to the `body` property, there should be a `bodyFile` property where you can specify a file from which the body can be read from. Relative paths should be relative to the simulation JSON file itself.

This might also allow to lazily load large files to improve general performance. As it may make sense to create a large set of response definitions in one file, but not all responses are requested and therefore not all response bodies would need to be loaded into memory.

**Describe alternatives you've considered**
One alternative that has been pointed out is using middleware. Though I think it's really way over the top to essentially write a small program to solve such a trivial and potentially common problem. Additionally you always run into the issue of platform dependence when using such a solution.  
If there was a premade, complete and platform independent script/program that loads responses from files, while still allowing direct response bodies in the simulation JSON, then that would be acceptable too, though I really think it would be benefitial to have that feature built in Hoverfly itself directly

**Comment by JohnFDavenport** [comment]
Makes sense as JSON is difficult to work with and the bodies would be separately managed

**Comment by crorodriguezro** [comment]
Hi, any update on this?

**Comment by tommysitu** [comment]
Please try this out in [v1.3.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v1.3.0) It might need some more refinement.
