### ISSUE TITLE
want to check the status of real service

### ISSUE THREAD

**Issue by antika08** [SpectoLabs/hoverfly#821]
First want to check the status of real service if service is up then hoverfly should be goes into capture mode but status of real service is down then hoverfly should be goes into simulation mode  how can we do this.

**Comment by JohnFDavenport** [comment]
@antika08
I have some questions:

1. Is the real service a production service?
2. How long is capturing going to continue if the real service is responding fine?
3. Should Hoverfly discard data after a certain period of time?
4. Hoverfly should wait for the real service in capture mode. How long should it wait?
5. Does Hoverfly try again on the next request if there is no response if the last one timed out (note that in this circumstance Hoverfly will appear to be as slow as your timeout)?
6. Instead of that, does Hoverfly declare the real service down and respond immediately?
7. How does Hoverfly know that the real service has come back? Is Hoverfly continually trying the real service perhaps?

**Comment by JohnFDavenport** [comment]
@antika08

I suppose my real question is why doesn't [Squid](http://www.squid-cache.org/) do what you want?

**Comment by antika08** [comment]
Sorry I don't understand about squid.

**Comment by antika08** [comment]
I will share the answers for below questions with you  tomorrow

Thanks,
Antika Chauhan

**Comment by antika08** [comment]
Hi John,

**Comment by antika08** [comment]
Please find below details of questions with highlighted answers:

    1. Is the real service a production service?  
Ans: -- Real service is not a
    production service.
    2. How long is capturing going to continue if the real service is
    responding fine?
 Ans :-  if real service is responding fine then on first
    time hoverfly should capture the response in simulation file and after that
    its gives real response till service is up.
    3. Should Hoverfly discard data after a certain period of time?
Ans:-- At
    the first successful response of the day, it should capture the response
    through hoverfly then Hoverfly should discard the previous recorded data.
    4. Hoverfly should wait for the real service in capture mode. How long
    should it wait? 
Ans :-- Wait time should be configurable from our end as
    different services have different wait time.
    5. Does Hoverfly try again on the next request if there is no response
    if the last one timed out (note that in this circumstance Hoverfly will
    appear to be as slow as your timeout)? 
Ans :- if service is down then first
    hoverfly should declare that this service is down and goes into simulation
    mode
    6. Instead of that, does Hoverfly declare the real service down and
    respond immediately? 
Ans :-- Hoverfly should declare the service down and
    goes into simulation mode.
    7. How does Hoverfly know that the real service has come back? Is
    Hoverfly continually trying the real service perhaps? 
Ans :-- Whenever we
    execute the test cases, if service is up, request should go to main
    application/service and hoverfly should also capture the response at that
    time, and if service is down then hoverfly should go into simulation mode.

Please help me this is very urgent for me.

**Comment by JohnFDavenport** [comment]
@antika08 If you want SpectoLabs to divert effort to this contact me directly

**Comment by antika08** [comment]
John, can you please share your email id so that I can contact you directly

**Comment by JohnFDavenport** [comment]
It's on my @JohnFDavenport profile

**Comment by antika08** [comment]
John, we want that hoverfly-java should check the status of real service if service is up then hoverfly- Java should be goes into capture mode but status of real service is down then hoverfly-java should be goes into simulation mode how can we do this.

**Comment by antika08** [comment]
Please help us. It's very urgent for us

**Comment by JohnFDavenport** [comment]
@antika08 it wasn't clear that you are using Hoverfly-Java. Given you are prepared to check the status of the service before you start the test. If the service is not available you can use the last good capture for your simulation.

In your test you can check your service health and change the mode based on the results. The hoverfly API provides methods to interact with the Hoverfly proxy: 

`setMode();`
`simulate();`
`exportSimulation();`

**Comment by antika08** [comment]
Please share some example with me so that I can understand this

**Comment by antika08** [comment]
Hi John,

Please help me to find the example for hoverfly-java for checking the
status of service and change mode accordingly.

This is very urgent for me.


Thanks and regards,
Antika

**Comment by JohnFDavenport** [comment]
@antika08 what you are asking for support that is in excess of what anyone can reasonably expect from an open source project. Whilst we have been helpful to continue to do so free of charge would mean diverting limited resources away from the wider community SpectoLabs seeks to serve. If your company would like to enter into a commercial support arrangement with SpectoLabs please get in contact with myself. My email is on my profile page. Alternatively use the SpectoLabs [contact form](https://specto.io/support/).
