### ISSUE TITLE
Wrongful Matching Requests

### ISSUE THREAD

**Issue by Navdit** [SpectoLabs/hoverfly#825]
## Description of the bug
If I use regex in the request matcher, Hoverfly gives the first match request from the bottom. Even though the requests are different.

Eg: 

## Context information (for bug reports)
Had two requests, differing slightly. Hoverfly responds with the same response.

## Steps to reproduce the issue

1. hoverctl start webserver
2. hoverctl mode simulate
3. hoverctl import dummy_stub.json (as shown below)
4. Hit any request, you will get response of request 2.

```
{
    "data": {
        "pairs": [
            {
                "request": {
                    "path": [
                        {
                            "matcher": "regex",
                            "value": "/super/api/member/v1/plans/C[DQ]/members/([0-9]+)/accountBalances/current"
                        }
                    ],
                    "method": [
                        {
                            "matcher": "exact",
                            "value": "GET"
                        }
                    ],
                    "destination": [
                        {
                            "matcher": "exact",
                            "value": "dummy"
                        }
                    ],
                    "scheme": [
                        {
                            "matcher": "exact",
                            "value": "https"
                        }
                    ]
                },
                "response": {
                    "status": 200,
                    "body": "{\"message_1\":\"Ok\"}",
                    "encodedBody": false,
                    "headers": {
                        "Cache-Control": [
                            "private"
                        ],
                        "Connection": [
                            "close"
                        ],
                        "Content-Type": [
                            "application/json; charset=utf-8"
                        ],
                        "Date": [
                            "Fri, 15 Mar 2019 04:06:14 GMT"
                        ],
                        "Hoverfly": [
                            "Was-Here"
                        ],
                        "Transfer-Encoding": [
                            "chunked"
                        ],
                        "X-Aspnet-Version": [
                            "4.0.30319"
                        ],
                        "X-Correlation-Id": [
                            "b0bb7920-46d7-11e9-aaf7-005056a21885"
                        ],
                        "X-Powered-By": [
                            "ASP.NET"
                        ]
                    },
                    "templated": false
                }
            },
            {
                "request": {
                    "path": [
                        {
                            "matcher": "regex",
                            "value": "/super/api/member/v1/plans/CD/members/[0-9]+/accountBalances"
                        }
                    ],
                    "method": [
                        {
                            "matcher": "exact",
                            "value": "GET"
                        }
                    ],
                    "destination": [
                        {
                            "matcher": "exact",
                            "value": "dummy"
                        }
                    ],
                    "scheme": [
                        {
                            "matcher": "exact",
                            "value": "https"
                        }
                    ]
                },
                "response": {
                    "status": 200,
                    "body": "{\"message_2\":\"Ok\"}",
                    "encodedBody": false,
                    "headers": {
                        "Cache-Control": [
                            "private"
                        ],
                        "Connection": [
                            "close"
                        ],
                        "Content-Type": [
                            "application/json; charset=utf-8"
                        ],
                        "Date": [
                            "Fri, 15 Mar 2019 04:06:14 GMT"
                        ],
                        "Hoverfly": [
                            "Was-Here"
                        ],
                        "Transfer-Encoding": [
                            "chunked"
                        ],
                        "X-Aspnet-Version": [
                            "4.0.30319"
                        ],
                        "X-Correlation-Id": [
                            "b144cd60-46d7-11e9-aaf7-005056a21885"
                        ],
                        "X-Powered-By": [
                            "ASP.NET"
                        ]
                    },
                    "templated": false
                }
            } 
        ],
        "globalActions": {
            "delays": [],
            "delaysLogNormal": []
        }
    },
    "meta": {
        "schemaVersion": "v5",
        "hoverflyVersion": "v1.0.0-rc.2",
        "timeExported": "2019-03-15T15:07:12+11:00"
    }
}
```

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
None
```
**If possible, add screenshots to help explain your problem**

```
$ curl http://localhost:8500//super/api/member/v1/plans/CD/members/3199123/accountBalances
{"message_2":"Ok"}
$ curl http://localhost:8500//super/api/member/v1/plans/CD/members/123456/accountBalances/current
{"message_2":"Ok"}
```

### Expected result
Should respond with different results for different requests.

## Additional relevant information
If not indicated above:
1. OS and version: e.g. macOS Mojave, Windows 10, Red Hat Linux, ...
2. Hoverfly version: e.g.0.17.7
3. Tools/Browser you were using
4. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
Really appreciate the details you have provided. 

When you made your request to `http://localhost:8500//super/api/member/v1/plans/CD/members/123456/accountBalances/current` 

The path was matched by both of your regex in Go. So Hoverfly will just pick one of the response and return it.

If you want Hoverfly to match a path without any more path fragments, you should add an end of line symbol like this to make your regex less ambiguous: 
`/super/api/member/v1/plans/CD/members/123456/accountBalances$`

**Comment by Navdit** [comment]
Hey @tommysitu 

Thanks a lot for your prompt reply and help.
First of all my earnest apologies for:

1. Raising such a dumb issue.
2. Replying in so late.

To be honest, I figured it on the day itself but forgot to comment and close the issue here. My bad.

But, I have something to offer. For one of my projects, I had been building a framework sort of thing around hoverfly. The project repo can be found here - https://github.com/Navdit/hoverfly_stub_framework/blob/master/README.md

Please feel free to check out and share your opinion.

**Comment by tommysitu** [comment]
@Navdit Thank you for closing this issue. The project looks interesting. I will try it out and give you feedback as soon as I could.

**Comment by Navdit** [comment]
Thanks, @tommysitu for indulging me.
I am quite a noob when it comes to coding so please bear with my coding skills.

The objective was to provide an out of the box solution, where I could:
1. Run scripts and install hoverfly in Cloud or Linux Based Machines.
2. Restart/Stop Hoverfly stub server using jenkins - so that anybody can use it.
3. Directly convert your postman collection to Hoverfly Stub Config (simulation.json) just by a script.

This framework is good in CI/CD scenarios, where my API collection is changing (maybe params, endpoints, etc)

**Comment by tommysitu** [comment]
Hi @Navdit I've looked at the framework you built. Here's my thought on the Pros and Cons: 

Pros: 
- Making hoverfly available to the team using Jenkins pipeline
- Good for managing Hoverfly lifecycle and configurations (simulation and middleware) 
- Support Postman to Hoverfly conversion
- Customize python functions to pre-processing the simulation file. Hoverfly-Java has a similar feature, but it's for the JUnit tests. 

Cons:
- Missing a summary of the features in README, it's not easy to understand what it does at a glance. 
- There are quite a few steps to set it up, so having a concrete example would be nice.

Suggestions: 
- I wonder if you can automate Step 6, so that main.py can pick up any stub helper functions that are added to a file or folder
- Can Step 7 and 9 be part of the `/start_stub_server.sh`? So basically if you have new configurations, you just need to put them in a folder, and the script takes care of it.
