### ISSUE TITLE
github.com/sirupsen/logrus import is incorrectly cased

### ISSUE THREAD

**Issue by DanielJonesEB** [SpectoLabs/hoverfly#826]
When depending on Hoverfly as a Golang library, it is impossible to use Go Modules as the imports for `github.com/sirupsen/logrus` are incorrectly cased. The repo itself has a lowercase `s`, but the imports in Hoverfly code have an uppercase `S` (`github.com/Sirupsen/logrus`).

This results in `go` complaining:

```
go: github.com/Sirupsen/logrus@v1.4.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

**Comment by tommysitu** [comment]
Will try out Go Module to see if there're any more bugs. Thanks again.

**Comment by DanielJonesEB** [comment]
No worries - I blame Golang! Due to various bugs, I couldn't use modules, dep, or godep, and had to revert to govendor like it was 2015...

**Comment by tommysitu** [comment]
This is fixed. However, Hoverfly uses `dep` to manage dependencies, I don't think go mod could understand the constraints defined in the dep specific lock file. For example, Hoverfly requires v2.7.0 of [jwt-go](https://github.com/dgrijalva/jwt-go), but go mode pulls in the latest version which is not compatible with Hoverfly.
