### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by aosavitski** [SpectoLabs/hoverfly#848]
I have a large export file (~500Mb). Starting hoverfly with "hoverfly -import simulation.json" takes around 2 hours for me:( 
I did a profiling and that what I see in pprof top:

```
      flat  flat%   sum%        cum   cum%
 14.73mins 11.62% 11.62%  91.20mins 71.95%  reflect.deepValueEqual
  7.59mins  5.99% 17.61%   8.91mins  7.03%  runtime.ifaceeq
  7.08mins  5.59% 23.20%  26.54mins 20.94%  runtime.mallocgc
  5.57mins  4.39% 27.59%   5.57mins  4.39%  runtime.memmove
  4.92mins  3.88% 31.47%   8.48mins  6.69%  runtime.strequal
  4.84mins  3.82% 35.29%  12.81mins 10.11%  runtime.mapassign
  4.49mins  3.54% 38.84%   5.84mins  4.61%  runtime.heapBitsSetType
  4.32mins  3.40% 42.24%   9.85mins  7.77%  runtime.scanobject
  4.06mins  3.20% 45.44%   4.06mins  3.20%  reflect.Value.Type
  3.21mins  2.53% 47.98%   3.21mins  2.53%  runtime.memclrNoHeapPointers
```

This lead me to the function AddPair in core/models/simulation.go, that is doing DeepEqual check for each pair adding to the simulation. I think its need to be optimized!
When I add a new function "AddPairWithoutDuplicateCheck" and use it in core/import.go instead "AddPair" then import of the same file took few seconds.

**Comment by tommysitu** [comment]
Can imagine this could happen on simulations with hundreds of pairs and some have a large request body. Maybe Hoverfly can provide an option to import simulation as it is without the `deepEquals` check like what you are already doing.

**Comment by aosavitski** [comment]
Does this check is needed at all during import? Is there a possibility that duplicate requests will be in import file?

**Comment by tommysitu** [comment]
probably not. If the simulation is created by capturing, then it shouldn't contain duplicated pairs. Maybe the default should be not checking for duplication for the sack of performance.

**Comment by tommysitu** [comment]
@aosavitski can you share the benchmark test you used to get the results please? We are getting different cpu profiles, and want to do a comparison.

**Comment by JohnFDavenport** [comment]
As long as Hoverfly matching is unchanged and deterministic, the warning for duplicates should be sufficient. Perhaps expose the existing functionality under a --verify option for those who may tamper with their simulations after Hoverfly has captured and exported them.

**Comment by aosavitski** [comment]
> @aosavitski can you share the benchmark test you used to get the results please? We are getting different cpu profiles, and want to do a comparison.

Here it is:
[cpu.prof.zip](https://github.com/SpectoLabs/hoverfly/files/3317741/cpu.prof.zip)

**Comment by aosavitski** [comment]
Wait, you was asking for test, not a result? Sorry. I was profiling without adding test. It was my first day I was dealing with golang sources, so I added profiling flagin main.go as written [here](https://golang.org/pkg/runtime/pprof/) and just start hoverfly with "-cpuprofile cpu.prof --import simulation.json". 
If you want, I can write a test

**Comment by tommysitu** [comment]
That's good enough. I was just wondering how you got the profile. Thank you!

**Comment by tommysitu** [comment]
@aosavitski I have done some benchmarking with a few large simulation files I've got that represents moderate usage of hoverfly, removing the duplicate check doesn't make much difference, the bottleneck is mainly the JSON encode/decode. Since the performance issue is only noticeable for very heavy usage of Hoverfly with a simulation of thousands of pairs, and removing the duplicate check might be a break changes for some users. I would suggest providing a flag for the user to turn off this check instead. What do you think?

**Comment by aosavitski** [comment]
Variant with flag fine with me.
But was you benchmarking import?
I can if you want provide a simulation file for you (replacing first sencitive data inside), that take hours to import, and seconds if I'm removing DeepEqual check.

here the fix that I'm using localy:
```
diff --git a/core/models/simulation.go b/core/models/simulation.go
index 4c8f1c5..3d9e906 100644
--- a/core/models/simulation.go
+++ b/core/models/simulation.go
@@ -42,6 +42,12 @@
 	return !duplicate
 }
 
+func (this *Simulation) AddPairWithoutDuplicateCheck(pair *RequestMatcherResponsePair) {
+	this.RWMutex.Lock()
+	this.matchingPairs = append(this.matchingPairs, *pair)
+	this.RWMutex.Unlock()
+}
+
 func (this *Simulation) AddPairInSequence(pair *RequestMatcherResponsePair, state *state.State) {
 	var duplicate bool
 
```
```
diff --git a/core/import.go b/core/import.go
index 95fcacf..76c1b3b 100644
--- a/core/import.go
+++ b/core/import.go
@@ -143,15 +143,11 @@
 
 			pair := models.NewRequestMatcherResponsePairFromView(&pairView)
 
-			isAdded := hf.Simulation.AddPair(pair)
-			if isAdded {
-				for k, v := range pair.RequestMatcher.RequiresState {
-					initialStates[k] = v
-				}
-				success++
-			} else {
-				importResult.AddPairIgnoredWarning(i)
+			hf.Simulation.AddPairWithoutDuplicateCheck(pair)
+			for k, v := range pair.RequestMatcher.RequiresState {
+				initialStates[k] = v
 			}
+			success++
 
 			if pairView.RequestMatcher.DeprecatedQuery != nil && len(pairView.RequestMatcher.DeprecatedQuery) != 0 {
 				importResult.AddDeprecatedQueryWarning(i)
```

**Comment by tommysitu** [comment]
I used a benchmark test in this branch: https://github.com/SpectoLabs/hoverfly/tree/fix-slow-import
It tests the import simulation API. It'd be good to have the simulation file so that we can try optimizing the duplicate check. 

The easiest thing to do for now is to add the skip flag. I wonder how you import the simulation. Are you using `hoverfly -import` or `hoverctl import`?

**Comment by aosavitski** [comment]
>I wonder how you import the simulation. Are you using hoverfly -import or hoverctl import?
I am using both ways. When I was creating cpu.prof file, I was using "hoverfly --import"

**Comment by aosavitski** [comment]
Here is the file: https://www.dropbox.com/s/3i0xykzjd5ke5ac/simulation.zip?dl=0
With hoverfly v1.0.1 it was imported ~1.5h for me:
```
/ # hoverfly --import /home/andrei/simulation.json
INFO[2019-07-01T07:29:20Z] Using memory backend
INFO[2019-07-01T08:56:45Z] payloads imported                             failed=0 successful=84468 total=86489
INFO[2019-07-01T08:56:45Z] Proxy prepared...                             Destination=. Mode=simulate ProxyPort=8500
```

With the patch I posted below ~10s:
```
/home/andrei # ./hoverfly --import simulation.json
INFO[2019-07-01T09:04:49Z] Using memory backend
INFO[2019-07-01T09:04:59Z] payloads imported                             failed=0 successful=86489 total=86489
INFO[2019-07-01T09:04:59Z] Proxy prepared...                             Destination=. Mode=simulate ProxyPort=8500
```

**Comment by tommysitu** [comment]
Here is the PR for providing the flag: https://github.com/SpectoLabs/hoverfly/pull/858

**Comment by tommysitu** [comment]
`-no-import-check` flag is available in https://github.com/SpectoLabs/hoverfly/releases/tag/v1.1.0
