### ISSUE TITLE
hoverfly returns ←[36mresponse←[0m="&map[error:nil response]"

### ISSUE THREAD

**Issue by felixvolz** [SpectoLabs/hoverfly#849]
## Description of the bug
I'm using hoverfly as a proxy (windows 64 bit)  on my corporate network
1. when I make a soapui request (to an api on our corporate network) I use hoverflly as the proxy
2. when I make a request (RESTful webservice which enforces basic auth) I get a valid/expected resposne back in soapui
3. when I view the hoverfly logs I see a valid request going through but I see ←[36mresponse←[0m="&map[error:nil response]" where I would expect the response
4. when I export the simulation I see the follwoing

"response": {
					"status": 401,
					"body": "",
					"encodedBody": false,
					"headers": {
						"Content-Type": [
							"text;charset=UTF-8"
						],
						"Date": [
							"Tue, 18 Jun 2019 03:26:12 GMT"
						],
						"Hoverfly": [
							"Was-Here"
						],
						"Server": [
							"none"
						],
						"Set-Cookie": [
							"JSESSIONID=xxx; Path=/xx; Secure"
						],
						"Transfer-Encoding": [
							"chunked"
						],
						"Www-Authenticate": [
							"Basic realm=\"xxx at 1560828373567\""
						]
					},
					"templated": false
				}

## Steps to reproduce the issue
Question: how can I get more verbose logs out of hoverfly. its like its acting as a proxy correctly just not capturing the response somehow

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
(paste here)
```
**If possible, add screenshots to help explain your problem**

## Additional relevant information
1. Hoverfly version:  master-3266 windows_amd64
2. Anything that might help us to diagnose the problem

**Comment by felixvolz** [comment]
My issue above is when I run hoverfly on my corporate network. Ive tried just now (same win64 install) on my home pc with the time.jsontest.com tutorial and hoverfly seems to work fine.

**Comment by tommysitu** [comment]
so Hoverfly can proxy the request fine, but the response being capture is different?  Can you provide some steps to reproduce the problem? Providing the commands you use and the hoverfly logs you got will be helpful.

You can get debug logs from hoverfly:
`$ hoverfly --log-level debug`

**Comment by felixvolz** [comment]
- I think I found my issue (soapui related)
- I was using soapui initially (soapui -> hoverfly as proxy -> some endpoint)
- I had soapui 'pre-emptive auth' as 'use global preference': the consequence of this si the http request is made with no authorization header and if that fails then soapui makes a second request with the authorixation details (i.e. because my endpiont enforces auth then soapui must always make two requests)
- hoverfly was capturing the response to the first request (401 unauth) and ignoring theresposne to the second request (might be a hoverfly matcher feature?)
- when I replay with soapui setting to 'authenticate pre-emptively' then I see hoverfly capture correctly
- when I replay with curl I see no issues

**Comment by tommysitu** [comment]
Glad you've figured it out. If the second request is exactly the same as the first one, then it won't be captured.
