### ISSUE TITLE
Set headers capturing via API

### ISSUE THREAD

**Issue by WouldYouKindly** [SpectoLabs/hoverfly#856]
Hi.

REST API documentation about [PUT /hoverctl/mode](https://hoverfly.readthedocs.io/en/latest/pages/reference/api/api.html#put-api-v2-hoverfly-mode) doesn't mention setting rules for capturing headers. I had to go through source code to figure it out. Would be nice to have it in docs.

Thanks for the great tool!

**Comment by tommysitu** [comment]
Thanks for spotting it. Will fix soon.
