### ISSUE TITLE
Provide a capture mode option to overwrite an existing request

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#862]
**Is your feature request related to a problem? Please describe.**
At the moment, Hoverfly only captures a unique request once, and a repeated request is ignored.
In some cases, you may want to capture the new ones by overwriting the old ones. For example, you import a previously captured simulation, and you want to rerun your test under capture mode to keep your simulation up-to-date.
  
**Describe the solution you'd like**
Provide a capture mode option to enable this feature, something like this: 
```
hoverctl mode capture --overwrite-duplicate
```

**Comment by tommysitu** [comment]
Fixed in [v1.1.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v1.1.1)

**Comment by aosavitski** [comment]
I tested it. Works great. Thanks a lot!
