### ISSUE TITLE
Why not switch to go mod

### ISSUE THREAD

**Issue by unlikezy** [SpectoLabs/hoverfly#870]
I tried to switch this project to go mod, and it's simple enough:
```
go mod init github.com/SpectoLabs/hoverfly
rm -rf vendor
```
and after then everything(compiling/testing/benchmarking) seems work fine.

**Comment by tommysitu** [comment]
@unlikezy that looks good! No more committing vendor files to git. It slightly reduces the size of the hoverfly binary as well.  We will switch to it when it's finalized in Go 1.13

**Comment by tsal** [comment]
We're about to see Go 1.14 finalized; any chance we can see this happen before v1.2?

**Comment by tommysitu** [comment]
I can look into this sooner.

**Comment by tommysitu** [comment]
hoverfly is now on go 1.14 and go mod 🎉
