### ISSUE TITLE
Can enter unsupported modify mode erroneously from Webserver mode 

### ISSUE THREAD

**Issue by nkvp** [SpectoLabs/hoverfly#873]
##  Description of the bug
I am currently unable to find an option for setting default destination for all requests when hoverfly is run as webserver

## Steps to reproduce the issue
hoverctl start webserver
hoverctl mode modify
hoverctl destination google.com
hoverctl status 

hoverctl status                          

+------------+---------------------+
| Hoverfly   | running             |
| Admin port |                8888 |
| Proxy port |                8500 |
| Proxy type | reverse (webserver) |
| Mode       | modify              |
| Middleware | disabled            |
| CORS       | disabled            |
+------------+---------------------+

Do curl http://localhost:8500

### Observed result
ERRO[2019-08-12T12:48:43+05:30] There was an error when forwarding the request to the intended destination  error="Get http://localhost:8500/: EOF" mode=modify request="&map[body: destination:localhost:8500 headers:map[Accept:[*/*] Accept-Encoding:[gzip] User-Agent:[curl/7.54.0]] method:GET path:/ query:map[] scheme:http]" response="&map[error:nil response]"

### Expected result
Request gets sent to http://www.google.com

## Additional relevant information
1. Hoverfly version: 
+----------+---------+
| hoverctl | v1.1.1  |
| hoverfly | v1.1.1  |
+----------+---------+

**Comment by tommysitu** [comment]
The webserver mode doesn't support forward proxying, therefore it only supports simulate. To use modify mode, please start hoverfly with `hoverctl start` without the `webserver` argument. 

Change mode to capture does the webserver checking, but not modify mode, so I realized that's a bug:
```
$ hoverctl mode capture
Could not set mode

Cannot change the mode of Hoverfly to capture when running as a webserver
```

**Comment by JohnFDavenport** [comment]
Given your comment @tommysitu  I've labelled this as a bug and changed the title to make it more appropriate
