### ISSUE TITLE
Fail to execute middleware on multiple Hoverfly targets

### ISSUE THREAD

**Issue by silencexy** [SpectoLabs/hoverfly#876]
Can I launch multiple hoverfly targets which in synthesize mode and running on diffrent ports on a single physical machine? The version v1.1.1
I tried to do this, using the command as following:

Hoverctl targets create mockplan1
Hoverctl start webserver -t mockplan1 --admin-port 8800 --proxy-port 8700
Hoverctl mode synthesize
Hoverctl middleware --binary python --script ./synthetic_flight_search.py

I started a target and set the middleware through the above method. it works when I start only a target.But I found that when starting a new target, the target which was launched previously can not be used normally, the error is shown in the figure.
So I'm wondering if I can launch multiple hoverfly targets on a single physical machine? 
![image](https://user-images.githubusercontent.com/18239275/63506239-b1cdac80-c507-11e9-92e4-2d17023de3d9.png)

**Comment by tommysitu** [comment]
Multiple hoverfly targets can be run on a single machine. This bug is probably related to the `hoverctl middleware` command. It deletes the previous middleware script, and when you use the first target, it complains the file is not found.

**Comment by tommysitu** [comment]
fix released in v1.1.5
