### ISSUE TITLE
SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number for HTTPS APIs

### ISSUE THREAD

**Issue by RajendraMallarapu** [SpectoLabs/hoverfly#878]
Getting below error while doing HTTPS request

Command:  curl --proxy https://localhost:8500 https://<XXX>
 Error: curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

**Comment by JohnFDavenport** [comment]
That isn't a Hoverfly error. It is likely to be some sort of misconfiguration in your setup.
