### ISSUE TITLE
Could not start Hoverfly Port 8888 was not free

### ISSUE THREAD

**Issue by kmayika** [SpectoLabs/hoverfly#882]
I get a `"Could not start Hoverfly Port 8888 was not free"`
when I run `Hoverctl start` 

And I just downloaded it and was following the tutorial on Hoverfly.io

**Comment by tommysitu** [comment]
@kmayika, that's because you have another process using port 8888. Try starting hoverfly admin on another port like this: `hoverfly -ap 8889` 

I'm closing this now, please use [Gitter channel](https://gitter.im/SpectoLabs/hoverfly) for support questions.
