### ISSUE TITLE
Node.js binding for Hoverfly?

### ISSUE THREAD

**Issue by larsthorup** [SpectoLabs/hoverfly#886]
**Is your feature request related to a problem? Please describe.**
We are using Hoverfly (via Hoverfly Java) to auto-mock external services when writing tests for our own services. This works well. However, we would like to do the same thing when writing tests for our front-end JavaScript which invokes our services. We run our JavaScript tests in Node.js. 

**Describe the solution you'd like**
It seems like it would be useful with a JavaScript/Node binding for Hoverfly. This was also hinted at in the Conclusion of a blog post back in 2017: https://specto.io/blog/2017/1/4/stubbing-http-apis-and-microservices-with-the-hoverfly-java-dsl/

**Describe alternatives you've considered**
Instead of a full binding with an orchestrator (starting and stopping the Hoverfly executable) we have considered writing a JavaScript parser for the Hoverfly JSON Capture files. However, this would fork the parsing code that already exists in Hoverfly, so would risk regressions.

Is a JavaScript/Node binding on the road map for Hoverfly?

**Comment by tommysitu** [comment]
Not at the moment, the project is lack of resource. Any contribution is welcome if there is node.js expertise on your side. 

Did you mean parsing the Go code to Javascript? 

If you're creating an orchestrator, there seems to be some javascript library let you run an executable easily, and all you need to do is writing a client to interact with Hoverfly's admin API.

Let me know if you need anything, I'm happy to help.

**Comment by larsthorup** [comment]
Thank you for the quick reply! The orchestrator would be the best way, I agree. The thing we had considered doing as a shortcut was not parsing the Go code, but parsing the JSON files containing the captured request-response-pairs.

I am not sure if we will prioritize creating an orchestrator. If so we will surely want to reach out for help, so thank you for offering it :)

I'll close this issue for now.
