### ISSUE TITLE
Is it possible to test for the absence of a header or a query param?

### ISSUE THREAD

**Issue by bric3** [SpectoLabs/hoverfly#889]
I would like to verify that the http client does not send a specific headers. And the same for query params.

E.g. I need to harness the code for future generation to make sure some headers and query param are not the request.

I've tried things like `.header("Accept-Encoding", newRegexMatcher("^$"))` without big hopes, and indeed it fails.

**Comment by tommysitu** [comment]
Are you talking about the verification feature in hoverfly-java? https://docs.hoverfly.io/projects/hoverfly-java/en/latest/pages/corefunctionality/verification.html

**Comment by bric3** [comment]
Actually I hoped to craft my stub so that they could only reply if a header wasn't present.
But I could modify them with verification api indeed. Thanks for the tip.

**Comment by tommysitu** [comment]
I think doing verification makes more sense for your use case.
