### ISSUE TITLE
Hoverfly as http proxy 

### ISSUE THREAD

**Issue by rchampa** [SpectoLabs/hoverfly#89]
Hi, hoverfly looks amazing but i'm failing trying to set it up as a proxy to modify the response for certain urls.

My python script is the same to the one here https://www.specto.io/service-virtualization-modifying-traffiic/

But I don't get  it works.

`./hoverfly --modify --middleware="./myscript"`

I expect modify all HTTP GET responses but when I use any browser every response is not customized.

**Comment by rusenask** [comment]
Hi, try launching hoverfly with debug mode enabled (-v):

./hoverfly --modify -v --middleware="./myscript.py"

then, make sure you set it as a proxy for your browser (https://support.google.com/chrome/answer/96815?hl=en-GB). Are your urls HTTP or HTTPS as well?

**Comment by rchampa** [comment]
It's http 
This is my settings but still not working
<img width="635" alt="screen shot 2016-02-04 at 12 37 43" src="https://cloud.githubusercontent.com/assets/3956444/12814007/134a0a68-cb3c-11e5-90f1-1add132e84f7.png">

**Comment by rchampa** [comment]
I remove "http://" from the field and now i get another error message.
`Hoverfly Error! Could not find recorded request, please record it first!. Got error: Bucket "rqbucket" not found! `

I have to record every request before use it? and why?

**Comment by rusenask** [comment]
No, you don't have to if you are using it with -modify flag,

`./hoverfly --modify --middleware="./myscript.py"` 

should work

**Comment by rchampa** [comment]
What is rqbucket ? I don't get this works :(

**Comment by rusenask** [comment]
Not sure whether it's related but does requests.db file appear in your hoverfly directory when you start it? I would expect this error in "virtualize" mode when no flags are supplied but with --modify flag you shouldn't get this message. 

What is your operating system? 
And can you show me exact command that you use to start hoverfly?

**Comment by rchampa** [comment]
Now I'm getting another error. This is exactly what i write:
<img width="1060" alt="screen shot 2016-02-04 at 15 59 57" src="https://cloud.githubusercontent.com/assets/3956444/12818731/4d280868-cb58-11e5-9e25-9cfa9ef0ee9d.png">

**Comment by rusenask** [comment]
Hey, change it to 

`./hoverfly -modify -middleware "/path/to/your/file.py" `

(you forgot "-middleware")

**Comment by rchampa** [comment]
I'm using macos x 
Still failing
<img width="1127" alt="screen shot 2016-02-04 at 16 13 26" src="https://cloud.githubusercontent.com/assets/3956444/12819177/4163f56c-cb5a-11e5-83b5-c131f3b0c796.png">

Even if change the code from original.
<img width="581" alt="screen shot 2016-02-04 at 16 15 18" src="https://cloud.githubusercontent.com/assets/3956444/12819213/66231dc4-cb5a-11e5-974a-050f26205f30.png">

**Comment by rusenask** [comment]
It's due to recent modification in how middleware recreates new request before sending it out, hold on a minute, I will supply a fix shortly

**Comment by rchampa** [comment]
Ok, thanks you so much.

**Comment by rchampa** [comment]
The version 0.5.6 works perfect!

**Comment by rusenask** [comment]
hey, tagged new release https://github.com/SpectoLabs/hoverfly/releases/tag/v0.5.9 can you check whether it works for you?

**Comment by rchampa** [comment]
ok, i will try.

**Comment by rchampa** [comment]
Works like a charm! and better than 0.5.6
Thanks a lot!

**Comment by rusenask** [comment]
thanks for spotting this! :)
