### ISSUE TITLE
Hoverfly is unable to capture multiple query parameters into json

### ISSUE THREAD

**Issue by srikarbittu** [SpectoLabs/hoverfly#891]
This is the url : http://10.0.75.1:8080/down/I18N?locale=en_U&update=n

and the json is 

{
	"data": {
		"pairs": [
			{
				"request": {
					"path": [
						{
							"matcher": "exact",
							"value": "/down/I18N"
						}
					],
					"method": [
						{
							"matcher": "exact",
							"value": "GET"
						}
					],
					"destination": [
						{
							"matcher": "exact",
							"value": "10.0.75.1:8080"
						}
					],
					"scheme": [
						{
							"matcher": "exact",
							"value": "http"
						}
					],
					"body": [
						{
							"matcher": "exact",
							"value": ""
						}
					],
					"query": {
						"locale": [
							{
								"matcher": "exact",
								"value": "en_U"
							}
						]
					}
				},
				"response": {
					"status": 200,
					"body": "",
					"encodedBody": false,
					"headers": {
						"Cache-Control": [
							"no-cache, no-store, max-age=0, must-revalidate"
						],
						"Content-Length": [
							"12133"
						],
						"Content-Type": [
							"application/json;charset=UTF-8"
						],
						"Date": [
							"Fri, 17 Jan 2020 06:06:56 GMT"
						],
						"Expires": [
							"0"
						],
						"Hoverfly": [
							"Was-Here"
						],
						"Pragma": [
							"no-cache"
						],
						"X-Content-Type-Options": [
							"nosniff"
						],
						"X-Frame-Options": [
							"SAMEORIGIN"
						],
						"X-Request-Id": [
							"086b8111-59ee-4ebb-b65f-2d27ced9d61a"
						],
						"X-Xss-Protection": [
							"1; mode=block"
						]
					},
					"templated": false
				}
			}
		],
		"globalActions": {
			"delays": [],
			"delaysLogNormal": []
		}
	},
	"meta": {
		"schemaVersion": "v5",
		"hoverflyVersion": "v1.1.3",
		"timeExported": "2020-01-17T11:37:12+05:30"
	}
}

In query section we are seeing only locale parameter but not update 

"query": {
						"locale": [
							{
								"matcher": "exact",
								"value": "en_U"
							}
						]
					}
but there is no update parameter why ?
It would we very help for me if any help on this .Thanks in advance

**Comment by ns3777k** [comment]
@srikarbittu 
I tried that with google and it works fine.

Start server in capture mode:
```
$ hoverfly -capture
INFO[2020-01-28T00:12:43+03:00] Using memory backend                         
INFO[2020-01-28T00:12:43+03:00] Proxy prepared...                             Destination=. Mode=capture ProxyPort=8500
INFO[2020-01-28T00:12:43+03:00] current proxy configuration                   destination=. mode=capture port=8500
INFO[2020-01-28T00:12:43+03:00] serving proxy                                
INFO[2020-01-28T00:12:43+03:00] Admin interface is starting...                AdminPort=8888
```

Curl with two parameters:
```
$ curl --proxy "http://localhost:8500" "http://google.com/down/I18N?locale=en_U&update=n"
```

Export captures pairs into a file:
```
$ hoverctl export test.json
```

Examine the file:
```json
...
"query": {
    "locale": [
        {
            "matcher": "exact",
            "value": "en_U"
        }
    ],
    "update": [
        {
            "matcher": "exact",
            "value": "n"
        }
    ]
}
...
```

Both query matchers are there.

What am I missing here? Can you provide more details? A step by step guide? Does this work for you curling google?

**Comment by tommysitu** [comment]
As @ns3777k had tried out, I don't think this is a bug. Hoverfly supports capturing multiple query params.   If you still have an issue, please reopen with more info for reproducing the issue.
