### ISSUE TITLE
JSON request body whose root starts with an array fails to match with JsonPath/JsonPartial as matcher

### ISSUE THREAD

**Issue by cvadityaflipkart** [SpectoLabs/hoverfly#895]
## Description of the bug
JSON request body whose root starts with an array fails to match with JsonPath as matcher.

## Steps to reproduce the issue
Any http request with the following body
https://jsonplaceholder.typicode.com/posts

and the simulation file containing the following matcher
```
        "body" : [ {
          "matcher" : "JsonPath",
          "value" : "$[0]"
        } ]
```
Edit: It also occurs with JsonPartial
```
        "body" : [ {
          "matcher" : "jsonpartial",
          "value" : "{\"userId\": 1}"
        } ]
```
### Observed result
**Hoverfly error messages seen (If none, say none)**
```
Failed to unmarshal body to JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
```
**If possible, add screenshots to help explain your problem**

### Expected result
No error

## Additional relevant information
1. Hoverfly version: 1.1.3
2. Schema Version: v5
3. Probable fix at https://github.com/SpectoLabs/hoverfly/blob/7c00820058912ad13d8060b2ab996ff5c573b934/core/matching/matchers/json_path_match.go#L38

**Comment by tommysitu** [comment]
fixed in v1.1.4
