### ISSUE TITLE
Add support for custom variables

### ISSUE THREAD

**Issue by maxmoehl** [SpectoLabs/hoverfly#900]
**Is your feature request related to a problem? Please describe.**
I have a simulation that sends back lists, these lists get filled with data extracted from the request using xpath (same statement over and over again), due to huge xml files these xpath statements are quite long and complicated. It would be really nice to be able to define some variables at the top that can later be used for templating.

**Describe the solution you'd like**
A new field in the request object (or somewhere else) with the possibility to load values from the request and store them in variables. For example:
```json
"request.variables": [
  {
    "name": "varOne",
    "method": "xpath",
    "path": "/some/xapth/expression"
  }
]
```
`method` could be xpath or jsonpath and path needs to be set accordingly
later in the template you can access those vars with: `{{ var "varOne" }}`

**Describe alternatives you've considered**
Copy paste those xpath statements but making changes is a nightmare.
I guess using middelware would also somehow work but it is fairly complicated since you don't have access to the request.

**Additions**
This could also be used for other data types like dates. To be able to do something like this it would need to be more generic which complicates things. Maybe something similiar to the templating syntax:
```
"request.variables": [
  {
    "name": "valueFromXpath",
    "method": "Request.Body",
    "args": ["xpath", "/some/xapth/expression"]
  },
  {
    "name": "dateValue",
    "method": "now",
    "args": ["", "2006-01-02T15:04:05Z"]
  },
]
```

**Comment by kapishmalik** [comment]
@tommysitu  I can work on this feature request. It will be really helpful as we also have such use cases.

**Comment by tommysitu** [comment]
@kapishmalik  are you considering to store the custom variables in the simulation file?

**Comment by kapishmalik** [comment]
@tommysitu yea, I would be defining them in simulation files. I need to think more about exact format and things which we can support. You can assign this to me . I will get back with complete implementation details around the same.

**Comment by kapishmalik** [comment]
@tommysitu  I am planning to add support for custom literals defined by the user and custom variables which can be values fetched from either XPath or JsonPath. We will be later adding support for global literals which can be used in any template response. Let me know if we are good to implement this.

Literals can be accessed as - {{literal "literal1" }}
Vars can be accessed as {{ var "varOne" }}

I will be adding support later to add support for custom methods as well.

```"literals": [
            {
              "name": "<literal1>",
              "value": ["value1", "value2", "value3"]
            },
            {
              "name": "<literal2>",
              "value": "value2"
            },
            {
              "name": "<literal3>",
              "value": {
                "mapKey1" : "mapValue1",
                "mapKey2" : "mapValue2"
              }
            },
          ],
          "variables" : [
              {
                 "name": "varOne",
                 "method": "xpath",
                 "path": "/some/xapth/expression"
              },
              {
                 "name": "varTwo",
                 "method": "jsonPath",
                 "path": "/some/xapth/expression"
              }
          ]

**Comment by kapishmalik** [comment]
@tommysitu  raised [PR](https://github.com/SpectoLabs/hoverfly/pull/1032) for the same.

**Comment by kapishmalik** [comment]
@maxmoehl  We have added support. You can read docs and get started.

https://docs.hoverfly.io/en/latest/pages/keyconcepts/templating/templating.html#global-literals-and-variables

**Comment by kapishmalik** [comment]
@tommysitu  I believe that we can close this issue.

**Comment by kapishmalik** [comment]
@tommysitu I believe now everything in this issue is resolved. We can close this issue.

**Comment by maxmoehl** [comment]
Thanks!
