### ISSUE TITLE
Chrome still show connection not private error after cert is added into key chain access

### ISSUE THREAD

**Issue by wunaidage** [SpectoLabs/hoverfly#901]
Proxy Setting:
![image](https://user-images.githubusercontent.com/12276316/74802571-4727de80-52a8-11ea-95df-91059df7972a.png)

Cert in trusted
![image](https://user-images.githubusercontent.com/12276316/74802632-76d6e680-52a8-11ea-959e-2c61b811845b.png)

I used this command to start
```
hoverctl start --certificate cert.pem --key key.pem
```
but still the console gives 
![image](https://user-images.githubusercontent.com/12276316/74802743-c3babd00-52a8-11ea-90e1-324adddda93d.png)
and browser gives
![image](https://user-images.githubusercontent.com/12276316/74802844-fb296980-52a8-11ea-9d49-b03b6065d0b9.png)

Please help

**Comment by tommysitu** [comment]
not sure if it's related to this: https://community.sophos.com/products/unified-threat-management/f/web-protection-web-filtering-application-visibility-control/115345/issue-with-ios-13-mac-os-10-15-ssl-certificate-requirements-for-transparent-proxy

The error in Chrome is actually: `ERR_CERT_WEAK_KEY` which makes me think that the hoverfly tls key needs reviewing.

**Comment by wunaidage** [comment]
thanks for reply! so does it mean hoverfly's 1024 key is too weak? Do we have options to generate 2048 bit key using  `hoverfly -generate-ca-cert`?

**Comment by wunaidage** [comment]
I googled some and found this https://podtech.io/os/mac-osx/chrome-catalina-certificate-issue/

**Comment by wunaidage** [comment]
check your code on generating the cert, looks like you are making 5 years expiration: https://github.com/SpectoLabs/hoverfly/blob/e523f31338156dfad2d187c4f7f527c41fff4ee0/core/cmd/hoverfly/main.go#L240
The article I posted said `The validity period may not be longer than 825 days.` could this be the reason?

**Comment by wunaidage** [comment]
any suggestion avoiding this?

**Comment by wunaidage** [comment]
> thanks for reply! so does it mean hoverfly's 1024 key is too weak? Do we have options to generate 2048 bit key using `hoverfly -generate-ca-cert`?

seems it's a 2048 key...

**Comment by wunaidage** [comment]
looks like hoverfly used sha1 to sign the cert. apple's new policy drops support for sha1: 

> TLS server certificates and issuing CAs must use a hash algorithm from the SHA-2 family in the signature algorithm. SHA-1 signed certificates are no longer trusted for TLS.

the code is here  https://github.com/SpectoLabs/hoverfly/blob/0afeecee42db659440291cade4f94098c5ef0a06/core/certs/certs.go#L87
and here
https://github.com/SpectoLabs/hoverfly/blob/0afeecee42db659440291cade4f94098c5ef0a06/core/certs/certs.go#L137
@tommysitu I'm new to go and I don't know if my finding is right or not

**Comment by ns3777k** [comment]
probably related to https://github.com/SpectoLabs/hoverfly/issues/898

**Comment by tommysitu** [comment]
Just tested @ns3777k 's fix. It works! 🎉  @wunaidage  You can try using the latest build for Mac OS: https://storage.googleapis.com/hoverfly-master-builds/latest/hoverfly_bundle_OSX_amd64.zip

**Comment by wunaidage** [comment]
thank you so much!!

**Comment by wunaidage** [comment]
looks good. when will you release?

**Comment by tommysitu** [comment]
will do a bug fix release this week

**Comment by tommysitu** [comment]
fix released in v1.1.5

**Comment by wunaidage** [comment]
thanks!
