### ISSUE TITLE
407 on authentication in https case

### ISSUE THREAD

**Issue by pashaosipyants** [SpectoLabs/hoverfly#926]
## Steps to reproduce the issue

1. Run hoverfly with flags -spy -auth -username=u -password=p
2. Do `curl -k --proxy http://p:u@localhost:8500 https://example.com/`

### Observed result

```
407 Proxy authentication required
```

### Expected result

Successful response of example.com

## Additional relevant information
1. Hoverfly version: _checked with master, 1.1.0-1.1.4_
2. Anything that might help us to diagnose the problem: _PR #925_

**Comment by tommysitu** [comment]
Thanks for the fix! We had never spotted it as it's a rarely used feature. 

I've also updated the functional tests: https://github.com/SpectoLabs/hoverfly/pull/928
