### ISSUE TITLE
test case fails randomly in local environment

### ISSUE THREAD

**Issue by ri-tatsu** [SpectoLabs/hoverfly#937]
## Description of the bug

Running locally, a test case for `/api/v2/shutdown` will pass/fails randomly.

## Steps to reproduce the issue

`make test` on local computer instead of CI on cloud.
(I use a virtual machine with: CPU: 1.8GHz*3, Memory:4G, OS: Ubuntu 20.04 LTS)

### Observed result
**Hoverfly error messages seen (If none, say none)**
```
• Failure [0.014 seconds]
/api/v2/shutdown
/home/ri-tatsu/go/src/github.com/SpectoLabs/hoverfly/functional-tests/core/api/shutdown_api_v2_test.go:12
  DELETE
  /home/ri-tatsu/go/src/github.com/SpectoLabs/hoverfly/functional-tests/core/api/shutdown_api_v2_test.go:27
    should shutdown after 10 seconds [It]
    /home/ri-tatsu/go/src/github.com/SpectoLabs/hoverfly/functional-tests/core/api/shutdown_api_v2_test.go:29

    Expected
        <string>: Get "http://localhost:46581/api/v2/hoverfly/mode": read tcp 127.0.0.1:38060->127.0.0.1:46581: read: connection reset by peer
    to contain substring
        <string>: connection refused

    /home/ri-tatsu/go/src/github.com/SpectoLabs/hoverfly/functional-tests/core/api/shutdown_api_v2_test.go:37

```
**If possible, add screenshots to help explain your problem**

![hoverfly-fails](https://user-images.githubusercontent.com/64121967/82400380-241cee80-9a92-11ea-937f-e3e810d75483.png)

### Expected result

It should not fails even the machine is a little bit slow.

## Additional relevant information
1. Hoverfly version: master branch
2. Anything that might help us to diagnose the problem

I think it may be a mistake of the test case.

```go
It("should shutdown after 10 seconds", func() {
	response := functional_tests.DoRequest(sling.New().Delete("http://localhost:" + hoverfly.GetAdminPort() + "/api/v2/shutdown"))
	Expect(response.StatusCode).To(Equal(http.StatusOK))

	request, _ := sling.New().Get("http://localhost:" + hoverfly.GetAdminPort() + "/api/v2/hoverfly/mode").Request()
	_, err := http.DefaultClient.Do(request)

	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("connection refused"))

})
```
The description says that is should shutdown **after 10 seconds**, but actually it checks the states immediately after shutdown request sent.

Therefore,
- If hoverfly is closed before the second request, it gets `connection refused` because a socket connection can not established. In this case, it will PASS.
- If hoverfly is closed after the second request started, it gets `connection reset by peer` because a connection is already established but forced to close during the second request reading/writing on it. In this case, it will FAILED.

In my opinion, there should have something like
```go
time.Sleep(time.Second * 10)
```
between the two requests. It should wait for 10 seconds just as the description said.

**Comment by tommysitu** [comment]
the shutdown should be pretty quick as it just calls `os.Exit`, adding a fixed 10s will slow test down quite a lot for everyone. I wonder if some kind of polling can be used to check the status of a second request, and return as soon as it passed. Also the test description is misleading, something like this is better `should shut down immediately` (although it could have a little bit delay on slow vms)

**Comment by lhttjdr** [comment]
Thanks for your replay. 
Considering its performance and accuracy, polling requests may be the proper solution as you said. For example, it tries to do requests after 0s, 1s, 2s, 3s, 5s, 8s and fails after all tries finished but hoverfly instance still running.  However, this makes the logic a little bit complex. May I make a pull request of such an implementation? Or, do we just need fix the description as you mentioned?

**Comment by ri-tatsu** [comment]
Thanks for your replay.
Considering its performance and accuracy, polling requests may be the proper solution as you said. For example, it tries to do requests after 0s, 1s, 2s, 3s, 5s, 8s and fails after all tries finished but hoverfly instance still running. However, this makes the logic a little bit complex. May I make a pull request of such an implementation? Or, do we just need fix the description as you mentioned?

**Comment by tommysitu** [comment]
tbh, this one has never occurred to me. It's not worth spending time on it. Would `time.Sleep(time.Second * 2)` solve the problem on your end?

**Comment by ri-tatsu** [comment]
Yes, 2 seconds is enough for me. I tried about 10 times and all tries succeed.
(VM: CPU: 1.8GHz*3, Memory:4G, OS: Ubuntu 20.04 LTS)

**Comment by tommysitu** [comment]
fixed in master
