### ISSUE TITLE
Allow Docker Hoverfly to run in DEBUG

### ISSUE THREAD

**Issue by kishorekkota** [SpectoLabs/hoverfly#940]
I do not see if there is an opiton to run Docker Image in debug mode ? Are the hoverfly setting exposed through ENV when spinning up it as a container ? If not, can this added as a feature.

**Comment by tommysitu** [comment]
Did you mean running the hoverfly docker image with the config flags? You can check it out here: https://docs.hoverfly.io/en/latest/pages/introduction/downloadinstallation.html#docker

**Comment by tommysitu** [comment]
question for gitter
