### ISSUE TITLE
Latest master breaks `-spy` mode passthrough for `-plain-http-tunneling`

### ISSUE THREAD

**Issue by ttiurani** [SpectoLabs/hoverfly#948]
Related to comment:

https://github.com/SpectoLabs/hoverfly/issues/944#issuecomment-683882641

The latest master https://github.com/SpectoLabs/hoverfly/commit/dd42a5b462d1fdbdac2b8dc2bf90a8d767a4caf3 breaks `-plain-http-tunneling` passthrough to the real server, where for two commits older https://github.com/SpectoLabs/hoverfly/commit/9a0eee5f5dfd41e4597dc0725010048e94187794 works.

The steps to reproduce these both with local docker are at

https://github.com/ttiurani/hoverflybug

**Comment by tommysitu** [comment]
@ttiurani could you try reverting this change, and build hoverfly locally? 
https://github.com/SpectoLabs/hoverfly/pull/945/files#diff-d50e833802b7f6fce13cfdf8c5a08b94L52-L57

I think that's the easier way to ensure it works for your use case.

**Comment by ttiurani** [comment]
I can confirm that with this patch

```patch
diff --git a/core/modes/spy_mode.go b/core/modes/spy_mode.go
index a8649ab5..2dc3a61f 100644
--- a/core/modes/spy_mode.go
+++ b/core/modes/spy_mode.go
@@ -49,7 +49,11 @@ func (this SpyMode) Process(request *http.Request, details models.RequestDetails

        if matchingErr != nil {
                log.Info("Going to call real server")
-               response, err := this.Hoverfly.DoRequest(request)
+               modifiedRequest, err := ReconstructRequest(pair)
+               if err != nil {
+                       return ReturnErrorAndLog(request, err, &pair, "There was an error when reconstructing the request.", Spy)
+               }
+               response, err := this.Hoverfly.DoRequest(modifiedRequest)
                if err == nil {
                        log.Info("Going to return response from real server")
                        return newProcessResult(response, 0, nil), nil
```

I was able to now use nginx `proxy_pass` even with `-plain-http-tunneling` using both `curl` and also `netty`. Thank you so much for your help in fixing this, we can now expand our use of hoverfly a lot in our test environments 💯

**Comment by tommysitu** [comment]
thank you for trying it out. I've reverted the changes, will kick off a bugfix release this week.
