### ISSUE TITLE
Release hoverfly for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [SpectoLabs/hoverfly#949]
Hi Team,

I am working on project ‘Drone’, which uses hoverfly binaries. I am planning to run drone on ARM64 platform, but hoverfly arm64 binaries are not available in releases. I have checked that hoverfly supports the arm64 platform. I have built hoverfly on a local ARM64 machine with ubuntu: bionic. Following are the steps taken:

1.  Installed go version 1.15 from <https://golang.org/dl>
2.  git clone https://github.com/SpectoLabs/hoverfly.git
3.  cd hoverfly
4.  make build

After ‘make build’, binaries are getting created in the ‘target’ directory. Below is the output to ‘file’ command:
~~~
$ file hoverctl
hoverctl: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=LHhD07aA9M0SMnC2OvbE/wgFs1bU6mxgFGHcri9PC/289NjWncRd8RM0i70w0o/6-eE8CxdcI-G6jiliSOM, not stripped
~~~

So, it will be really helpful if hoverfly Linux/ARM64 binaries become available in releases.

**Comment by tommysitu** [comment]
available in https://github.com/SpectoLabs/hoverfly/releases/tag/v1.3.2
