### ISSUE TITLE
Allow for remote bodyFiles

### ISSUE THREAD

**Issue by anthonyshull** [SpectoLabs/hoverfly#951]
**Is your feature request related to a problem? Please describe.**
I want to be able to run hoverfly locally, but load remote simulations. This is possible using `--import` but bodyFiles cannot be loaded remotely. I want to do this so that third-party contributors can work off of the same set of simulations.

**Describe the solution you'd like**
Just like with `--import`, I would like to be able to reference remote bodyFiles.

**Describe alternatives you've considered**
One alternative would be to write a tool to load files and inject JSON strings into simulation files and load those remotely.

**Comment by ns3777k** [comment]
I think i'm gonna make a PR next week on this.

**Comment by tommysitu** [comment]
available in https://github.com/SpectoLabs/hoverfly/releases/tag/v1.3.2
