### ISSUE TITLE
RPC support

### ISSUE THREAD

**Issue by L-sing** [SpectoLabs/hoverfly#952]
Hope this tool can support RPC,like grpc、dubbo

**Comment by JohnFDavenport** [comment]
@L-sing We have support for http/2 or grpc but it's not built into this project for a myriad of reasons. Take a look at https://github.com/SpectoLabs/hoverfly-java-grpc and contact me direct if that approximates what you are looking for stating what you need.

**Comment by JohnFDavenport** [comment]
Closing issue as it's not really specific enough to produce any tasks & it is unclear what the OP's use-case is.
