### ISSUE TITLE
How to force use python3

### ISSUE THREAD

**Issue by rchampa** [SpectoLabs/hoverfly#96]
Hi, I miss a lot work with python3. Is there any way to select python3 instead of work with python2 by default?

**Comment by rusenask** [comment]
yes, you can pass whole command how to execute your script:
`./hoverfly -modify -middleware "python3 middleware/python_script.py"`

**Comment by rusenask** [comment]
added more info on readme how to execute commands through middleware flag:
https://github.com/SpectoLabs/hoverfly#middleware
