### ISSUE TITLE
Error in adding a day to a date template

### ISSUE THREAD

**Issue by DavidLivingston** [SpectoLabs/hoverfly#962]
## Description of the bug
adding 1 day to now function using the response template returns the current date and not adding 1 day to now function reduces the date by 1010 years, please used the below date templates to reproduce to reproduce the issue

## Steps to reproduce the issue
compare the result of the below two templates
```
(1) "{{now '' 'Mon, 01 Feb 2021 17:15:13 GMT'}}"
(2) "{{now '1d' 'Mon, 01 Feb 2021 17:15:13 GMT'}}"
```
### Observed result
**Hoverfly error messages seen (If none, say none)**
```
(1)Mon, 02 Feb 1012 27:20:28 GMT
(2)Tue, 02 Feb 2022 27:20:28 GMT
```

**Template in Simulation file** 
![image](https://user-images.githubusercontent.com/12004240/106516755-6e82b600-64cf-11eb-9793-1aadddebf486.png)
**response Output** 
![image](https://user-images.githubusercontent.com/12004240/106516883-a25ddb80-64cf-11eb-8c10-843be8ffea20.png)

### Expected result
```
(1)Mon, 01 Feb 2022 27:20:28 GMT
(2)Tue, 02 Feb 2022 27:20:28 GMT
```
## Additional relevant information
1. Hoverfly version: 1.3.1
2. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
That's because Golang requires date formating to use a "special" layout parameter (🤷‍♂️ ): https://yourbasic.org/golang/format-parse-string-time-date-example/

this one should work:
`{{ now '' 'Mon, 02 Jan 2006 15:04:05 MST' }}` 

I'll update the doc to make it a bit more clear

**Comment by DavidLivingston** [comment]
Thanks @tommysitu  , that works !
