### ISSUE TITLE
Specifying a json object in request matcher crashes the hoverfly server

### ISSUE THREAD

**Issue by DavidLivingston** [SpectoLabs/hoverfly#965]
## Description of the bug
Specifying a json object in request matcher crashes the hoverfly server
Have to restart the server every time

### Observed result
**Hoverfly error messages seen (If none, say none)**
None
**Matcher Example**
```           
{
      "matcher": "json",
     "value": "{\"PreferredLanguage\":\"en-gb\",\"data1\":[{\"data2\":\"xyz\",\"data3\":\"abc\"}]}"
}
```
**If possible, add screenshots to help explain your problem**
<img width="1166" alt="Screenshot 2021-02-16 at 9 19 09 pm 4" src="https://user-images.githubusercontent.com/12004240/108123048-294caf80-709d-11eb-977a-9d4c1ada3a9b.png">
<img width="783" alt="Screenshot 2021-02-16 at 9 13 49 pm 1" src="https://user-images.githubusercontent.com/12004240/108123250-76c91c80-709d-11eb-87d1-8641c98182b5.png">

### Expected result
The server should not crash and serve the response that is matched or an appropriate error message must be displayed 

## Additional relevant information
1. Hoverfly version:  1.3.2
2. Anything that might help us to diagnose the problem

**Comment by tommysitu** [comment]
I can't reproduce this issue with hoverfly 1.3.2 running locally. I'm using this simulation with the same json matcher. 
[json-matcher.txt](https://github.com/SpectoLabs/hoverfly/files/6039426/json-matcher.txt)

and the commands: 
```
$ curl -X PUT localhost:8500 --header 'Content-Type: application/json' -d '{
  "PreferredLanguage": "en-gb",
  "data1": [
    {
      "data2": "xyz",
      "data3": "abc"
    }
  ]
}'

$ hoverctl status

+------------+---------------------+
| Hoverfly   | running             |
| Admin port |                8888 |
| Proxy port |                8500 |
| Proxy type | reverse (webserver) |
| Mode       | simulate            |
| Middleware | disabled            |
| CORS       | disabled            |
+------------+---------------------+
```

**Comment by tommysitu** [comment]
not able to reproduce
