### ISSUE TITLE
param -v don't show output where script crash

### ISSUE THREAD

**Issue by rchampa** [SpectoLabs/hoverfly#97]
In previous versions when something fails in the script the out of that fail was showed on console.
Now I'm getting a crash but i can't see the line where the problem is.

**Comment by rusenask** [comment]
interesting, haven't changed anything on that part of the code, I will have a look at it tomorrow

**Comment by rusenask** [comment]
Hey, checked it yesterday - middleware errors show up in the log. Are you still having this issue?

**Comment by rchampa** [comment]
Ok I will try tomorrow.

**Comment by rusenask** [comment]
execution error and stderr is now visible in logs
