### ISSUE TITLE
Requests from localhost not captured

### ISSUE THREAD

**Issue by BalachanderJ** [SpectoLabs/hoverfly#971]
## Description of the bug
I have an express server currently running at localhost:7001 that serves mock content for all my REST backend. I want all this data captured in a simulation file so I can eliminate this express server and use Hoverfly in simulate mode.

## Steps to reproduce the issue
I started hoverfly in Capture mode which is obviously listening in localhost:8500. I started my UI on my chrome browser (localhost:3000) with proxy set as localhost:8500. All backend requests from my UI will hit localhost:7001.

### Observed result
None of the localhost:7001 requests are captured in simulation json. But I do see other requests that hits a different host captured in simulation json file.

### Expected result
All requests should be captured.

## Additional relevant information
1. Hoverfly version: 1.3.2

Please clarify if am missing anything.

**Comment by ns3777k** [comment]
Just checked this, everything works fine. If you're still struggling, you need to tell more details like os, commands you use, and etc. also try to use curl instead of browser.

**Comment by tommysitu** [comment]
you probably have bypass proxy settings for localhost, I don't think this is a hoverfly issue.
