### ISSUE TITLE
Unable to start hoverfly on Mac OS - Catalina

### ISSUE THREAD

**Issue by manish2788** [SpectoLabs/hoverfly#972]
## Description of the bug
While trying to run the commands to start hoverfly, the app errors out with timeout warning

## Steps to reproduce the issue
- Download hoverfly from following location on mac
https://github.com/SpectoLabs/hoverfly/releases/download/v1.3.0/hoverfly_bundle_OSX_amd64.zip
- Configure the path variable in bash_profile
- Run the command to start hoverfly -  ```hoverctl start```
### Observed result
```
Timed out waiting for Hoverfly to become healthy, returns status: 0
```
## Additional relevant information
1. Hoverfly version: master-3578 OSX_amd64
2. Anything that might help us to diagnose the problem
macOS Catalina 10.15.7

**Comment by manish2788** [comment]
Update: Same issue I am observing over BigSur OS too.

**Comment by manish2788** [comment]
Hello Team, 
It has been more than a month but I have not received any update on the issue.
Can you please confirm if my issue would addressed?

**Comment by ns3777k** [comment]
Hey. I'm on big sur as well and nothing like you described happening.

```
$ wget "https://github.com/SpectoLabs/hoverfly/releases/download/v1.3.3/hoverfly_bundle_OSX_amd64.zip"
$ unzip hoverfly_bundle_OSX_amd64.zip
$ ./hoverctl start
Hoverfly is now running

+------------+------+
| admin-port | 8888 |
| proxy-port | 8500 |
+------------+------+
```

Makes me think it's some your local issue. Did you check "Security & Privacy" in settings? Does it ask you for permissions to run the binary?
Does the same thing happen when you run `hoverfly` binary and not `hoverctl start`?

@manish2788

**Comment by tommysitu** [comment]
I never came across this issue on MacOS. You should try using `brew` to install hoverfly: https://docs.hoverfly.io/en/latest/pages/introduction/downloadinstallation.html#homebrew-macos

**Comment by manish2788** [comment]
> Hey. I'm on big sur as well and nothing like you described happening.
> 
> ```
> $ wget "https://github.com/SpectoLabs/hoverfly/releases/download/v1.3.3/hoverfly_bundle_OSX_amd64.zip"
> $ unzip hoverfly_bundle_OSX_amd64.zip
> $ ./hoverctl start
> Hoverfly is now running
> 
> +------------+------+
> | admin-port | 8888 |
> | proxy-port | 8500 |
> +------------+------+
> ```
> 
> Makes me think it's some your local issue. Did you check "Security & Privacy" in settings? Does it ask you for permissions to run the binary?
> Does the same thing happen when you run `hoverfly` binary and not `hoverctl start`?
> 
> @manish2788

Thanks for the response @ns3777k .
Yes, I have checked "Security & Privacy" in settings. Mac does asks permission to run the binary, I grant the permissions and whenever I run again I get the same error of timeout.
`hoverfly` binary execution is working fine though. It happens only for `hoverctl start`

I would highly appreciate any pointers to debug this issue as this tool is very useful and I intend to use in my project.

**Comment by ns3777k** [comment]
@manish2788 any extra info if you run `./hoverctl start --verbose` ?
does it work if you install hoverfly from brew as @tommysitu mentioned?

**Comment by manish2788** [comment]
@ns3777k When I run  ```./hoverctl start --verbose``` I get following logs printed on console.
```
Current target: local

DEBU[0000] [<path to the directory>/hoverfly/hoverfly -log-level=info -ap=8888 -pp=8500] 
Timed out waiting for Hoverfly to become healthy, returns status: 0
```

**Comment by ns3777k** [comment]
@manish2788  And what about brew?

**Comment by ns3777k** [comment]
You can also try to search over the mac logs (https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/) something like hoverfly / hoverctl / 8500 / 8888.
Also double check the `$HOME/.hoverfly/config.yaml` file for weird settings.
Maybe that would much efficiently to get in touch with Apple Support.

**Comment by manish2788** [comment]
@ns3777k Thanks!! Let me explore the mac logs and yaml file.

**Comment by tommysitu** [comment]
don't think this one is related to hoverfly
