### ISSUE TITLE
hoverfly serves public directory from admin interface

### ISSUE THREAD

**Issue by ns3777k** [SpectoLabs/hoverfly#973]
## Description of the bug

Funny thing that took me a while to figure out.
When hoverfly is started it serves files from the `public` directory from admin interface.
Image you have a frontend project with `public` directory and `index.html` inside it. When you start hoverfly from this path, the `index.html` will replace the admin ui dashboard.

## Steps to reproduce the issue

1. Create `project` directory and cd there.
3. Create `public` directory and put `index.html` with any content you want there.
4. Get back up to the `project` directory and start hoverfly from there.
5. Try to open up localhost:8888 and instead of dashboard you'll see the content of the `index.html` file.

### Observed result

Admin UI serves the local `index.html` file instead of dashboard.

### Expected result

Admin UI serves the dashboard.

## Additional relevant information

I think the solution is to remove `negroni.NewStatic(http.Dir("public"))` from https://github.com/SpectoLabs/hoverfly/blob/master/core/admin.go#L29 since dashboard files are packed with statikFS.

Ready to make PR.

**Comment by tommysitu** [comment]
Yeah the dashboard is served here already: `mux = this.addDashboardRoutes(router)`, we can get rid of the bit you suggest.  Good finding!
