### ISSUE TITLE
Server Error with Basic Tutorial

### ISSUE THREAD

**Issue by MatthewDGlynn** [SpectoLabs/hoverfly#982]
## Description of the bug
during basic tutorial and running the following command, getting 500 error. 
Command: curl --proxy http://localhost:8500 http://time.jsontest.com

Error:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

## Steps to reproduce the issue
Install via homebrew
Start and run in capture
run: curl --proxy http://localhost:8500 http://time.jsontest.com

### Observed result
**Hoverfly error messages seen (If none, say none)**
The server encountered an error and could not complete your request.
<img width="849" alt="Screen Shot 2021-08-30 at 9 22 44 AM" src="https://user-images.githubusercontent.com/89787218/131345899-a2957622-172f-4a4a-b836-1f78b3efe7bc.png">

**If possible, add screenshots to help explain your problem**

## Additional relevant information
1. Hoverfly version: v1.3.3
2. Anything that might help us to diagnose the problem

**Comment by ns3777k** [comment]
That's because http://time.jsontest.com is down for now) you can use any other site to test hoverfly is ok.

**Comment by tommysitu** [comment]
@ns3777k is right, it's not a hoverfly bug. We should update the doc with a different site

**Comment by ns3777k** [comment]
@tommysitu can be closed. time.jsontest.com is back online.
